### ISSUE TITLE
Problems building qt-client on OSX Mavericks

### ISSUE THREAD

**Issue by dwasyluk** [litecoin-project/litecoin#121]
I'm trying to compile the latest qt wallet client on OSX Mavericks. If I run makefile.osx I get a working litecoind without issue. However, when I try to run qmake/make on the .pro file I get the following error:

Undefined symbols for architecture x86_64:
  "Db::verify(char const*, char const*, std::ostream*, unsigned int)", referenced from:
      CDBEnv::Verify(std::string, bool (*)(CDBEnv&, std::string)) in db.o
      CDBEnv::Salvage(std::string, bool, std::vector<std::pair<std::vector<unsigned char, std::allocator<unsigned char> >, std::vector<unsigned char, std::allocator<unsigned char> > >, std::allocator<std::pair<std::vector<unsigned char, std::allocator<unsigned char> >, std::vector<unsigned char, std::allocator<unsigned char> > > > >&) in db.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Litecoin-Qt.app/Contents/MacOS/Litecoin-Qt] Error 1

I think this may have to do with how makefile.osx builds the leveldb libs/links vs how the Makefile generated by qmake and the .pro file builds leveldb/links but I can't get a valid build. I'm using Macports and OSX Mavericks, boost +universal and db48 +universal.

**Comment by kediacorp** [comment]
brew install boost miniupnpc openssl berkeley-db4

Next: makefile.osx will need a little touchup:

CXX=llvm-g++
DEPSDIR=/usr/local/opt

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(DEPSDIR)/include" \
 -I"$(DEPSDIR)/berkeley-db4/include" \
 -I"$(DEPSDIR)/miniupnpc/include" \
 -I"$(DEPSDIR)/boost/include" \
 -I"$(DEPSDIR)/openssl/include"

LIBPATHS= \
 -L"$(DEPSDIR)/lib" \
 -L"$(DEPSDIR)/berkeley-db4/lib" \
 -L"$(DEPSDIR)/miniupnpc/lib" \
 -L"$(DEPSDIR)/boost/lib" \
 -L"$(DEPSDIR)/openssl/lib"

...

ifdef STATIC
# Build STATIC if you are redistributing the bitcoind binary
TESTLIBS += \
 $(DEPSDIR)/boost/lib/libboost_unit_test_framework-mt.a
LIBS += \
 $(DEPSDIR)/berkeley-db4/lib/libdb_cxx-4.8.a \
 $(DEPSDIR)/boost/lib/libboost_system-mt.a \
 $(DEPSDIR)/boost/lib/libboost_filesystem-mt.a \
 $(DEPSDIR)/boost/lib/libboost_program_options-mt.a \
 $(DEPSDIR)/boost/lib/libboost_thread-mt.a \
 $(DEPSDIR)/boost/lib/libboost_chrono-mt.a \
 $(DEPSDIR)/openssl/lib/libssl.a \
 $(DEPSDIR)/openssl/lib/libcrypto.a \

...

# osx 10.9 has changed the stdlib default to libc++. To prevent some link error, you may need to use libstdc++
#CFLAGS += -stdlib=libstdc++

When building Qt Client change all /usr/opt/Cellar references to /usr/local/opt

Have Fun!

**Comment by wtogami** [comment]
https://github.com/litecoin-project/litecoin/tree/master-0.10
