### ISSUE TITLE
Arch Linux packages

### ISSUE THREAD

**Issue by xaoseric** [litecoin-project/litecoin#137]
Hello,
I was looking in the arch linux package repository, and didn't find any litecoin package. From the looks of it, it shouldn't be too hard to make a litecoin-qt and litecoin-deamon package.

https://wiki.archlinux.org/index.php/Arch_User_Repository#community_repository

As long as litecoin has the same dependencies  that bitcoin does, it shouldn't be too hard to do.

https://www.archlinux.org/packages/community/i686/bitcoin-daemon/
https://www.archlinux.org/packages/community/i686/bitcoin-qt/

**Comment by shaolinfry** [comment]
This should be handled by a community member. There is a Bitcoin package which should be basically identical for Bitcoin Core 0.13.2 as well as Litecoin Core 0.13.2.
