### ISSUE TITLE
issues with boost

### ISSUE THREAD

**Issue by alphonse23** [litecoin-project/litecoin#161]
Hello, I'm trying to compile litecoin on a mac osx mavericks using this guide: https://litecoin.info/Compiling_the_Litecoin_daemon_from_source_on_Debian. I keep running into issues with boost:
```
c++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/Users/Sean/litecoin/src -I/Users/Sean/litecoin/src/obj -DUSE_UPNP=1 -DUSE_IPV6=1 -I/Users/Sean/litecoin/src/leveldb/include -I/Users/Sean/litecoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:6:10: fatal error: 'boost/algorithm/string/classification.hpp' file not found
#include <boost/algorithm/string/classification.hpp>
         ^
1 error generated.
make: *** [obj/alert.o] Error 1
```
Do I have to add boost to my cpp path or something. How do I include it with the make command?

**Comment by erm3nda** [comment]
I have similiar problem compiling a bitcoin derived coin too. I've sucessfully compiled other wallets with boost libraries, so I cannot figure why is that missing and what to replace. Packages at apt-get seems fine, so... what?

**Comment by ajbraus** [comment]
+1

**Comment by simonmullaney** [comment]
I have the same problem,

make -f makefile.unix USE_UPNP=-
c++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/Users/simonmullaney/Downloads/simoncoin/src -I/Users/simonmullaney/Downloads/simoncoin/src/obj -DUSE_IPV6=1 -I/Users/simonmullaney/Downloads/simoncoin/src/leveldb/include -I/Users/simonmullaney/Downloads/simoncoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:6:10: fatal error: 'boost/algorithm/string/classification.hpp' file not found
#include <boost/algorithm/string/classification.hpp>
         ^
1 error generated.
make: *** [obj/alert.o] Error 1

Did anyone ever get this resolved?

**Comment by Dbl0207** [comment]
I have the same problem,

make -f makefile.unix USE_UPNP=-
c++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/Users/simonmullaney/Downloads/simoncoin/src -I/Users/simonmullaney/Downloads/simoncoin/src/obj -DUSE_IPV6=1 -I/Users/simonmullaney/Downloads/simoncoin/src/leveldb/include -I/Users/simonmullaney/Downloads/simoncoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:6:10: fatal error: 'boost/algorithm/string/classification.hpp' file not found
#include <boost/algorithm/string/classification.hpp>
^
1 error generated.
make: *** [obj/alert.o] Error 1

Did anyone ever get this resolved?

**Comment by jestevez** [comment]
in debian execute as root

apt-get install libboost-dev
