### ISSUE TITLE
Package litecoin is failing on debian big endian archs.

### ISSUE THREAD

**Issue by juricast** [litecoin-project/litecoin#188]
Hello,

litecoin_0.8.7.5-1 is failing on debian big endian archs:
https://buildd.debian.org/status/package.php?p=litecoin&suite=sid

with following message:
<pre>
test_litecoin: main.cpp:2809: bool InitBlockIndex(): Assertion `block.hashMerkleRoot == uint256("0x97ddfbbae6be97fd6cdf3e7ca13232a3afff2353e29badfab7f73011edd4ced9")' failed.
Test setup error: signal: SIGABRT (application abort requested)
</pre>

I get following values for hash, hashGenesisBlock and hashMerkleRoot:
<pre>
32bd06294f8082fd40d4746207e0d4a98df76c598f935137f522cda0d53a049e
12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2
b7a313ba5be66daf057448001cceda5de21237fcee752ef943a0cc7e439dde9d
</pre>

I have found patch for package bitcoin here:
<pre>
https://github.com/bitcoin/bitcoin/pull/5510
</pre>

I have tried to use this patch for litecoin (with changing it so it can be used for litecoin)
and I did get following values for hash, hashGenesisBlock and hashMerkleRoot:
<pre>
cc32868b9864048a8861c8a98171d223f33b84030e7e1ffd7c97fa913b3dc17d
12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2
97ddfbbae6be97fd6cdf3e7ca13232a3afff2353e29badfab7f73011edd4ced9
</pre>

Now package is failing on following:
<pre>
assert(hash == hashGenesisBlock);
</pre>

Could someone please take a look?

Thanks!
Jurica

**Comment by juricast** [comment]
Patch used:
<pre>
--- /dev/null
+++ litecoin-0.8.7.5/src/common.h
@@ -0,0 +1,48 @@
+// Copyright (c) 2014 The Bitcoin Core developers
+// Distributed under the MIT software license, see the accompanying
+// file COPYING or http://www.opensource.org/licenses/mit-license.php.
+#ifndef BITCOIN_COMMON_H
+#define BITCOIN_COMMON_H
+#include <stdint.h>
+#include <endian.h>
+uint16_t static inline ReadLE16(const unsigned char* ptr)
+{
+	return le16toh(*((uint16_t*)ptr));
+}
+uint32_t static inline ReadLE32(const unsigned char* ptr)
+{
+	return le32toh(*((uint32_t*)ptr));
+}
+uint64_t static inline ReadLE64(const unsigned char* ptr)
+{
+	return le64toh(*((uint64_t*)ptr));
+}
+void static inline WriteLE16(unsigned char* ptr, uint16_t x)
+{
+	*((uint16_t*)ptr) = htole16(x);
+}
+void static inline WriteLE32(unsigned char* ptr, uint32_t x)
+{
+	*((uint32_t*)ptr) = htole32(x);
+}
+void static inline WriteLE64(unsigned char* ptr, uint64_t x)
+{
+	*((uint64_t*)ptr) = htole64(x);
+}
+uint32_t static inline ReadBE32(const unsigned char* ptr)
+{
+	return be32toh(*((uint32_t*)ptr));
+}
+uint64_t static inline ReadBE64(const unsigned char* ptr)
+{
+	return be64toh(*((uint64_t*)ptr));
+}
+void static inline WriteBE32(unsigned char* ptr, uint32_t x)
+{
+	*((uint32_t*)ptr) = htobe32(x);
+}
+void static inline WriteBE64(unsigned char* ptr, uint64_t x)
+{
+	*((uint64_t*)ptr) = htobe64(x);
+}
+#endif // BITCOIN_CRYPTO_COMMON_H
--- litecoin-0.8.7.5.orig/src/hash.cpp
+++ litecoin-0.8.7.5/src/hash.cpp
@@ -1,4 +1,5 @@
 #include "hash.h"
+#include "common.h"
 
 inline uint32_t ROTL32 ( uint32_t x, int8_t r )
 {
@@ -16,11 +17,13 @@ unsigned int MurmurHash3(unsigned int nH
 
     //----------
     // body
-    const uint32_t * blocks = (const uint32_t *)(&vDataToHash[0] + nblocks*4);
+    //const uint32_t * blocks = (const uint32_t *)(&vDataToHash[0] + nblocks*4);
+    const uint8_t* blocks = &vDataToHash[0] + nblocks * 4;
 
     for(int i = -nblocks; i; i++)
     {
-        uint32_t k1 = blocks[i];
+    //  uint32_t k1 = blocks[i];
+	uint32_t k1 = ReadLE32(blocks + i*4);
 
         k1 *= c1;
         k1 = ROTL32(k1,15);
--- litecoin-0.8.7.5.orig/src/main.cpp
+++ litecoin-0.8.7.5/src/main.cpp
@@ -3888,6 +3888,7 @@ bool ProcessMessages(CNode* pfrom)
         uint256 hash = Hash(vRecv.begin(), vRecv.begin() + nMessageSize);
         unsigned int nChecksum = 0;
         memcpy(&nChecksum, &hash, sizeof(nChecksum));
+	nChecksum = htole32(nChecksum);
         if (nChecksum != hdr.nChecksum)
         {
             printf("ProcessMessages(%s, %u bytes) : CHECKSUM ERROR nChecksum=%08x hdr.nChecksum=%08x\n",
--- litecoin-0.8.7.5.orig/src/netbase.h
+++ litecoin-0.8.7.5/src/netbase.h
@@ -125,7 +125,7 @@ class CService : public CNetAddr
              CService* pthis = const_cast<CService*>(this);
              READWRITE(FLATDATA(ip));
              unsigned short portN = htons(port);
-             READWRITE(portN);
+             READWRITE(FLATDATA(portN));
              if (fRead)
                  pthis->port = ntohs(portN);
             )
--- litecoin-0.8.7.5.orig/src/script.h
+++ litecoin-0.8.7.5/src/script.h
@@ -8,6 +8,7 @@
 #include <string>
 #include <vector>
 
+#include "common.h"
 #include <boost/foreach.hpp>
 #include <boost/variant.hpp>
 
@@ -374,14 +375,20 @@ public:
         else if (b.size() <= 0xffff)
         {
             insert(end(), OP_PUSHDATA2);
-            unsigned short nSize = b.size();
-            insert(end(), (unsigned char*)&nSize, (unsigned char*)&nSize + sizeof(nSize));
+            // unsigned short nSize = b.size();
+            // insert(end(), (unsigned char*)&nSize, (unsigned char*)&nSize + sizeof(nSize));
+	    uint8_t data[2];
+	    WriteLE16(data, b.size());
+            insert(end(), data, data + sizeof(data));
         }
         else
         {
             insert(end(), OP_PUSHDATA4);
-            unsigned int nSize = b.size();
-            insert(end(), (unsigned char*)&nSize, (unsigned char*)&nSize + sizeof(nSize));
+            // unsigned int nSize = b.size();
+            // insert(end(), (unsigned char*)&nSize, (unsigned char*)&nSize + sizeof(nSize));
+	    uint8_t data[4];
+	    WriteLE32(data, b.size());
+	    insert(end(), data, data + sizeof(data));
         }
         insert(end(), b.begin(), b.end());
         return *this;
@@ -454,15 +461,17 @@ public:
             {
                 if (end() - pc < 2)
                     return false;
-                nSize = 0;
-                memcpy(&nSize, &pc[0], 2);
+                // nSize = 0;
+                // memcpy(&nSize, &pc[0], 2);
+		nSize = ReadLE16(&pc[0]);
                 pc += 2;
             }
             else if (opcode == OP_PUSHDATA4)
             {
                 if (end() - pc < 4)
                     return false;
-                memcpy(&nSize, &pc[0], 4);
+                // memcpy(&nSize, &pc[0], 4);
+		nSize = ReadLE32(&pc[0]);
                 pc += 4;
             }
             if (end() - pc < 0 || (unsigned int)(end() - pc) < nSize)
--- litecoin-0.8.7.5.orig/src/serialize.h
+++ litecoin-0.8.7.5/src/serialize.h
@@ -38,6 +38,78 @@ inline T& REF(const T& val)
     return const_cast<T&>(val);
 }
 
+/*
+ * Lowest-level serialization and conversion.
+ * @note Sizes of these types are verified in the tests
+ */
+template<typename Stream> inline void ser_writedata8(Stream &s, uint8_t obj)
+{
+	s.write((char*)&obj, 1);
+}
+template<typename Stream> inline void ser_writedata16(Stream &s, uint16_t obj)
+{
+	obj = htole16(obj);
+	s.write((char*)&obj, 2);
+}
+template<typename Stream> inline void ser_writedata32(Stream &s, uint32_t obj)
+{
+	obj = htole32(obj);
+	s.write((char*)&obj, 4);
+}
+template<typename Stream> inline void ser_writedata64(Stream &s, uint64_t obj)
+{
+	obj = htole64(obj);
+	s.write((char*)&obj, 8);
+}
+template<typename Stream> inline uint8_t ser_readdata8(Stream &s)
+{
+	uint8_t obj;
+	s.read((char*)&obj, 1);
+	return obj;
+}
+template<typename Stream> inline uint16_t ser_readdata16(Stream &s)
+{
+	uint16_t obj;
+	s.read((char*)&obj, 2);
+	return le16toh(obj);
+}
+template<typename Stream> inline uint32_t ser_readdata32(Stream &s)
+{
+	uint32_t obj;
+	s.read((char*)&obj, 4);
+	return le32toh(obj);
+}
+template<typename Stream> inline uint64_t ser_readdata64(Stream &s)
+{
+	uint64_t obj;
+	s.read((char*)&obj, 8);
+	return le64toh(obj);
+}
+inline uint64_t ser_double_to_uint64(double x)
+{
+	union { double x; uint64_t y; } tmp;
+	tmp.x = x;
+	return tmp.y;
+}
+inline uint32_t ser_float_to_uint32(float x)
+{
+	union { float x; uint32_t y; } tmp;
+	tmp.x = x;
+	return tmp.y;
+}
+inline double ser_uint64_to_double(uint64_t y)
+{
+	union { double x; uint64_t y; } tmp;
+	tmp.y = y;
+	return tmp.x;
+}
+inline float ser_uint32_to_float(uint32_t y)
+{
+	union { float x; uint32_t y; } tmp;
+	tmp.y = y;
+	return tmp.x;
+}
+
 /////////////////////////////////////////////////////////////////
 //
 // Templates for serializing to anything that looks like a stream,
@@ -100,55 +172,45 @@ enum
 //
 // Basic types
 //
-#define WRITEDATA(s, obj)   s.write((char*)&(obj), sizeof(obj))
-#define READDATA(s, obj)    s.read((char*)&(obj), sizeof(obj))
-
-inline unsigned int GetSerializeSize(char a,           int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(signed char a,    int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(unsigned char a,  int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(signed short a,   int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(unsigned short a, int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(signed int a,     int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(unsigned int a,   int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(signed long a,    int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(unsigned long a,  int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(int64 a,          int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(uint64 a,         int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(float a,          int, int=0) { return sizeof(a); }
-inline unsigned int GetSerializeSize(double a,         int, int=0) { return sizeof(a); }
-
-template<typename Stream> inline void Serialize(Stream& s, char a,           int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, signed char a,    int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, unsigned char a,  int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, signed short a,   int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, unsigned short a, int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, signed int a,     int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, unsigned int a,   int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, signed long a,    int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, unsigned long a,  int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, int64 a,          int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, uint64 a,         int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, float a,          int, int=0) { WRITEDATA(s, a); }
-template<typename Stream> inline void Serialize(Stream& s, double a,         int, int=0) { WRITEDATA(s, a); }
-
-template<typename Stream> inline void Unserialize(Stream& s, char& a,           int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, signed char& a,    int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, unsigned char& a,  int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, signed short& a,   int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, unsigned short& a, int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, signed int& a,     int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, unsigned int& a,   int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, signed long& a,    int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, unsigned long& a,  int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, int64& a,          int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, uint64& a,         int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, float& a,          int, int=0) { READDATA(s, a); }
-template<typename Stream> inline void Unserialize(Stream& s, double& a,         int, int=0) { READDATA(s, a); }
+inline unsigned int GetSerializeSize(char a, int, int=0) { return 1; }
+inline unsigned int GetSerializeSize(int8_t a, int, int=0) { return 1; }
+inline unsigned int GetSerializeSize(uint8_t a, int, int=0) { return 1; }
+inline unsigned int GetSerializeSize(int16_t a, int, int=0) { return 2; }
+inline unsigned int GetSerializeSize(uint16_t a, int, int=0) { return 2; }
+inline unsigned int GetSerializeSize(int32_t a, int, int=0) { return 4; }
+inline unsigned int GetSerializeSize(uint32_t a, int, int=0) { return 4; }
+inline unsigned int GetSerializeSize(int64_t a, int, int=0) { return 8; }
+inline unsigned int GetSerializeSize(uint64_t a, int, int=0) { return 8; }
+inline unsigned int GetSerializeSize(float a, int, int=0) { return 4; }
+inline unsigned int GetSerializeSize(double a, int, int=0) { return 8; }
+
+template<typename Stream> inline void Serialize(Stream& s, char a, int, int=0) { ser_writedata8(s, a); } // TODO Get rid of bare char
+template<typename Stream> inline void Serialize(Stream& s, int8_t a, int, int=0) { ser_writedata8(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, uint8_t a, int, int=0) { ser_writedata8(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, int16_t a, int, int=0) { ser_writedata16(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, uint16_t a, int, int=0) { ser_writedata16(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, int32_t a, int, int=0) { ser_writedata32(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, uint32_t a, int, int=0) { ser_writedata32(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, int64_t a, int, int=0) { ser_writedata64(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, uint64_t a, int, int=0) { ser_writedata64(s, a); }
+template<typename Stream> inline void Serialize(Stream& s, float a, int, int=0) { ser_writedata32(s, ser_float_to_uint32(a)); }
+template<typename Stream> inline void Serialize(Stream& s, double a, int, int=0) { ser_writedata64(s, ser_double_to_uint64(a)); }
+
+template<typename Stream> inline void Unserialize(Stream& s, char& a, int, int=0) { a = ser_readdata8(s); } // TODO Get rid of bare char
+template<typename Stream> inline void Unserialize(Stream& s, int8_t& a, int, int=0) { a = ser_readdata8(s); }
+template<typename Stream> inline void Unserialize(Stream& s, uint8_t& a, int, int=0) { a = ser_readdata8(s); }
+template<typename Stream> inline void Unserialize(Stream& s, int16_t& a, int, int=0) { a = ser_readdata16(s); }
+template<typename Stream> inline void Unserialize(Stream& s, uint16_t& a, int, int=0) { a = ser_readdata16(s); }
+template<typename Stream> inline void Unserialize(Stream& s, int32_t& a, int, int=0) { a = ser_readdata32(s); }
+template<typename Stream> inline void Unserialize(Stream& s, uint32_t& a, int, int=0) { a = ser_readdata32(s); }
+template<typename Stream> inline void Unserialize(Stream& s, int64_t& a, int, int=0) { a = ser_readdata64(s); }
+template<typename Stream> inline void Unserialize(Stream& s, uint64_t& a, int, int=0) { a = ser_readdata64(s); }
+template<typename Stream> inline void Unserialize(Stream& s, float& a, int, int=0) { a = ser_uint32_to_float(ser_readdata32(s)); }
+template<typename Stream> inline void Unserialize(Stream& s, double& a, int, int=0) { a = ser_uint64_to_double(ser_readdata64(s)); }
 
 inline unsigned int GetSerializeSize(bool a, int, int=0)                          { return sizeof(char); }
-template<typename Stream> inline void Serialize(Stream& s, bool a, int, int=0)    { char f=a; WRITEDATA(s, f); }
-template<typename Stream> inline void Unserialize(Stream& s, bool& a, int, int=0) { char f; READDATA(s, f); a=f; }
-
+template<typename Stream> inline void Serialize(Stream& s, bool a, int, int=0) { char f=a; ser_writedata8(s, f); }
+template<typename Stream> inline void Unserialize(Stream& s, bool& a, int, int=0) { char f=ser_readdata8(s); a=f; }
 
 
 
@@ -174,29 +236,22 @@ void WriteCompactSize(Stream& os, uint64
 {
     if (nSize < 253)
     {
-        unsigned char chSize = nSize;
-        WRITEDATA(os, chSize);
+	ser_writedata8(os, nSize);
     }
     else if (nSize <= std::numeric_limits<unsigned short>::max())
     {
-        unsigned char chSize = 253;
-        unsigned short xSize = nSize;
-        WRITEDATA(os, chSize);
-        WRITEDATA(os, xSize);
+	ser_writedata8(os, 253);
+	ser_writedata16(os, nSize);
     }
     else if (nSize <= std::numeric_limits<unsigned int>::max())
     {
-        unsigned char chSize = 254;
-        unsigned int xSize = nSize;
-        WRITEDATA(os, chSize);
-        WRITEDATA(os, xSize);
+	ser_writedata8(os, 254);
+	ser_writedata32(os, nSize);
     }
     else
     {
-        unsigned char chSize = 255;
-        uint64 xSize = nSize;
-        WRITEDATA(os, chSize);
-        WRITEDATA(os, xSize);
+	ser_writedata8(os, 255);
+	ser_writedata64(os, nSize);
     }
     return;
 }
@@ -204,8 +259,7 @@ void WriteCompactSize(Stream& os, uint64
 template<typename Stream>
 uint64 ReadCompactSize(Stream& is)
 {
-    unsigned char chSize;
-    READDATA(is, chSize);
+    uint8_t chSize = ser_readdata8(is);
     uint64 nSizeRet = 0;
     if (chSize < 253)
     {
@@ -213,21 +267,15 @@ uint64 ReadCompactSize(Stream& is)
     }
     else if (chSize == 253)
     {
-        unsigned short xSize;
-        READDATA(is, xSize);
-        nSizeRet = xSize;
+	nSizeRet = ser_readdata16(is);
     }
     else if (chSize == 254)
     {
-        unsigned int xSize;
-        READDATA(is, xSize);
-        nSizeRet = xSize;
+	nSizeRet = ser_readdata32(is);
     }
     else
     {
-        uint64 xSize;
-        READDATA(is, xSize);
-        nSizeRet = xSize;
+	nSizeRet = ser_readdata64(is);
     }
     if (nSizeRet > (uint64)MAX_SIZE)
         throw std::ios_base::failure("ReadCompactSize() : size too large");
@@ -282,7 +330,7 @@ void WriteVarInt(Stream& os, I n)
         len++;
     }
     do {
-        WRITEDATA(os, tmp[len]);
+	ser_writedata8(os, tmp[len]);
     } while(len--);
 }
 
@@ -291,8 +339,7 @@ I ReadVarInt(Stream& is)
 {
     I n = 0;
     while(true) {
-        unsigned char chData;
-        READDATA(is, chData);
+	unsigned char chData = ser_readdata8(is);
         n = (n << 7) | (chData & 0x7F);
         if (chData & 0x80)
             n++;
--- litecoin-0.8.7.5.orig/src/test/serialize_tests.cpp
+++ litecoin-0.8.7.5/src/test/serialize_tests.cpp
@@ -4,11 +4,81 @@
 #include <vector>
 
 #include "serialize.h"
+#include "hash.h"
 
 using namespace std;
 
 BOOST_AUTO_TEST_SUITE(serialize_tests)
 
+BOOST_AUTO_TEST_CASE(sizes)
+{
+	BOOST_CHECK_EQUAL(sizeof(char), GetSerializeSize(char(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(int8_t), GetSerializeSize(int8_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(uint8_t), GetSerializeSize(uint8_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(int16_t), GetSerializeSize(int16_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(uint16_t), GetSerializeSize(uint16_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(int32_t), GetSerializeSize(int32_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(uint32_t), GetSerializeSize(uint32_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(int64_t), GetSerializeSize(int64_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(uint64_t), GetSerializeSize(uint64_t(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(float), GetSerializeSize(float(0), 0));
+	BOOST_CHECK_EQUAL(sizeof(double), GetSerializeSize(double(0), 0));
+	// Bool is serialized as char
+	BOOST_CHECK_EQUAL(sizeof(char), GetSerializeSize(bool(0), 0));
+
+	// Sanity-check GetSerializeSize and c++ type matching
+	BOOST_CHECK_EQUAL(GetSerializeSize(char(0), 0), 1);
+	BOOST_CHECK_EQUAL(GetSerializeSize(int8_t(0), 0), 1);
+	BOOST_CHECK_EQUAL(GetSerializeSize(uint8_t(0), 0), 1);
+	BOOST_CHECK_EQUAL(GetSerializeSize(int16_t(0), 0), 2);
+	BOOST_CHECK_EQUAL(GetSerializeSize(uint16_t(0), 0), 2);
+	BOOST_CHECK_EQUAL(GetSerializeSize(int32_t(0), 0), 4);
+	BOOST_CHECK_EQUAL(GetSerializeSize(uint32_t(0), 0), 4);
+	BOOST_CHECK_EQUAL(GetSerializeSize(int64_t(0), 0), 8);
+	BOOST_CHECK_EQUAL(GetSerializeSize(uint64_t(0), 0), 8);
+	BOOST_CHECK_EQUAL(GetSerializeSize(float(0), 0), 4);
+	BOOST_CHECK_EQUAL(GetSerializeSize(double(0), 0), 8);
+	BOOST_CHECK_EQUAL(GetSerializeSize(bool(0), 0), 1);
+}
+
+BOOST_AUTO_TEST_CASE(floats_conversion)
+{
+	// Choose values that map unambigiously to binary floating point to avoid
+	// rounding issues at the compiler side.
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x00000000), 0.0F);
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x3f000000), 0.5F);
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x3f800000), 1.0F);
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x40000000), 2.0F);
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x40800000), 4.0F);
+	BOOST_CHECK_EQUAL(ser_uint32_to_float(0x44444444), 785.066650390625F);
+
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(0.0F), 0x00000000);
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(0.5F), 0x3f000000);
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(1.0F), 0x3f800000);
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(2.0F), 0x40000000);
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(4.0F), 0x40800000);
+	BOOST_CHECK_EQUAL(ser_float_to_uint32(785.066650390625F), 0x44444444);
+}
+
+BOOST_AUTO_TEST_CASE(doubles_conversion)
+{
+	// Choose values that map unambigiously to binary floating point to avoid
+	// rounding issues at the compiler side.
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x0000000000000000ULL), 0.0);
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x3fe0000000000000ULL), 0.5);
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x3ff0000000000000ULL), 1.0);
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x4000000000000000ULL), 2.0);
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x4010000000000000ULL), 4.0);
+	BOOST_CHECK_EQUAL(ser_uint64_to_double(0x4088888880000000ULL), 785.066650390625);
+
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(0.0), 0x0000000000000000ULL);
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(0.5), 0x3fe0000000000000ULL);
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(1.0), 0x3ff0000000000000ULL);
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(2.0), 0x4000000000000000ULL);
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(4.0), 0x4010000000000000ULL);
+	BOOST_CHECK_EQUAL(ser_double_to_uint64(785.066650390625), 0x4088888880000000ULL);
+}
+
 BOOST_AUTO_TEST_CASE(varints)
 {
     // encode
</pre>

**Comment by wtogami** [comment]
Sorry, we will not make deep changes like this to the stable release.  I see that Bitcoin 0.11+ will have this fix, so we will adopt it later.

https://github.com/litecoin-project/litecoin/commits/master-0.10
Would you consider making a pull requests against our master-0.10 branch?  We will not merge it, however it can be a convenient way for others to patch their own for big endian builds.
