### ISSUE TITLE
LTC error on blockchain.info

### ISSUE THREAD

**Issue by geopayme** [litecoin-project/litecoin#193]
When I search my LTC address on blockchain.info I receive this error...

Anyone have any thoughts?
![blockchain-error](https://cloud.githubusercontent.com/assets/8299759/7214243/ce952a36-e5ab-11e4-99c0-c4bd1e42ea6f.jpg)

Unrecognized Address Version 48

**Comment by Rav3nPL** [comment]
Blockchain.info is site for BTC (Bitcoin) not LTC (Litecoin)....

**Comment by geopayme** [comment]
Got it... it makes sense! 

I confuse them with block.io that can handle  both coins.
