### ISSUE TITLE
litecoin-cli not operational

### ISSUE THREAD

**Issue by sigwo** [litecoin-project/litecoin#203]
` litecoin-cli getnewaddress`
`Error: There is no RPC client functionality in litecoind anymore. Use the litecoin-cli utility instead.`
I've tried with litecoind as well, same error. ?

**Comment by losh11** [comment]
Does any other command work? Recently getbalance failed to work - I guess
(as this is a test branch) some things are broken.

**Comment by wtogami** [comment]
sigwo, how did you build it and on what OS?  This is working just fine for for me on Linux and Windows.

**Comment by sigwo** [comment]
Built from source on Ubuntu 14.04

-SG

**Comment by thrasher-** [comment]
I'm using the same operating system as you but can't replicate the issue on version 0.10.2.2. What error message do you get when trying to use litecoin-cli?

**Comment by thrasher-** [comment]
Could you please type "./litecoin-cli -?" and paste the output here.

**Comment by sigwo** [comment]
On my dev Ubuntu 14.04 it works as intended. The other server (that LTC didn't work properly) I compiled LTC is a uNOMP pool for a guy on his server. I admittedly assumed his server was Ubuntu 14.04. Litecoin v0.10 did not work on his server. I checked out master-0.8 and compiled the old daemon. I finished the project and do not feel comfortable logging back into his server.

**Comment by wtogami** [comment]
Beware that Litecoin 0.8 blocks will be rejected by the network whenever our BIP66 softfork locks in, which is after 95% of miners upgrade to 0.10.

Your answer is not satisfactory as to pointing at a confirmed issue in 0.10.  Open a new ticket if you can prove there is a bug.

**Comment by losh11** [comment]
95% of miners? Isn't that an extremely large number? Pretty sure that 95%
isn't even how the latest public version is distributed.

**Comment by wtogami** [comment]
That's how the IsSuperMajority soft forks work.
