### ISSUE TITLE
Aborted (core dumped) not writing to debug.log

### ISSUE THREAD

**Issue by Jheguy2** [litecoin-project/litecoin#214]
I've been attempting to compile the code with different genesis block information. However when I run the compiled daemon nothing is outputted to debug.log. The daemon is being run as root and the .litecoin directory in my home is already created. Any advice would be greatly appreciated. Thank you.

The exact output to the console is as follows:

litecoind: chainparams.cpp:155: CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("0x12a765e31ffd4059bada1e25190f6e98c99d9714d334efa41a195a7e7e04bfe2")' failed.
Aborted (core dumped)

**Comment by thrasher-** [comment]
You'll need to edit the nTime, pszTimestamp value and nonce values and have it calculate the new genesis block. After that, get the block hash and make it the merkle root.

However, this is for Litecoin Core specific issues, not a forum on how to modify genesis block parameters. You would be better off posting in an altcoin discussion forum so I will be closing this.

**Comment by tech-alchemist** [comment]
Comment the assertion Line
