### ISSUE TITLE
Unable to compile on Arch

### ISSUE THREAD

**Issue by ThaWeatherman** [litecoin-project/litecoin#221]
See [this](https://github.com/dogecoin/dogecoin/issues/1292) issue on Dogecoin for the details.

**Comment by thrasher-** [comment]
Thanks, we are about to merge a bunch of changes which should fix this issue. I'll bump this one it's done.

**Comment by ThaWeatherman** [comment]
Awesome thanks!

**Comment by thrasher-** [comment]
The fix has been merged, thanks!
