### ISSUE TITLE
litecoin-qt: /usr/share/kde4/services/litecoin-qt.protocol refers to bitcoin-qt

### ISSUE THREAD

**Issue by Pastafarianist** [litecoin-project/litecoin#222]
(from https://bugs.gentoo.org/show_bug.cgi?id=557430)

I don't know if this is severe or not, but this is something I accidentally discovered. Both bitcoin-qt.protocol and litecoin-qt.protocol refer to bitcoin-qt inside.

```
/usr/share/kde4/services $ cat bitcoin-qt.protocol
[Protocol]
exec=bitcoin-qt '%u'
protocol=bitcoin
input=none
output=none
helper=true
listing=
reading=false
writing=false
makedir=false
deleting=false 

/usr/share/kde4/services $ cat litecoin-qt.protocol
[Protocol]
exec=bitcoin-qt '%u'
protocol=bitcoin
input=none
output=none
helper=true
listing=
reading=false
writing=false
makedir=false
deleting=false
```

**Comment by thrasher-** [comment]
Thanks for reporting this, the litecoin-qt.protocol file should contain the following:

exec=litecoin-qt '%u'
protocol=litecoin

**Comment by blueness** [comment]
ping.  i'm maintaining this package for gentoo.  is this fix going to be committed?  are  you planning a release sometime soon?

**Comment by thrasher-** [comment]
Apologies for the delay, I have a patch undergoing testing ATM: https://github.com/thrasher-/litecoin/commit/fac64e8dc325015a67c91f52de7f4f1b93f2c37f so it should be merged shortly. Our next release will be 0.12 which will be completed most likely by the end of next month.

**Comment by losh11** [comment]
@thrasher- please close.

**Comment by thrasher-** [comment]
Please refer to https://github.com/litecoin-project/litecoin/pull/236/commits/4c54b2a1072c8ee35961c09fc3c32c688e3b4d5d
