### ISSUE TITLE
charset or font problem of Chinese, OSX Version

### ISSUE THREAD

**Issue by ronnin** [litecoin-project/litecoin#223]
OSX El Captain 10.11
<img width="848" alt="2015-10-16 16 41 48" src="https://cloud.githubusercontent.com/assets/100691/10541350/ef1ab868-7442-11e5-979a-a1ee1b7c6f34.png">

**Comment by thrasher-** [comment]
Thanks for reporting this, a PR has been submitted to correct this issue and it will be pushed out for the next version release once approved.

**Comment by thrasher-** [comment]
A fix has been merged into master and we'll be releasing binaries shortly.
