### ISSUE TITLE
Wrong icon on OS X notification centre

### ISSUE THREAD

**Issue by gades** [litecoin-project/litecoin#224]
![screen shot 2015-11-04 at 21 45 09](https://cloud.githubusercontent.com/assets/4200730/10949968/3b5ce930-833e-11e5-86eb-15a105c92848.png)

**Comment by thrasher-** [comment]
Please download and install v0.10.3.0 which fixes this particular issue: https://dev.litecoin.org/

And let us know if you have any further issues.

**Comment by gades** [comment]
thank you, works for me

![screen shot 2015-11-05 at 00 37 45](https://cloud.githubusercontent.com/assets/4200730/10954345/81004af6-8355-11e5-8b2b-4f3a51bd7e97.png)
