### ISSUE TITLE
Does Litecoin support SPV?

### ISSUE THREAD

**Issue by jprichardson** [litecoin-project/litecoin#233]
(I've been searching the code base for filter commands / references to bloom filters, haven't found anything yet). But this https://www.reddit.com/r/bitcoinxt/comments/3i6uvt/peter_todd_recommends_that_litecoin_disable_spv/ leads me to believe that it does?

**Comment by thrasher-** [comment]
Litecoin Core supports SPV functionality for SPV clients. You can find the network messages for /filterload/filteradd/filterclear here:

https://github.com/litecoin-project/litecoin/blob/master-0.10/src/main.cpp#L4367

**Comment by jprichardson** [comment]
Thank you!
