### ISSUE TITLE
general compiling error

### ISSUE THREAD

**Issue by nemgun21** [litecoin-project/litecoin#243]
Hello,
Following the instructions in doc for unix, i made : 

make -f makefile.unix       # Headless litecoin

As a result i got : 

In file included from /usr/include/boost/iterator/iterator_categories.hpp:22:0,
                 from /usr/include/boost/iterator/iterator_facade.hpp:14,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/assign/list_of.hpp:20,
                 from rpcrawtransaction.cpp:6:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’:
/usr/include/boost/variant/get.hpp:284:25:   required from ‘typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’
rpcrawtransaction.cpp:242:77:   required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC_ASSERTION_FAILURE<false>’
     BOOST_STATIC_ASSERT_MSG(
     ^
makefile.unix:186: recipe for target 'obj/rpcrawtransaction.o' failed
make: *** [obj/rpcrawtransaction.o] Error 1

Thank you for your consideration.

**Comment by nemgun21** [comment]
basicaly he tells me to go rpcrawtransaction.cpp and check line 242 ==>

 const CScriptID& hash = boost::get<_const_ CScriptID_&_>(address);

just remove const and &

**Comment by wrapperband** [comment]
It's an error due to boost incompatible version : you could try this, from FTC :

#warning BOOST_VERSION      
#if ((BOOST_VERSION / 100000 == 1) && (BOOST_VERSION / 100 % 1000 == 58))
		  const CScriptID& hash = boost::get<const CScriptID>(address);
#else
		  const CScriptID& hash = boost::get<const CScriptID&>(address);
#endif
                CScript redeemScript;

**Comment by nemgun21** [comment]
what do you mean by FTC ?

**Comment by wrapperband** [comment]
http:/github.com/Feathercoin/Feathercoin

**Comment by nemgun21** [comment]
thank you

**Comment by vishal73patil** [comment]
:720: error: parse error before "DEMOD_PID_FILTER"
/home/vishal/projects/factory_k5l/K5L_ECOS/Keltic/DDI_Package/ddi_pkg_ecos/cus_mstar/project/mstar_demo/../../../../../../DDI_Misc/cus_mstar/api/frontend/apiDigiTuner.h:720: warning: function declaration isn't a prototype
ddi_target.mk:443: recipe for target 'obj/dtv.o' failed
make[1]: *** [obj/dtv.o] Error 1
make[1]: Leaving directory '/home/vishal/projects/factory_k5l/K5L_ECOS/Keltic/DDI_Package/ddi_pkg_ecos/cus_mstar/project/mstar_demo'
Makefile:145: recipe for target 'image' failed
make: *** [image] Error 2
vishal@ubuntu:~/projects/factory_k5l/K5L_ECOS/Keltic/DDI_Package/ddi_pkg_ecos/cus_mstar/project/mstar_demo$ recipe for target 'obj/dtv.o' failed
No command 'recipe' found, did you mean:
 Command 'recite' from package 'recite' (universe)
recipe: command not found
how to solve this error?
