### ISSUE TITLE
BIP 32(LIP 32) for litecoin core client?

### ISSUE THREAD

**Issue by briannyeko** [litecoin-project/litecoin#244]
When will you guys implement support for Hardware wallets like bitcoin core are going to do for their next upgrade?

**Comment by losh11** [comment]
Yes. Most of the BIPs added in Bitcoin 0.13 will make it to Litecoin 0.13.

**Comment by ysangkok** [comment]
@losh11 Do you happen to know the activation heights, or how I can find them? It would be useful for ltcd.

**Comment by losh11** [comment]
@ysangkok commented on the issue in ltcsuite/ltcd.
