### ISSUE TITLE
Propably a very stupid question.

### ISSUE THREAD

**Issue by IvRRimum** [litecoin-project/litecoin#246]
Hello,

I have a pretty dumb question. How could one integrate LiteCoin payments in Magento website ?
I have working bitcoin payment method( plugin ), is it possible to adjust it to get it working with LiteCoin ?

Thanks In advance!

**Comment by losh11** [comment]
Sure, it should be easily possible since Bitcoin and Litecoin are very similar. Do you have a repository or something, because I would be interested in helping.

By the way, you probably shouldn't ask this question on this repo. Would recommend using /r/Litecoin in the future.

**Comment by thrasher-** [comment]
Closed due to inactivity.
