### ISSUE TITLE
MinGW Runtime Assertion - Error

### ISSUE THREAD

**Issue by ShawnKimble** [litecoin-project/litecoin#248]
Occurs when trying to load on Windows 32

Program:litecoin-qt.exe  (win-32 binary)
0.10.4-d1691e5
File: allocators.h, Line 43
Expression: this->GetLockedPageCount() == 0

**Comment by thrasher-** [comment]
When you get that error message, does it mention anything about bad_alloc?

**Comment by thrasher-** [comment]
Closed due to inactivity. This error usually happens when your system is running low on memory. Please update this when you have the time.
