### ISSUE TITLE
building with QT 5.7 fails because: "Qt requires C++11 support"

### ISSUE THREAD

**Issue by marcpopp** [litecoin-project/litecoin#253]
We got a bug reported in Gentoo that building litecoin with QT 5.7 fails with the message "Qt requires C++11 support".
Full logs and used versions can be found in the original Gentoo Bug: https://bugs.gentoo.org/show_bug.cgi?id=595452

I found that explicitly adding enabling C++11 in the CXXGLAGS might solve the problem. I'll ask the reporter to try that out.

**Comment by shaolinfry** [comment]
Please can you check with the latest master branch.

**Comment by shaolinfry** [comment]
Litecoin Core 0.13.2 now depends on C++11. Closing. Please reopen if you have any further issue.
