### ISSUE TITLE
make: get stucked at `CXXLD    libbitcoinconsensus.la`

### ISSUE THREAD

**Issue by chenmiaomiao** [litecoin-project/litecoin#254]
I get stucked at `CXXLD    libbitcoinconsensus.la` in compiling. No error, just stop there, no matter how long you wait.

 I've tried many times, and the the longest test was about 1 month. I'm not exaggerating, because I was compiling on the server and forgot it. 

I followed the guide below and installed all the dependencies.
https://github.com/litecoin-project/litecoin/blob/master-0.10/doc/build-unix.md

my server is ubuntu server 14.04.

This is the output. I ended it with Ctrl + C.
`cm@ebs-29409:~/pool-unomp/litecoin$ sudo make

Making all in src

make[1]: Entering directory `/home/cm/pool-unomp/litecoin/src'

make[2]: Entering directory `/home/cm/pool-unomp/litecoin/src'

  CXX      primitives/libbitcoinconsensus_la-transaction.lo

  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo

  CXX      crypto/libbitcoinconsensus_la-scrypt.lo

  CXX      crypto/libbitcoinconsensus_la-sha1.lo

  CXX      crypto/libbitcoinconsensus_la-sha256.lo

  CXX      crypto/libbitcoinconsensus_la-sha512.lo

  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo

  CXX      libbitcoinconsensus_la-eccryptoverify.lo

  CXX      libbitcoinconsensus_la-ecwrapper.lo

  CXX      libbitcoinconsensus_la-hash.lo

  CXX      libbitcoinconsensus_la-pubkey.lo

  CXX      script/libbitcoinconsensus_la-script.lo

  CXX      script/libbitcoinconsensus_la-interpreter.lo

  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo

  CXX      libbitcoinconsensus_la-uint256.lo

  CXX      libbitcoinconsensus_la-utilstrencodings.lo

  CXXLD    libbitcoinconsensus.la

^Cmake[2]: *** [libbitcoinconsensus.la] Interrupt

make[1]: *** [all-recursive] Interrupt

make: *** [all-recursive] Interrupt

`
Any help will be appreciated.

**Comment by thrasher-** [comment]
Unexpected aborts during compilation usually happens when your machine has insufficient memory to compile or the CPU is maxed out. Try adding add a swap file and that should resolve it.
