### ISSUE TITLE
Issue compiling with freebsd version 11.0

### ISSUE THREAD

**Issue by peterfillmore** [litecoin-project/litecoin#257]
Seem to be able to run autogen.sh and ./configure successfully but am failing on the "make" step.

attached is the output from make. I've successfully compiled on Ubuntu 11.04 LTS and Debian so am perplexed as to why it chokes on the all_am.
(have followed the FreeBSD instructions and have all dependencies installed"

Thanks! Peter

```
Making all in src
make[2]: don't know how to make all-am. Stop

make[2]: stopped in /usr/home/freebsd/src/litecoin/src/obj
*** Error code 1

Stop.
make[1]: stopped in /usr/home/freebsd/src/litecoin/src
*** Error code 1

Stop.
make: stopped in /usr/home/freebsd/src/litecoin
```

**Comment by shaolinfry** [comment]
Please try again with the latest master branch

**Comment by thrasher-** [comment]
Closed due to inactivity, please comment on this when you get time to test it again.
