### ISSUE TITLE
0.13-dev: Stay up to date with Bitcoin 0.13 master!

### ISSUE THREAD

**Issue by losh11** [litecoin-project/litecoin#261]
@wangxinxi please git pull the 0.13.1 dev branch from Bitcoin master branch. We are like 600 commits behind! That branch has work from ~Bitcoin 0.13.1 rc1!

**Comment by thrasher-** [comment]
This isn't required, 0.13-dev is based off 0.13.1rc2.

**Comment by losh11** [comment]
Yeah, I realised soon after posting. Forgot to close the issue, I'm a daft person!

**Comment by thrasher-** [comment]
Haha no worries!
