### ISSUE TITLE
FTBFS with openssl 1.1.0

### ISSUE THREAD

**Issue by onlyjob** [litecoin-project/litecoin#264]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828425
Litecoin FTBFS with OpenSSL 1.1.0.

On https://wiki.openssl.org/index.php/1.1_API_Changes you can see various of the
reasons why it might fail.  There are also updated man pages at
https://www.openssl.org/docs/manmaster/ that should contain useful information.

**Comment by shaolinfry** [comment]
I believe this is sorted with 0.13.2
