### ISSUE TITLE
Getblocktemple does not work

### ISSUE THREAD

**Issue by Wayno** [litecoin-project/litecoin#29]
when try and use getblocktemplate it does not work, it needs to be fixed it guess?

./litecoind getblocktemplate
error: {"code":-1,"message":"getblocktemplate [params]\nIf [params] does not contain a \"data\" key, returns data needed to construct a block to work on:\n  \"version\" : block version\n  \"previousblockhash\" : hash of current highest block\n  \"transactions\" : contents of non-coinbase transactions that should be included in the next block\n  \"coinbaseaux\" : data that should be included in coinbase\n  \"coinbasevalue\" : maximum allowable input to coinbase transaction, including the generation award and transaction fees\n  \"target\" : hash target\n  \"mintime\" : minimum timestamp appropriate for next block\n  \"curtime\" : current timestamp\n  \"mutable\" : list of ways the block template may be changed\n  \"noncerange\" : range of valid nonces\n  \"sigoplimit\" : limit of sigops in blocks\n  \"sizelimit\" : limit of block size\n  \"bits\" : compressed target of next block\n  \"height\" : height of the next block\nIf [params] does contain a \"data\" key, tries to solve the block and returns null if it was successful (and \"rejected\" if not)\nSee https://en.bitcoin.it/wiki/BIP_0022 for full specification."}

**Comment by GatekeeperZA** [comment]
Litecoin "version": 130200,
------------------
litecoin-cli getblocktemplate
error code: -8
error message:
Support for 'segwit' rule requires explicit client support
------------------
From p2pool the error im getting.
2pool.util.jsonrpc.NarrowError: -8 Support for 'segwit' rule requires explicit client support

**Comment by anggaand123** [comment]
hi , what about {"litecoin is not connected!"}
how to fix that
