### ISSUE TITLE
main.cpp nCheckDepth

### ISSUE THREAD

**Issue by romanornr** [litecoin-project/litecoin#293]
https://github.com/litecoin-project/litecoin/blob/master/src/main.cpp#L4161

In the code it says 
nCheckDepth = 1000000000; // suffices until the year 19000

But Litecoin is 4x faster then Bitcoin.
The note should say "until the year 4750"

or should the nCheckDepth be changed into 4000000000 since nCheckDepth 1000000000 is straight from Bitcoin 0.13 and Litecoin should have 4000000000  ?

**Comment by thrasher-** [comment]
Thanks! A PR has been submitted.

**Comment by losh11** [comment]
I genuinely still cannot believe how romanornr managed to find this issue...

**Comment by romanornr** [comment]
I work on 0.13.x for btcdrak Viacoin. 
It's not that I was such a "no life" to look at the whole main.cpp without a reason. 

I saw it & wondered.. "is this sufficient for Viacoin?" 

Probably not. I was looking if you guys changed it since the Litecoin Dev team is pretty sharp & saw you guys didn't change it too. 

Well but thanks this was also a confirmation for me that it indeed should be changed.

**Comment by losh11** [comment]
Sorry, didn't mean to make it seem like I was calling you someone with 'no life'. Makes sense, and thank you for the issue. It's just something that's really easy to miss. ;)

**Comment by romanornr** [comment]
Well maybe I'm a little bit of a no life. Nothing wrong about that ;D

**Comment by thrasher-** [comment]
FYI @romanornr in 0.14 you can find the value in validation.cpp - https://github.com/thrasher-/litecoin/commit/a03b564b4617f4c2de2f0db10ccf21e4d9006ffc
