### ISSUE TITLE
fundrawtransaction() address reuse bug

### ISSUE THREAD

**Issue by gituser** [litecoin-project/litecoin#301]
Hello.

Is this https://github.com/bitcoin/bitcoin/pull/9377 ported to litecoin? I can't seem to find this in the litecoin's commit log.

**Comment by shaolinfry** [comment]
This will be included in Litecoin Core 0.14.1. You can see the 0.14-dev branch for more details.

**Comment by gituser** [comment]
Is there any ETA on the 0.14.1 release?

Cheers.

**Comment by shaolinfry** [comment]
Two weeks™

**Comment by thrasher-** [comment]
http://dev.litecoin.org/ 0.14.2rc2 is now released and has this bug fixed. We'll be releasing 0.14.2 soon ™ (likely within the next week).
