### ISSUE TITLE
My testnet4 blocks height remain 42556, and then the network is unreachable.

### ISSUE THREAD

**Issue by LzyDou** [litecoin-project/litecoin#305]
my litecoind is build from the latest master. and the error message from debug.log is:

"connect() to [2605:6000:151d:809a:2acf:e9ff:fe21:8841]:19335 failed: Network is unreachable (101)"

**Comment by damui** [comment]
am I

**Comment by thrasher-** [comment]
Miner went down, all fixed now. Try adding node 104.236.211.206:19335.

**Comment by damui** [comment]
@thrasher-  thanks, it's ok.

**Comment by LzyDou** [comment]
@thrasher- thanks
