### ISSUE TITLE
what's up with litecoin's testnet?

### ISSUE THREAD

**Issue by gituser** [litecoin-project/litecoin#306]
Hi

It seems from the logs there are no peers or something wrong with my client?

I'm using `v0.13.2.1` and it seems client can't connect to anyone stating 'connection refused` or `network is unreachable`. 

Of course my network setup is completely fine.

Transactions are not getting out as well.

Was testnet reset recently or something?

Also is there any good faucet to get litecoin testnet coins?

Thank you.

**Comment by thrasher-** [comment]
Hey @gituser,

Litecoin testnet version 3 has been depreciated and disbanded. If you compile the latest master or 0.14-dev branch you'll be able to connect fine. 

I'm just in the process of setting up a new faucet since our last one got DDoS'd. I'll paste the link here shortly.

**Comment by gituser** [comment]
I see there is a new `testnet4` in the litecoin's datadir directory.

Thanks @thrasher- waiting for the link..

**Comment by gituser** [comment]
can anybody tell me how can I mine some coins on the testnet?

I've tried with `0.14.0-dev branch`:
 https://github.com/pooler/cpuminer (for CPU, like this `/minerd -D -a scrypt -o 127.0.0.1:8888 -O user:pass --coinbase-addr myltctestnet_addr`) doesn't work (gives me 500 error).

`cgminer 3.72` compiled with scrypt support on the gpu, doesn't work either.

If I query via curl same url with credentials, e.g. `getbalance` it displays just fine.

What could be wrong? And is there any mining software for recent litecoin which 100% works?

Thank you.

**Comment by thrasher-** [comment]
You can use this faucet to obtain testnet coins: http://testnet.thrasher.io/ (Limit of 10 coins per IP)

If you require any more, please let me know.

**Comment by gituser** [comment]
@thrasher- i'm getting 502 over there..

also starting more recent litecoin version nothing is happening there.. 
basically all i get is this:

```
2017-04-26 21:34:21 init message: Loading addresses...
2017-04-26 21:34:21 torcontrol thread start
2017-04-26 21:34:21 Loaded 0 addresses from peers.dat  1ms
2017-04-26 21:34:21 init message: Loading banlist...
2017-04-26 21:34:21 init message: Starting network threads...
2017-04-26 21:34:21 dnsseed thread start
2017-04-26 21:34:21 Loading addresses from DNS seeds (could take a while)
2017-04-26 21:34:21 net thread start
2017-04-26 21:34:21 addcon thread start
2017-04-26 21:34:21 init message: Done loading
2017-04-26 21:34:21 msghand thread start
2017-04-26 21:34:21 opencon thread start
2017-04-26 21:34:26 0 addresses found from DNS seeds
2017-04-26 21:34:26 dnsseed thread exit
```

Do I need to get proper peers.dat or something to get new testnet4 working?

Thank you.

**Comment by thrasher-** [comment]
Sorry, the site went down but it's back up now. Litecoin Core has had its mining functionality removed so you'll need to setup a pool (I use Eloipool - https://github.com/thrasher-/eloipool) and CGMiner (with scrypt support)

**Comment by gituser** [comment]
thanks, @thrasher- your website works and sends quickly.

i'll try eloipool bit later, cgminer I presume you're using `3.7.2` ?

**Comment by thrasher-** [comment]
You're welcome, and that's correct I'm using CGMiner 3.7.2.

**Comment by pooler** [comment]
I just pushed an update that adds basic Segwit support to cpuminer. It should work fine on testnet4 now, I was able to mine a dozen blocks on my laptop.
