### ISSUE TITLE
What are address version values for P2WPKH and P2WSH (BIP-142) for Litecoin?

### ISSUE THREAD

**Issue by prusnak** [litecoin-project/litecoin#312]
Or does Litecoin only support (non-native) Segwit-in-P2SH?

**Comment by shaolinfry** [comment]
We are not using BIP142, we're using BIP173 with ltc1 and tltc1 prefixes

For normal P2SH addresses, we use M prefix now.

**Comment by prusnak** [comment]
Can you point me to your implementation of BIP173 in the source code?

**Comment by azuchi** [comment]
I understand if ltc, why 1 is included?

**Comment by prusnak** [comment]
> I understand if ltc, why 1 is included?
read [https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki|bip-173]. It is a delimiter of human-readable string and encoded data.

**Comment by azuchi** [comment]
oh, I see. well then human-redable part is ltc.

**Comment by shaolinfry** [comment]
@prusnak We obviously haven't implemented BIP173 in Litecoin Core yet, but it's being implemented already in some LN clients - we with LN devs that Litecoin would use bech32 with ltc1 as the prefix. M and Q addresses for P2SH have been implemented in 0.13.3rc1 and 0.14-dev.

**Comment by prusnak** [comment]
What are M and Q addresses?
