### ISSUE TITLE
 Warning: Unknown block versions being mined! It's possible unknown rules are in effect

### ISSUE THREAD

**Issue by AdvancedStyle** [litecoin-project/litecoin#315]
Running the latest release version (13.2.1) and keep getting this error message in the "error" field of getinfo.

"Warning: Unknown block versions being mined! It's possible unknown rules are in effect"

**Comment by juscamarena** [comment]
That's fine. Miners are supposed to automatically unset bip9 bits after activation, but it seems some set it manually and left them on after segwit activation. There's no harm done here, everything is fine.
