### ISSUE TITLE
Dear Author How do I open the P2P connection?  Thank you

### ISSUE THREAD

**Issue by wuhuaping** [litecoin-project/litecoin#317]
litecoin] (Thread 1) getblocktemplate call failed for daemon instance 0 with error {"code":-8,"message":"Support for 'segwit' rule requires explicit client support"}
2017-05-17 22:23:57 [Pool]	[litecoin] (Thread 1) Error with getblocktemplate on creating first job, server cannot start

root@iZ2zegquegjgaxid7pimbwZ:~# litecoin-cli getblocktemplate
error code: -8
error message:
Support for 'segwit' rule requires explicit client support

**Comment by losh11** [comment]
I sent you a message about this on [LitecoinTalk.org](http://litecointalk.org/t/litrcoin-qt-gettempleteblock-error-8/2403).

**Comment by wuhuaping** [comment]
Thank you
I've found so many problems that the purse itself is incomplete
Or intentionally turning off the P2P connection
I don't know what the purpose of this is
Can you tell me how to start the connection?

**Comment by wuhuaping** [comment]
I hope the author can help me. Thank you

root@iZ2zegquegjgaxid7pimbwZ:~# litecoin-cli getblocktemplate
error code: -8
error message:
Support for 'segwit' rule requires explicit client support

**Comment by thrasher-** [comment]
This would occur if the mining software (CoiniumServ) does not support the 'segwit' rule. You'll need to contact their dev team and ask them to add support for it. There's other pool software out there which supports segwit like NOMP/Eloipool/CKPool.
