### ISSUE TITLE
how to contribute to the projects in Litecoin 2017 road map

### ISSUE THREAD

**Issue by jw2013** [litecoin-project/litecoin#319]
Hi,
I am pretty interested in contributing to the Lightning Network project listed on the Litecoin 2017 roadmap (https://litecoincore.org/). Could I ask how could I contribute to it? Is there anyone I could talk to?

Really appreciate any response!

:)

**Comment by FaysalM** [comment]
Join us on IRC freenode #litecoin-dev

Clone the code and have at it! :)

**Comment by jw2013** [comment]
@FaysalM thanks for the reply! Could I ask if there is anything I can look up if I want to contribute something on lightning network in particular? Wondering if there is a list of todos I can grab on?

cc'ing: @coblee, @ultragtx, @wangxinxi as I see you guys are listed on that project in the list. Would love to do what I can to help. :)

**Comment by thrasher-** [comment]
As the Litecoin Core project is open source, the sky is the limit when it comes to things you could contribute to. Submitting new ideas, helping existing teams with their implementations or testing new releases (https://www.reddit.com/r/litecoin/comments/6isa54/loafwallet_android_for_ltc_offical/), writing code or docuemtnation all helps out depending on what you're happy to do. #litecoin-dev on Freenode is a great place to hang it in, in which you can contact the majority of devs.

See https://github.com/litecoin-project/litecoin/blob/master/CONTRIBUTING.md for the contribution philosophy behind the Litecoin Project.
