### ISSUE TITLE
osx make deploy error

### ISSUE THREAD

**Issue by out0fmemory** [litecoin-project/litecoin#320]
i meet error when "make deploy" on mac 2015 early,the error msg is below

$ make deploy
make -C src qt/litecoin-qt
make[1]: Entering directory '/Volumes/sd_card/git_project/litecoin/src'
OBJCXXLD qt/litecoin-qt
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:3407: qt/litecoin-qt] Error 1
make[1]: Leaving directory '/Volumes/sd_card/git_project/litecoin/src'
make: *** [Makefile:1185: src/qt/litecoin-qt] Error 2

**Comment by out0fmemory** [comment]
resolved in my pull,[https://github.com/litecoin-project/litecoin/issues/320](url)

**Comment by rromanchuk** [comment]
Looks like there are two PRs for this now, would love this to get pulled in @shaolinfry  👍

**Comment by losh11** [comment]
Tests are failing. Won’t be merged until Travis is happy.

**Comment by rromanchuk** [comment]
@losh11 i'll dig in, and see if i can fix the build

**Comment by dwasyluk** [comment]
The referenced bitcoin patch seems to be related to the background TIFFs which is different than the issue the author posted.

**Comment by dwasyluk** [comment]
Getting a very similar issue here in the Syscoin project on OSX 10.12.5:

$ make deploy
build-aux/install-sh -c -d Syscoin-Qt.app/Contents
build-aux/install-sh -c -d Syscoin-Qt.app/Contents/Resources
build-aux/install-sh -c -d Syscoin-Qt.app/Contents/Resources
/usr/bin/install -c -m 644 src/qt/res/icons/syscoin.icns Syscoin-Qt.app/Contents/Resources/syscoin.icns
build-aux/install-sh -c -d Syscoin-Qt.app/Contents
/usr/bin/install -c -m 644 share/qt/Info.plist Syscoin-Qt.app/Contents/Info.plist
/Library/Developer/CommandLineTools/usr/bin/make -C src qt/syscoin-qt
  OBJCXXLD qt/syscoin-qt
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/syscoin-qt] Error 1
make: *** [src/qt/syscoin-qt] Error 2

**Comment by thrasher-** [comment]
Resolved with @out0fmemory's PR #321.
