### ISSUE TITLE
Litecoin-cli getblockhashes not available

### ISSUE THREAD

**Issue by anhgien** [litecoin-project/litecoin#322]
Hi guys,
I'm tesing litecoin-cli commands (litecoin 0.13.2) with method `getblockhashes` (method returns an array of block hashes for a specified block range, ex: two timestamps) but it return `Method not found`, is it removed?
If it was removed, so is there a method that has the same feature with above method?

**Comment by gabrieldov** [comment]
Hi, I think you can find more info about this here:
https://github.com/bitpay/bitcore-node/issues/490

**Comment by thrasher-** [comment]
Litecoin Core has method 'getblockhash' but not one which allows you to call getblockhashes. As @gabrieldov pointed out, Bitpay has their own project bitcore which is probably what you're after.
