### ISSUE TITLE
possible double spends of coinbase transactions

### ISSUE THREAD

**Issue by HashUnlimited** [litecoin-project/litecoin#327]
Discovered due to the specifications of an altcoin, this issue is concerning Litecoin and ultimately Bitcoin as well, there for here the report on information collected so far:

Test setup: 
- create a chain with at least one mature block
- on the created blocks, resize the coinbase tx to any number greater than 1 
- fill the coinbase transactions up to the consensus accepted nSubsidy
- create a mutable transaction, go back the coinbase size -1 (leave the first vector untouched) and add (replay) all following vectors there

Result:
Transaction accepted

Those transactions are being accepted by the network (which I think is a serious issue). Literally that means one can spend the reward except the minimum in the first vector, which is 1*COIN, twice.

**Comment by gabrieldov** [comment]
I don't get it. Do you have any transaction like this on testnet to share? Or this was done on a private blockchain with one mature block? I mean, could you reproduce this bug on testnet?

**Comment by HashUnlimited** [comment]
I have reproduced it on our (altcoin) testnet, since it's plain LTC code with different prefix I assume the same result. Please allow me a little time, I'm happy to set up a stratum server on Litecoin testnet to show the block result. Just a little busy right now, a lot of alts are experiencing 51% attacks at the moment of writing...

**Comment by gabrieldov** [comment]
Ok, so probably not possible to reproduce on live testnet. This can happen to any coin if you don't have active mining power and nodes in place to verify transactions - also if there are no other transactions on the chain (if your chain only has predictable transactions).

**Comment by HashUnlimited** [comment]
my test net contains 5 active nodes 2 stratum servers, 600 GH/s hash power... Will move that thing to Litecoin testnet and see... just to understand what made me worry and file the issue

**Comment by gabrieldov** [comment]
What's the status of this? Please close if no more findings.

**Comment by HashUnlimited** [comment]
Closed for now, will write some test case and report the details if available. For now I wasn't able to reproduce on LTC testnet.
