### ISSUE TITLE
Couldn't connect to server

### ISSUE THREAD

**Issue by imnuruddin** [litecoin-project/litecoin#328]
I just installed litecoin, and I am getting following.
`./litecoin-cli getinfo
error: couldn't connect to server`
Please Help, thanks in advance

**Comment by losh11** [comment]
You have to start the Litecoin server first. Run `./litecoind &` first.
Please make sure you are using testnet4 on Core 0.13.3 which you have to
build yourself.

**Comment by niminokh** [comment]
Server is running and cli giving this output

11 июня 2017 г. 19:24 пользователь "Loshan T" <notifications@github.com>
написал:

> You have to start the Litecoin server first. Run `./litecoind &` first.
> Please make sure you are using testnet4 on Core 0.13.3 which you have to
> build yourself.
>

**Comment by losh11** [comment]
Can you make sure the correct rpc port is open?

**Comment by niminokh** [comment]
How do I do that @losh11

**Comment by thrasher-** [comment]
What operating system are you on? Are you using mainnet or testnet? Ports for RPC on mainnet are 9332 and 19332 for testnet. If on Linux you can type netstat -anp | grep PORT and see if it's listening. Then if you can confirm that it's listening, try ./litecoin-cli -rcpport=PORT getinfo and see if that works.

**Comment by thrasher-** [comment]
Closed due to inactivity, but feel free to follow this up if needed.

**Comment by PEVN** [comment]
Hi so I also ran into this type of problem...
After entering "./litecoind &" .... I get an output that says "[1] 16410...litecoin server starting"
It then freezes in a blank line
After pressing enter it writes "[1]+ Done           ./litecoind"
And ofcourse trying "litecoin-cli getinfo -rpcconnect=xx.xxx.xx.xx -rpcport=xxxx" it returns an unkown error and that the server might not be running.

Please :( what's going on. I feel like an idiot by now
Thanks in advance

**Comment by blockchaintrainer** [comment]
Hi,

I am getting below error in build.log while mining my own coin:
2018-04-21 13:11:13 connection timeout
2018-04-21 13:11:18 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:11:23 connection timeout
2018-04-21 13:11:29 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:11:34 connection timeout
2018-04-21 13:11:39 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:11:44 connection timeout
2018-04-21 13:11:50 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:11:55 connection timeout
2018-04-21 13:12:00 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:12:05 connection timeout
2018-04-21 13:12:11 trying connection 128.199.56.171 lastseen=0.0hrs
2018-04-21 13:12:16 connection timeout

Do you have a fix for this?
