### ISSUE TITLE
Update nodes_main.txt with .onion addresses

### ISSUE THREAD

**Issue by mrosseel** [litecoin-project/litecoin#329]
In the bitcoin source code, the file: `./contrib/seeds/nodes_main.txt` contains .onion addresses (at the end of the file).

For Litecoin this file does not contain .onion addresses, does this mean there are no known Litecoin full nodes on Tor?

If there are none you can close this issue, otherwise please add a list of them to this issue.

**Comment by thrasher-** [comment]
There currently exists no .onion nodes for Litecoin's testnet or mainnet. It would be nice to have some though. Will look into adding a testnet and mainnet full node soon.

**Comment by mrosseel** [comment]
thx @thrasher- , please let me know the onion address if you create one.

**Comment by mhouriet** [comment]
Litecoin node `mqgmba4o453jwdjd.onion` is available and stable on mainnet for everyone :)

**Comment by n0n0n0n0** [comment]
any nodes?

**Comment by LasersAreGreat** [comment]
I've setup a litecoin node that is accessible on TOR at qmt2knih2w2whmxq.onion:9333

To add it, you can run the following:

addnode qmt2knih2w2whmxq.onion:9333 add

**Comment by MoTLD** [comment]
I occasionally run a full Litecoin node at cilpmzytinzlg5m2.onion.
