### ISSUE TITLE
Can i compile litecoin in QT Creator?

### ISSUE THREAD

**Issue by l1feste4ler** [litecoin-project/litecoin#330]
Iam novice in Qt and Linux 
so i have many trouble with it. And is very hard for me. Pls help. 
When i open bitcoin-qt.pro in QT creator i cant build him.
In issues:

- target 'all' doesn't match the target pattern

**Comment by thrasher-** [comment]
Nope, Litecoin Core has to be compiled using automake via ./autogen.sh and then ./configure.

You can find build instructions for Linux here:
https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md
