### ISSUE TITLE
Segmentation fault after compilation of latest litecoind

### ISSUE THREAD

**Issue by PavelNiedoba** [litecoin-project/litecoin#334]
I have compiled latest litecoin from sources according howto. I only used different berkelydb version than recommended.  I use ubuntu 14.04LTS. The compilation went fine, I did make install with success, but when i try to run litecoind, I get only segmentation fault. 
  Is it likely because of berkeley db ? 
Is there compiled version which runs against test network available for download ?

**Comment by thrasher-** [comment]
A different berkleydb version causes compatibility issues between older wallets but shouldn't cause a segmentation fault. Did you use this guide here? 

https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md

Could you please upload the contents of your ~/.litecoin/debug.log file?

**Comment by thrasher-** [comment]
Closed due to inactivity, however please report back if required.

**Comment by dimitrkovalsky** [comment]
I have same issue. But ~/.litecoin/ folder is empty. Why can it happen?

**Comment by dimono777** [comment]
I have same issue. 

litecoin.conf
![image](https://user-images.githubusercontent.com/2892688/120899540-e5c08600-c638-11eb-8d50-cf1eb39dbab9.png)

When I run litecoind
![image](https://user-images.githubusercontent.com/2892688/120899567-fec93700-c638-11eb-9936-5d341a2961a3.png)

**Comment by dimono777** [comment]
debug.log
![image](https://user-images.githubusercontent.com/2892688/120899607-46e85980-c639-11eb-9ded-1e33476db280.png)

**Comment by skoniks** [comment]
The same problem
