### ISSUE TITLE
Makfile.am 

### ISSUE THREAD

**Issue by PEVN** [litecoin-project/litecoin#335]
What happened to makefile.unix
Ubuntu will not run Makefile.am or Makefile.in and when forced it reports errors within these files

**Comment by thrasher-** [comment]
Litecoin Core uses automake now so there is no longer a makefile.unix file. Please follow this guide: https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md

**Comment by PEVN** [comment]
Thanks so much for your response. I have another question now that I’ve done some homework which I apologise if it’s wrong to ask you or if I am wasting you’re time.
When I build the litecoin dameon I run ./autogen.sh and ./configure but when trying to run “make -f Makefile.am” it returns an error about a missing character line 7. How do I fix this?
Kind regards


Sent from Mail for Windows 10

**Comment by thrasher-** [comment]
No problem, after running ./configure, the next step is to write 'make'. That will compile the software accordingly.

**Comment by PEVN** [comment]
Thank you so much for your help. I’ll run it later and see. I really appreciate your time.
Kind Regards

Sent from Mail for Windows 10

**Comment by PEVN** [comment]
Please could someone help me
I am trying to compile litecoin into a dameon as I am developing a pool however make will not build litecoin at all no matter what I try and even if I force it it says that there are missing seperators within the make file. What am I doing wrong??? Is there an alternative way to do this? Alternatively is it possible to run my pool without a dameon and just have the core running somehow linking the pool terminal and core terminal to interact?
Any help whatsoever would be appreciated.
Kind Regards


Sent from Mail for Windows 10

**Comment by losh11** [comment]
What exactly is the output in terminal?
https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md works almost universally. What OS are you running?

**Comment by PEVN** [comment]
Hi there so it seems I might have missed a dependency or something but I finally got it to work 😊 Thank you so much for your help
Last question
Once I get the daemon running how do I know that it is up to date?


Sent from Mail for Windows 10

**Comment by PEVN** [comment]
Hi there I run ./litecoind and it says Server starting 
Firstly how can I get stats on the daemon?
And secondly how do I know when it has finished downloading the blockchain?


Sent from Mail for Windows 10

**Comment by rromanchuk** [comment]
`tail -f ~/.litecoin/debug.log` 

or run `./src/litecoind --help`  to see what other flags you can pass from command line or create a conf file at `~/.litecoin/litecoin.conf`

**Comment by thrasher-** [comment]
`./src/litecoin-cli getinfo` check to see if 'Litecoin is downloading blocks...' is shown. If not and there's no other errors, then you're synced. Currently at block height: 1234584

**Comment by shaolinfry** [comment]
This tracker isnt really for user support. Can I recommend the #litecoin IRC channel or the r/litecoin subreddit?

**Comment by charlesrocket** [comment]
is there a PR with transition to makefile.am? can't find it anywhere
