### ISSUE TITLE
Decrease Litecoin Fees

### ISSUE THREAD

**Issue by FaysalM** [litecoin-project/litecoin#336]
Not really an issue but a request to change the minimum LTC fee. Since the price has been going up, the dust is now not really dust. Maybe decrease this to 0.00001 -- if I am not wrong it used to be this but was changed to 0.001 in the following commit

https://github.com/litecoin-project/litecoin/commit/3cb9f7aa4b5cd5056d0969b83ab2602ad2f6635c#diff-12635a58447c65585f51d32b7e04075b

**Comment by gabrieldov** [comment]
Yes, this update needs to follow the adoption to avoid alienating new users,

**Comment by shaolinfry** [comment]
The fee system will be updated to floating in 0.14 you can see the code in the master branch already.
