### ISSUE TITLE
rename manpages to litecoind.1 etc

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#339]
Being a fork of bitcoin, litecoin has renamed pieces of the source as litecoin,
but the manpages in doc/man are still named bitcoin-cli.1 bitcoin-qt.1 bitcoin-tx.1 bitcoind.1
These should be renamed too, like the binaries.

**Comment by thrasher-** [comment]
Fixed in https://github.com/litecoin-project/litecoin/pull/358
