### ISSUE TITLE
testnet.litecointools.com is bugging

### ISSUE THREAD

**Issue by lepipele** [litecoin-project/litecoin#341]
I am trying to reach whoever is in charge of that "official" testnet for Litecoin to see if I can help with fixing few problems.

Specifically the biggest issue for me is that it seems http://explorer.litecointools.com subdomain is down... so when you click on transaction link it doesn't work, for example:

http://explorer.litecointools.com/block/048a5cddd91b02f6610af50d6d67a90f423fdc60ca1d1d2794697eee4597349b

I've posted on forum (https://litecointalk.io/), Litecoin subreddit /r/litecoin - but no-one can help because this is "technical issue". Please let me know if you can help!

**Comment by thrasher-** [comment]
Thanks for letting us know. We'll get this fixed up ASAP.

**Comment by lepipele** [comment]
Thanks @thrasher- ... I love using http://testnet.litecointools.com/ and it would be great if Explorer is back online!

**Comment by losh11** [comment]
@lepipele you might be interested to see Insight Lite Testnet at: https://testnet.litecore.io.
We'll be switching the litecointools faucet to use Insight Lite as the default explorer soon.

**Comment by lepipele** [comment]
Yeah, that explorer looks pretty good - it would be great if it was linked in official Wiki page, here: https://litecoin.info/Category:Services#Block_Explorers

Seems they also have GitHub page: https://github.com/bitpay/insight-ui

So, thanks for help and I hope this thread will help others who are in similar situation (searching for LTCT blockchain explorer).

**Comment by losh11** [comment]
Thanks for closing. We'll be updating our blogs and other forms of info with the most up to date info.
