### ISSUE TITLE
--disable-lcov requires lcov

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#343]
This is current git master on OpenBSD 6.1-current/amd64.
Configuring with  --disable-lcov complains that lcov is not found,
which seems obviously wrong.

1.  env AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 sh autogen.sh 
2 ./configure --prefix=$HOME --mandir=$HOME/man --disable-lcov --disable-wallet --without-gui  CC=egcc CXX=eg++

[...]
configure: error: "lcov testing requested but lcov not found"

**Comment by iamkubi** [comment]
Looks like this was fixed upstream by https://github.com/bitcoin/bitcoin/commit/0e707919f596c80056bca295abd71543ccae4956, which is tagged for 0.16.0.

This should get fixed in Litecoin 0.16.

**Comment by thrasher-** [comment]
Fixed in v0.16: https://github.com/litecoin-project/litecoin/commit/223a4aabd3681817f3ced5b2441a6b44fcf29c4e
