### ISSUE TITLE
./configure fails with GCC 6

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#345]
Trying to build the current git master on OpenBSD 6.1-current/amd64.
I have it working, including the GUI, with GCC 4.9.4 from OpenBSD ports.
(A revised OpenBSD build manual is in the works).
However, with GCC 6 (also in ports), litecoin fails to configure, reporting

> checking whether the Boost::Chrono library is available... yes                                 
> checking for exit in -lboost_chrono-mt... yes  
> checking for mismatched boost c++11 scoped enums... ok                                         
> configure: error: No working boost sleep implementation found.        

1.  env AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 sh autogen.sh 
2. ./configure --prefix=$HOME --mandir=$HOME/man --disable-tests --disable-glibc-back-compat --disable-zmq --disable-wallet --with-gui=qt4  --with-utils  --with-daemon --without-libs  CC=egcc CXX=eg++ PKG_CONFIG_PATH=/usr/local/lib/qt4/pkgconfig/

This sequence works with GCC 4.9.4 but fails with GCC6.
What is the realation of the compiler to the boost sleep implementation?

**Comment by knoxcard** [comment]
I've had the same issues with Bitcoin.  My recommendation is to use your Operating System's system libraries.  Compilers, Boost, Python, Libs, etc..  You can use the latest version of MySQL, NGINX, NodeJS, Redis, etc.  Just don't mess with the core stuff, that is of course if the attempt to upgrade fails.

**Comment by knoxcard** [comment]
So in your case I would try this...

sudo apt-get uninstall libboost-all-dev
sudo apt-get install libboost-all-dev

That should do it!

**Comment by thrasher-** [comment]
Closed due to inactivity.
