### ISSUE TITLE
./configure looks for javac

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#346]
This is current git master on OpenBSD 6.1-current.
Reading the output of ./configure carefully, I see this:

```
checking for javac... no^M
configure: WARNING: cannot find JDK; try setting $JAVAC or $JAVA_HOME^M
checking jni headers... none^M
configure: WARNING: jni headers/dependencies not found. jni support disabled^M
```

Is Litecoin using Java at all? Why is it there?
Naively grepping for JDK, i's ./src/secp256k1/configure that does it.

1.  env AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 sh autogen.sh
2. ./configure --prefix=$HOME --mandir=$HOME/man --disable-tests --disable-glibc-back-compat --disable-zmq --disable-wallet --with-gui=no  --with-utils  --with-daemon --without-libs  CC=egcc CXX=eg++

**Comment by shaolinfry** [comment]
There is no use of Java, this was for the test framework once uponatime.

**Comment by janstary** [comment]
OK, should it be removed then?

**Comment by thrasher-** [comment]
Fixed in: https://github.com/litecoin-project/litecoin/commit/cbdd338a75d53061b97daeb8e6f04d22249117cc#diff-67e997bcfdac55191033d57a16d1408a
