### ISSUE TITLE
QT4 GUI: Bad Drawable

### ISSUE THREAD

**Issue by janstary** [litecoin-project/litecoin#348]
This is current git master running on OpenBSD 6.1-current.
After a seemingly random period of time, the GUI becomes
just a set of grey rectangles with nothing in them,
and the debug.log says:

```
2017-07-11 13:39:58 GUI: QNativeImage: Unable to attach to shared memory segment.   
2017-07-11 13:39:59 GUI: X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
```

There is nothing to do but sigkill the litecoin-qt.

Here is how to reproduce: start up litecoin-qt on OpenBSD
and let it rot for  few minutes. Switch windows with alt-tab, whatever.
Eventually you wil get an unresponsive empty rectangle.

OS: OpenBSD 6.1-current/amd64 with qt4-4.8.7p11

**Comment by thrasher-** [comment]
Could you please try the latest master to see if the issue is fixed now?

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to persue this if you wish to.
