### ISSUE TITLE
mining with cpuminer (testing)

### ISSUE THREAD

**Issue by noeldum** [litecoin-project/litecoin#355]
Just for testing purpose I am trying to run a quick miner on my litecoin core. The miner does seem to fail but it does appear this is due to something wrong with the litecoin side as I tested the miner on a pool which was successful.

I got the miner from pooler/cpuminer. Running command is 

> ./minerd -o stratum+tcp://127.0.0.1:9332 -u user -p x

(on ubuntu 14)

This outputs as 

> [2017-07-17 17:32:30] Starting Stratum on stratum+tcp://127.0.0.1:9332
> [2017-07-17 17:32:30] Binding thread 0 to cpu 0
> [2017-07-17 17:32:30] 4 miner threads started, using 'scrypt' algorithm.
> [2017-07-17 17:32:30] Binding thread 1 to cpu 1
> [2017-07-17 17:32:30] Binding thread 2 to cpu 2
> [2017-07-17 17:32:30] Binding thread 3 to cpu 3
> [2017-07-17 17:32:30] JSON decode failed(1): '[' or '{' expected near 'HTTP'
> [2017-07-17 17:32:30] stratum_subscribe send failed
> [2017-07-17 17:32:30] ...retry after 30 seconds

My litecoin.conf file is:

> rpcuser=user
> rpcpassword=x
> rpcallowip=192.168.1.0/24
> rpcport=9332
> daemon=0
> server=1

The debug shows:

> 2017-07-17 16:24:02 Litecoin version v0.13.2.1
> 2017-07-17 16:24:02 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
> 2017-07-17 16:24:02 Default data directory /home/nono/.litecoin
> 2017-07-17 16:24:02 Using data directory /home/nono/.litecoin
> 2017-07-17 16:24:02 Using config file /home/nono/.litecoin/litecoin.conf
> 2017-07-17 16:24:02 Using at most 125 connections (1024 file descriptors available)
> 2017-07-17 16:24:02 Using 4 threads for script verification
> 2017-07-17 16:24:02 scheduler thread start
> 2017-07-17 16:24:02 Binding RPC on address 0.0.0.0 port 9332 failed.
> 2017-07-17 16:24:02 HTTP: creating work queue of depth 16
> 2017-07-17 16:24:02 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
> 2017-07-17 16:24:02 HTTP: starting 4 worker threads
> 2017-07-17 16:24:02 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> 2017-07-17 16:24:02 Using wallet wallet.dat
> 2017-07-17 16:24:02 init message: Verifying wallet...
> 2017-07-17 16:24:02 CDBEnv::Open: LogDir=/home/nono/.litecoin/database ErrorFile=/home/nono/.litecoin/db.log
> 2017-07-17 16:24:02 Bound to [::]:9333
> 2017-07-17 16:24:02 Bound to 0.0.0.0:9333
> 2017-07-17 16:24:02 Cache configuration:
> 2017-07-17 16:24:02 * Using 2.0MiB for block index database
> 2017-07-17 16:24:02 * Using 8.0MiB for chain state database
> 2017-07-17 16:24:02 * Using 290.0MiB for in-memory UTXO set
> 2017-07-17 16:24:02 init message: Loading block index...
> 2017-07-17 16:24:02 Opening LevelDB in /home/nono/.litecoin/blocks/index
> 2017-07-17 16:24:02 Opened LevelDB successfully

The message "Binding RPC on address 0.0.0.0 port 9332 failed" seems funny but the telnet does work on that port.

> telnet 127.0.0.1 9332
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.

Trying with http instead of stratum does not either:

> ./minerd -o http://127.0.0.1:9332 -u user -p x
> [2017-07-17 17:39:21] Binding thread 0 to cpu 0
> [2017-07-17 17:39:21] 4 miner threads started, using 'scrypt' algorithm.
> [2017-07-17 17:39:21] Binding thread 1 to cpu 1
> [2017-07-17 17:39:21] Binding thread 2 to cpu 2
> [2017-07-17 17:39:21] Binding thread 3 to cpu 3
> [2017-07-17 17:39:22] No payout address provided, switching to getwork
> [2017-07-17 17:39:22] HTTP request failed: The requested URL returned error: 404 Not Found
> [2017-07-17 17:39:22] json_rpc_call failed, retry after 30 seconds

This is related to issue #333 which has not been solved.

ANy help would be really appreciated.

**Comment by thrasher-** [comment]
For solo mining, please see the following example:

`./minerd -o http://127.0.0.1:9332 -O user:x --no-longpoll --no-getwork --no-stratum --coinbase-addr=address
`
Replace address with your desired Litecoin address to generate coins to.

**Comment by noeldum** [comment]
that works. Thanks a lot!

**Comment by thezhongxina** [comment]
Hi its still not working 

[2021-11-01 11:33:36] HTTP request failed: Operation timed out after 30001 milliseconds with 0 bytes received
[2021-11-01 11:33:36] json_rpc_call failed, retry after 30 seconds
