### ISSUE TITLE
Linker errors when building on OSX 10.12 (current master 0.14.99)

### ISSUE THREAD

**Issue by HashUnlimited** [litecoin-project/litecoin#366]
While going through fine on 10.10, the linker fails on OSX 10.12:

  CXXLD    litecoind
Undefined symbols for architecture x86_64:
  "boost::this_thread::hiden::sleep_for(timespec const&)", referenced from:
      MilliSleep(long long) in libbitcoin_util.a(libbitcoin_util_a-utiltime.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [litecoind] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

### System:
298-MBP-MIP-3:litecoin michael$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

### configure options (default):
Options used to compile and link:
  with wallet   = yes
  with gui / qt = yes
    qt version  = 5
    with qr     = yes
  with zmq      = no
  with test     = yes
  with bench    = yes
  with upnp     = yes
  debug enabled = no
  werror        = no

  target os     = darwin
  build os      = darwin

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -isystem /opt/local/include -I/opt/local/include/db48 -I/usr/local/opt/berkeley-db@4/include -DMAC_OSX
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -Wno-self-assign -Wno-unused-local-typedef -Wno-deprecated-register
  LDFLAGS       =  -Wl,-headerpad_max_install_names -Wl,-dead_strip

### Machine specs:
- OS: OSX 10.12.6
- CPU: 2.8 GHz Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 750 GB
- Disk Type (HD/SDD): SSD

**Comment by thrasher-** [comment]
This issue appears related to https://github.com/litecoin-project/litecoin/issues/369. It seems as though there's an outdated libboost installed. Please try updating boost (and perhaps installing any other dependencies https://github.com/litecoin-project/litecoin/blob/master/doc/build-osx.md) through brew and recompiling. Compiling master with libboost 1.64.0_1 should work. Closing this and we can follow up the problem in the other issue.
