### ISSUE TITLE
Solo mining testnet

### ISSUE THREAD

**Issue by ILoveAllTheCoin** [litecoin-project/litecoin#368]
I have set up the Litecoin testnet locally on my computer, two nodes running connected to each other and no one else. I've downloaded CPUMiner 2.5.0 (minerd) and run the following.

`minerd -a scrypt -o http://127.0.0.1:19333 -u username -p Ghd8s7Sw13Yd -t 1 -D --no-stratum --no-longpoll --no-getwork --coinbase-addr=myp43yPrRwodbzeB8ChfqT7d53zYqdK71R`

However I get the following error.

    [2017-08-02 12:56:13] 1 miner threads started, using 'scrypt' algorithm.
    [2017-08-02 12:56:13] HTTP request failed: Empty reply from server
    [2017-08-02 12:56:13] json_rpc_call failed, retry after 30 seconds

Contents of my conf file for the client I'm trying to mine against. 19333 is the default testnet RPC port so does not need to be specified. The other local client has a different P2P and RPC port so they do not clash but I'm not able to mine against that one either.

    rpcuser=username
    rpcpassword=Ghd8s7Sw13Yd
    rpcallowip=127.0.0.1
    rpcallowip=192.168.1.155
    server=1
    listen=1
    daemon=1

    # Run on the test network instead of the real bitcoin network.
    #testnet=1

    # Run a regression test network
    #regtest=0

Any ideas what I need to do to be able to CPU mine the testnet?

**Comment by HashUnlimited** [comment]
your testnet flag is commented out? would be the first issue I see. remove the #

**Comment by thrasher-** [comment]
The default RPC port for testnet is 19332, the server port is 19333. Please try amending that and see how you go.

**Comment by ILoveAllTheCoin** [comment]
I launched the client with the -testnet option, it loads with the green Litecoin symbol and says testnet in the window title. I did not spot that the testnet line was commented out which explains why I had to use the launch option. Trying again with 19332 I get the following.

```
minerd -a scrypt -o http://127.0.0.1:19332 -u username -p Ghd8s7Sw13Yd -t 1 -D --no-stratum --no-longpoll --no-getwork --coinbase-addr=myp43yPrRwodbzeB8ChfqT7d53zYqdK71R
[2017-08-03 09:13:50] 1 miner threads started, using 'scrypt' algorithm.
[2017-08-03 09:13:50] HTTP request failed: The requested URL returned error: 500 Internal Server Error
[2017-08-03 09:13:50] json_rpc_call failed, retry after 30 seconds
```

When loading http://127.0.0.1:19332 in a browser I get the following.

`JSONRPC server handles only POST requests`

The nodes each show 1 connection to each other, I checked and there are no checkpoints on the testnet blockchain so the client should not expect that there are any blocks it needs to sync with, I believe that I should be able to mine but am not able to do so.

I am using latest win32 version of cpuminer from the following location.
https://sourceforge.net/projects/cpuminer/files/?source=navbar

**Comment by ILoveAllTheCoin** [comment]
Others have had the same error when their clients are not fully synced with the network. My nodes only know of each other and I am not sure why they would not be able to mine from the genesis block onwards. The Bitcoin client expects that there is a testnet chain already in existence and they have a checkpoint for it in their code.

Could the client expect a chain to sync with before allowing mining on the testnet even without a checkpoint entry?

**Comment by ILoveAllTheCoin** [comment]
> One possible reason may that with Bitcoin Core 0.13.1, it was mandatory to use SegWit-compatible mining software. When SegWit transactions are included in a block, a coinbase commitment to the witnesses is required by consensus rules. As the eventual selection of transaction in the block is done by the mining software, old mining software cannot be used to construct a SegWit block. On testnet, SegWit (BIP141) has been active since May 2016.
> 
> In Bitcoin Core 0.14, a change was made that permits old mining software to continue to operate. When such software is detected, Bitcoin Core will simply return a block template that excludes any SegWit transactions, alleviating the need for a coinbase commitment.
Source: Peter Wuille https://bitcoin.stackexchange.com/questions/53974/unable-to-mine-on-testnet/53975

**Comment by ILoveAllTheCoin** [comment]
I've found the fix for old miners to keep working.

Bitcoin 0.14.1 notes.

> In previous versions, getblocktemplate required segwit support from downstream clients/miners once the feature activated on the network. In this version, it now supports non-segwit clients even after activation, by removing all segwit transactions from the returned block template. This allows non-segwit miners to continue functioning correctly even after segwit has activated.
> 
> Due to the limitations in previous versions, getblocktemplate also recommended non-segwit clients to not signal for the segwit version-bit. Since this is no longer an issue, getblocktemplate now always recommends signalling segwit for all miners. This is safe because ability to enforce the rule is the only required criteria for safe activation, not actually producing segwit-enabled blocks.

Commit to allow old miners: https://github.com/bitcoin/bitcoin/pull/9955/commits

**Comment by HashUnlimited** [comment]
If you want to mine from genesis, you need to remove the checkpoints, otherwise your nodes will assume they aren't synced yet

**Comment by ILoveAllTheCoin** [comment]
Compiling Litecoin 0.14 and syncing with the testnet I can mine, I missed the checkpoint on the testnet chain. So I set the checkpoint to be the same as the genesis block. Deleted the testnet directories, launch the first client with -connect=0 and the second with -connect=127.0.0.1, both now show as connected to one another but I still get the "500 Internal Server Error" message when trying to mine.

Is there a way to set the checkpoint to null or to make it be ignored as setting it to the genesis block is not working?

Changes made and compiled to mine from genesis block, top lines are for reference.
```
genesis = CreateGenesisBlock(1486949366, 293345, 0x1e0ffff0, 1, 50 * COIN);
assert(consensus.hashGenesisBlock == uint256S("0x4966625a4b2851d9fdee139e56211a0d88575f59ed816ff5e6a63deb4e3e29a0"));

checkpointData = (CCheckpointData) {
    boost::assign::map_list_of
        ( 0, uint256S("0x4966625a4b2851d9fdee139e56211a0d88575f59ed816ff5e6a63deb4e3e29a0")),
};

chainTxData = ChainTxData{
    1486949366,
    1,
    0.01
};
```

**Comment by HashUnlimited** [comment]
1.) you need to remove the txdata as well

        chainTxData = ChainTxData{
            0,
            0,
            0
        };

2.) you need to define a different datadir for each node

**Comment by ILoveAllTheCoin** [comment]
1) Done. No Joy.
2) I am using a different datadir for each node. 

I've set GuessVerificationProgress to return 1.0 so it thinks it is up-to-date and DEFAULT_CHECKPOINTS_ENABLED is set to false to skip checkpoint checks.

This has reminded me of something I saw years ago with a new coin running the Bitcoin 0.11 codebase, it would not mine from the genesis block so an older version was ported to create a blockchain to bootstrap the newer client. I think the problem here runs a little deeper and is because Bitcoin (and Litecoin) is coded to expect a chain already exists. I'll head off and try to find a newer coin that has surmounted this problem.

**Comment by HashUnlimited** [comment]
Did you check my edits? On 0.13 I have started a fresh testnet more than once....

**Comment by ILoveAllTheCoin** [comment]
Running the generate command worked! The cpuminer returns "Empty data received in json_rpc_call." now which is different. I'll run the generate command and leave it running and will try cpuminer once a few more blocks have been created.

I could not find edits on Litecoin 0.13 under HashUnlimited, do you go by a different moniker?

**Comment by HashUnlimited** [comment]
I would call myself copy-paste-dev for Litecoin based Alts, the guys here would call that a little more diplomatic power user. I'm just trying to reproduce any issue I find on a plain LTC test chain before reporting, so there we had a few test networks running.

**Comment by ILoveAllTheCoin** [comment]
Thanks for your help on this, I would not have tried the generate command. I'll close this issue as it is largely solved. Thanks again.
