### ISSUE TITLE
[Documentation] v2 Transactions can only be mined by 0.14 nodes

### ISSUE THREAD

**Issue by HashUnlimited** [litecoin-project/litecoin#370]
That can be reproduced at least on a chain prior to SegWit activation on lock-in status. 0.13 nodes are ignoring mempool if the tx is version 2. Should be documented at some point.

**Comment by thrasher-** [comment]
IsStandardTx policy checks to see if the tx.nVersion > CTransaction::MAX_STANDARD_VERSION or < 1. 0.13.2 and 0.13.3 nodes has MAX_STANDARD_VERSION set to 2 and 0.14.2 default transaction version is 2, so they'll be accepted in either client. Any version deviating from that will be rejected. Segwit doesn't use the transaction version field at all so it's safe.
