### ISSUE TITLE
Litecoin Website Down/Missing

### ISSUE THREAD

**Issue by incomingstick** [litecoin-project/litecoin#378]
### Describe the issue
The Litecoin website seems to be down/missing. When visiting http://www.litecoin.org from any source (i.e the URL bar of a modern browser) takes you to a Norton Connect Safe page.

#### If so, please list the steps to reproduce below:
1. Visit http://www.litecoin.org from any source

### Expected behaviour
The Litecoin website should load.

### Actual behaviour
You are redirected to a Norton Connect Safe landing page. 

### Screenshots.
When visiting the website from Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/11799068/29693723-db3843c6-88fc-11e7-8a5b-67ebb3f00d6e.png)

When connecting for Google Chrome on an iPhone 6
![img_0033](https://user-images.githubusercontent.com/11799068/29693835-822a1394-88fd-11e7-817b-665f300d6c43.PNG)

**Comment by losh11** [comment]
Any idea what caused this issue?

**Comment by incomingstick** [comment]
@losh11 Honestly it was a weird internal network issue. I am honestly embarrassed to have jumped to conclusions right aware and immediately closed the issue. This issue can be ignored.

**Comment by thrasher-** [comment]
No worries, thanks for updating us :)

**Comment by incomingstick** [comment]
It is probably important to note that if anyone uses Norton for security in the browser, it flags litecoin.org as malware.
