### ISSUE TITLE
RPC server (litecoin-qt) does not work

### ISSUE THREAD

**Issue by martinpeterbauer** [litecoin-project/litecoin#380]
Hi,

iam using: ubuntu 16, 64Bit, litecoin version 14 (latest version to download)

First of all: Please remove the RPC help informations from litecoind. It is not good to have a help explain of this program and then getting the response by the program "rpc is no more possible in litecoind".

I let litecoin-qt running with the rpc comand line optiions (-server -rest -rpcbind, -rpcport, -rpcallowip.... ). The program listen on 9332 as expected. With tring a HTTP-GET Request from a browser the server send "Json-rpc is only with post requests possible" So ... i used post requests ... I tried to use / not to use the parameter rpclogin in some tests .....

My testing clients (curl / java) will get a tcp-connect but after/while sending the json-rpc request the litecoin.qt will just drop the tcp-connection. In detail: tcp-socket is accepted, request bytes are fullywritten - tcp socket is closedby forign host)

i send a typical json request like: {"jsonrpc": "1.0", "id":"curltest", "method": "getblockcount", "params": [] }.
I tried it with different values like "2.0" , with/without params-array, different methods ..... noting worked for me.

Any hints?

remark: setting -debug=rpc or -debug=1 did not produce any relevant information except that socket listener was started.

**Comment by thrasher-** [comment]
Please see below for some examples on how to communicate with the RPC server:

```
{"id":1,"method":"getinfo","params":null}
{"id":1,"method":"getblockhash","params":[1281158]}
{"id":1,"method":"getblock","params":["c911793646561a580dcfd8201881aca194ccf96b8209777b49f92748dabda3db"]}
```
The URL would be http://username:password@rpchost:rpcport. Example: http://user:pass@localhost:9332

You can find a Golang example here: https://github.com/thrasher-/litecoin-tools/blob/master/monitor/litecoinrpc.go
