### ISSUE TITLE
MilliSleep(long long) Boost issue OSX

### ISSUE THREAD

**Issue by jonn4y** [litecoin-project/litecoin#383]
I have pulled Litecoin from master branch and when i try to build on OSX i get the error:

  CXXLD    litecoind
Undefined symbols for architecture x86_64:
  "boost::this_thread::hiden::sleep_for(timespec const&)", referenced from:
      MilliSleep(long long) in libbitcoin_util.a(libbitcoin_util_a-utiltime.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [litecoind] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

I am running macOS Sierra 10.12.6
Boost version installed is 1.65.1 via Homebrew
in location:
/usr/local/Cellar/boost/1.65.1/

Litecoin Core: 0.13.99
I have tried uninstalling boost and building from source as mentioned here:
https://github.com/litecoin-project/litecoin/issues/170
and i get the same error.
I have made sure all the dependancies required are installed but seems to be a boost issue somewhere.

A fresh pull from master and ./autogen.sh - ./configure - make produces this log:
https://pastebin.com/byUg2msu

**Comment by thrasher-** [comment]
The latest master is now 0.15.0.1rc1. Please pull and try `brew uninstall boost --force`

Then `brew install automake berkeley-db4 libtool boost --c++11 miniupnpc openssl pkg-config protobuf qt libevent`

Then `make clean && ./autogen.sh && ./configure`

**Comment by jonn4y** [comment]
Hi, Thanks for the response, I followed the steps force removing boost, then building with --c++11 tag

as it was a fresh pull of 0.15.0.1rc1 make clean wouldn't work but i ./autogen.sh && ./configure then make and got the exact same error as before.

**Comment by jonn4y** [comment]
Ok figured it out, I have no idea why but in my /usr/local/include & /usr/local/lib folders i had some random boost files in there that shouldn't be there.
Removing these fixed my issue

**Comment by thrasher-** [comment]
Glad to hear you got it resolved!
