### ISSUE TITLE
[feature request] Backport smart fees from bitcoin core

### ISSUE THREAD

**Issue by runn1ng** [litecoin-project/litecoin#385]
Bitcoin core has a better fee algorithm in 0.15.0

See bitcoin/bitcoin#10199 and other commits in the directory

It returns more accurate fees and returns fees even for small / big block targets. (With very empty chains, current algoritm returns -1 for small targets, and for targets >= 25)

The more accurate fees are maybe not important for emptier blockchains like Litecoin, but the API is already better, because it doesn't return -1 for either too small targets or too big targets.

**Comment by thrasher-** [comment]
Master is currently 0.15.0.1 and we've pushed out a RC for it which now includes these changes :)

**Comment by runn1ng** [comment]
cool!
