### ISSUE TITLE
Failed to connect to testnet

### ISSUE THREAD

**Issue by DSofter** [litecoin-project/litecoin#387]
### Describe the issue
Downloaded and compiled `litecoin-0.13.2.1`, ran `./litecoind -testnet -printtoconsole` and got this:

![image](https://user-images.githubusercontent.com/1687829/31369649-bc436ccc-ad3a-11e7-9065-484c1cfd5b71.png)

### Machine specs:
- OS: OX X 10.9.5

Thank you!

**Comment by thrasher-** [comment]
v0.13.2.1 has testnet v3 which has been deprecated, Try the latest master (v0.15.0.1) and you'll have no connection issues.

**Comment by DSofter** [comment]
@thrasher- Thanks for responding! I tried and got this: https://github.com/litecoin-project/litecoin/issues/386

Any chance you know how to address this issue? Thanks!

**Comment by thrasher-** [comment]
Closing this issue, but will follow up the problem in #386. Just testing myself on OSX.
