### ISSUE TITLE
nBits different? can cause problems?

### ISSUE THREAD

**Issue by bilalpakistani** [litecoin-project/litecoin#388]
Hex Value of nBits of Litecoin 0x1e0ffff0 ==> 504365040 Decimal
While reading through the code. I found this mistake. I am not sure if it can cause any problems or not.
I have pointed out the mistake. in comments below.

   /// In the following line where 486604799 ==> 1d00ffff Which is Bitcoin's nBits value Should not be used
   /// but instead 504365040  this value should have been used. which is decimal value of nBits of Litecoin, I don't know if it can cause any problem

Which I found when you are creating Genesis Block 
`genesis = CreateGenesisBlock(1317972665, 2084524493, 0x1e0ffff0, 1, 50 * COIN);`
here you used,  0x1e0ffff0 this nBits value.  but when creating scriptSig you did not used it
but you used bitcoin's original nBits decimal. 486604799 as seen below

   /// This code from chainparams.cpp and function name:  createGenesisBlock 
`
    txNew.vin[0].scriptSig = CScript() << 486604799 << CScriptNum(4) << std::vector<unsigned char>
`

It should be like this

`
    txNew.vin[0].scriptSig = CScript() << 504365040 << CScriptNum(4) << std::vector<unsigned char>
`

**Comment by thrasher-** [comment]
Thanks, this has been fixed in the 0.15 branch.
