### ISSUE TITLE
GPG Signatures?

### ISSUE THREAD

**Issue by 2SI3NX** [litecoin-project/litecoin#390]
I know the GPG Signatures for litecoin-core are available on the download section of https://litecoin.org/
but is it possible for you to also post them on https://github.com/litecoin-project/litecoin/releases
where the Source code (zip) and Source code (tar.gz)  is posted for each future release?

Apologies if i have missed something, but i cannot seem to find them on github for each release.

**Comment by gabrieldov** [comment]
Yeah, would be great to have these sections updated - why version 0.13 is latest release if there are several other releases after?

**Comment by 2SI3NX** [comment]
yea i was also wondering the same thing

**Comment by losh11** [comment]
At the top, if you click the button with 3 dots in it, you can see all the new releases. For whatever reason, GitHub only like to show tags with a post.

**Comment by thrasher-** [comment]
Thanks for raising this! The Releases section has updated to reflect the past and latest versions. Will publish releases on GitHub as well moving forward.

**Comment by Exadra37** [comment]
This issue was closed but not addressed... The GPG keys are not available anywhere in this repo, thus we need to trust in the ones present in the website, but if the website gets compromised, then also the GPG keys will be compromised.

In my opinion the website should never publish the GPG keys, instead should link to them on this repo.

**Comment by 2SI3NX** [comment]
@thrasher- You solved a minor issue where the releases section was not displaying properly. GPG keys which was the original issue posted was not addressed.
As @Exadra37 mentioned. Your Github repo should be the 'go to place' to verify sources.
Each file should strictly:
1. Be signed with a GPG signature coming from a trusted developer.
2. Have a 256 hash

Security comes first.  We dont want what happened to https://electrum-ltc.org/#notice to happen to us do we?
