### ISSUE TITLE
feature request: PoW difficulty proportional to transaction volume.

### ISSUE THREAD

**Issue by happyjack27** [litecoin-project/litecoin#391]
proof-of-work difficulty should be proportional to total inter-wallet transaction size.

to keep proof-of-work difficulty and thus expected time to solve each block fairly constant, one can alter the number of transactions in the block.

large transactions could be broken up into smaller transactions to keep it well under this limit.

**Comment by thrasher-** [comment]
PoW difficulty adjustment over 2016 blocks is a proven and well working difficulty adjustment algorithm. Changing PoW difficulty adjustment to transaction volume opens a range of issues, be easily gamed and would require a hard fork.

**Comment by wrapperband** [comment]
Can you point me to the evidence that POW adjustment over 2016 is proven to work?

The difficulty adjustment algorythm is designed to compensate for changes in hash rate and is measured by how accurately the blockchain maintains it's designated block timing, 2 mins.30 secs.

**Comment by happyjack27** [comment]
you say "Changing PoW difficulty adjustment to transaction volume opens a
range of issues, be easily gamed and would require a hard fork."

can you name an issue that changing pow difficulty to transaction volume
opens?

can you demonstrate how it would be more easily gamed than the current
system, which disproportionally rewards attacks on large volume trades?

**Comment by happyjack27** [comment]
also it looks like you didn't read my whole request.  i'm not recommending
altering the global pow adjustment.   i'm recommending capping the block
size at a certain volume, so that the potential payoff of a successful
attack is capped.

**Comment by gabrieldov** [comment]
I believe you should send a more detailed LIP if you want to implement such a drastic change. Maybe you're right, but your request was not sufficiently convincing as well.

**Comment by happyjack27** [comment]
whats a "LIP"?

anyway i think if there was any confusion before, it's sufficiently
clarified now.  it's not a very complicated suggestion.

**Comment by happyjack27** [comment]
so what happens now -- does this feature request get re-opened?  it was
closed without justification.  closer never supplied any support for their
assertions and every assertion they made has been questioned.

one could easily set a very high cap, say max volume of 1% of total supply
per block.  this would greatly help keep the cost/reward ratio for
attempting an attack below one, by reducing it's theoretically max 100-fold.

if someone really wants to send more than that - they'll have to break it
up.  or the program could split it automatically.  I'm sure they won't mind
the added cryptographic protection.  that's why they're using the currency,
anyways.

**Comment by losh11** [comment]
What @gabrieldov meant by LIP is the Litecoin equivalent of the Bitcoin Improvement Proposal [BIP](https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki). This requires a technical specification, along with tests + a very thorough specification. Once you have that, please create a new Issue to restart discussion.

**Comment by happyjack27** [comment]
okay, i'm not going to do that.

way too much effort / tedium.

i've said my peace.  if the fact that $100,000,000,000 transactions have no
more security than $0.01 transactions comes back to bite anyone in the bum,
my hands are clean.

if someone else wants to take it and run with it, have at it.
