### ISSUE TITLE
question

### ISSUE THREAD

**Issue by eMosbat** [litecoin-project/litecoin#394]
I need bx tool for litecoin:

https://github.com/libbitcoin/libbitcoin-explorer/wiki

**Comment by thrasher-** [comment]
This is for Litecoin Core related issues, unfortunately I'm not aware of any port of libbitcoin for Litecoin currently.

**Comment by semozoo** [comment]
I’m confused, I’m not trying to work on litecoins core. If I gave that impression I apologize. Did I do something I’m unaware of? If so I can close down the project I started. I can plod away and have a good time trying to do something I’ve never attempted and it’s ok, no hurt feelings ;)
