### ISSUE TITLE
Litecoin Java API

### ISSUE THREAD

**Issue by jasgeeteden** [litecoin-project/litecoin#395]
I need Litecoin Java API, to create wallet and transaction, where can i find that?

Can I also use bitcoinJ API to create LTC wallet and transactions ?

**Comment by thrasher-** [comment]
You can find a Litecoin port of Bitcoinj here: https://github.com/litecoin-java/ but it is outdated.

**Comment by rschilling** [comment]
Just an observation which may help, if for no other reason to provide some perspective. I've gone through multiple projects: litecoin, litecoinj, bitcoin, bitcoinj, for C/C++, erlang, Java, and mobile apps. So, the code in all of these projects is pretty outdated. It's going to take some time to get the code ported properly.

**Comment by Syntaxide** [comment]
If you are planning on running the litecoin wallet, you could use https://en.bitcoin.it/wiki/API_reference_(JSON-RPC) to communicate with the wallet.

**Comment by thrasher-** [comment]
Closed due to inactivity and nothing to do with Litecoin Core dev.

**Comment by posuda** [comment]
Hi @jasgeeteden 
Which lib you use?

**Comment by LouisWayne** [comment]
Use this: https://github.com/GENERALBYTESCOM/litecoinj

**Comment by wang858** [comment]
> 使用此：[https](https://github.com/GENERALBYTESCOM/litecoinj)：[//github.com/GENERALBYTESCOM/litecoinj](https://github.com/GENERALBYTESCOM/litecoinj)

这个是怎么使用？
