### ISSUE TITLE
Strange transaction

### ISSUE THREAD

**Issue by axelay** [litecoin-project/litecoin#397]
I am not sure this is the best place to ask this but I am operating an exchange and we had a transaction coming in today that was unlike others.
What is strange about it (at least for me) is that it has no inputs: http://explorer.litecoin.net/tx/aff4332cccf3b16b989e7ff73b60d93746888e85daea928c0f7ab1f9997dd979
Try viewing this transaction in blockcypher and it craps out completely.

When I fetch the transaction from my server, the "details" contains this:
```    {
      "account": "",
      "address": "LhzF5H74piN4yjqeeShFW6haeutwfaQ69q",
      "category": "generate",
      "amount": 0.00722602,
      "label": "",
      "vout": 10
    }
```
I have never ever seen the category as "generate" - can someone explain what it is and how it got there?
The client said it came from a mining pool but I don't know the name yet - is this happening often?

**Comment by thrasher-** [comment]
When a block is mined it contains a generation transaction which pays out the block reward + fees to one or many addresses. In this case, the transaction above is the generation transaction, and it looks like whoever was mining at that pool set their payment address to their exchange deposit address.

**Comment by axelay** [comment]
That's what I thought - never realised there could be another category and that threw my process out.
Thanks for taking the time to answer - this issue is now closed.

**Comment by thrasher-** [comment]
No problem!

**Comment by axelay** [comment]
Bloomin' hell! I now got another weird category:
```
(
    [account] => 
    [address] => LfUAaohwbopkNzPHPT9vvtS9yWwBjUWukj
    [category] => immature
    [amount] => 0.20072472
    [label] => 
    [vout] => 51
)
```
How many of these should I care for when crediting user's account.
So far I know of *receive*, *generate* and now *immature* - any others I need to cater for?
