### ISSUE TITLE
Can't start to Compile

### ISSUE THREAD

**Issue by achillesss** [litecoin-project/litecoin#398]
This issue tracker is only for technical issues related to litecoin-core.

General litecoin questions and/or support requests and are best directed to the [litecointalk.io forums](https://litecointalk.io/).

For reporting security issues, please contact the Litecoin developers on the #litecoin-dev Freenode IRC channel or alternatively you can email us at contact@litecoin.org.

### Describe the issue
can't start to compile
### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1.  ``xcode-select --install``
2. ``brew install automake berkeley-db4 libtool boost --c++11 miniupnpc openssl pkg-config protobuf qt libevent``
3. ``brew install librsvg``
4. ``git clone https://github.com/litecoin-project/litecoin``
5. ``cd litecoin``
6. ``./autogen.sh``
7. ``./configure``
8. ``make``

### Expected behaviour
``make: *** No targets specified and no makefile found.  Stop.``

### Actual behaviour
shouldn't it start to compile ?

### What version of litecoin-core are you using?
code on the master branch

### Machine specs:
- OS: Mac 10.13.1

**Comment by thrasher-** [comment]
Please paste the output of the ./configure command so we can find out why it's not generating the makefile.

**Comment by achillesss** [comment]
@thrasher- here's the output: 

```bash
checking build system type... x86_64-apple-darwin17.2.0
checking host system type... x86_64-apple-darwin17.2.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in `/Users/freeza/projects/litecoin':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
```

many thanks!

**Comment by achillesss** [comment]
@thrasher-  seems that the C++ compiler doesn't work.  how should I solve this?

**Comment by thrasher-** [comment]
Try 

```
g++ -v 
```

and see if you get any output. If g++ doesn't exist, you'll need to install the command line developer tools.

**Comment by achillesss** [comment]
@thrasher- I tried ``g++ -v``, then got the following messages:

```bash
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

does this mean that I've already have a compiler but it doesn't work?

**Comment by thrasher-** [comment]
Yeah, you have a compiler installed, but it's unable to create any executables. Could you please paste the contents of your config.log file after running ./configure

**Comment by achillesss** [comment]
finally I figure it out, just add ``sudo`` before ``./configure``

```bash
sudo ./configure
```

@thrasher- thank you
