### ISSUE TITLE
error on import and export of private keys 

### ISSUE THREAD

**Issue by hansfbaier** [litecoin-project/litecoin#40]
I use litecoind 0.6.3c for linux.
I started litecoin-qt (encrypted wallet) and / or litecoind
and created litecoind.conf,

---

$ ./litecoin-0.6.3c-linux/bin/32/litecoind getinfo
{
    "version" : 60300,
    "protocolversion" : 60001,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 336328,
    "connections" : 3,
    "proxy" : "",
    "difficulty" : 323.27417770,
    "testnet" : false,
    "keypoololdest" : 1366066629,
    "keypoolsize" : 100,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00010000,
    "unlocked_until" : 0,
    "errors" : ""
}

$ ./litecoin-0.6.3c-linux/bin/32/litecoind listreceivedbyaddress 0 true | grep account
        "account" : "Schatzkiste",
        "account" : "Mining",

$ ./litecoin-0.6.3c-linux/bin/32/litecoind dumpprivkey Mining
error: {"code":-5,"message":"Invalid Litecoin address"}

If I use the address directly, I get:
$ ./litecoin-0.6.3c-linux/bin/32/litecoind dumpprivkey LhtD...
error: {"code":-4,"message":"Private key for address LhtD... is not known"}

Is this because I encrypted the wallet with litecoin-qt.
If yes, how in the world can I import private keys?

**Comment by webwakko** [comment]
Hi, The code-4 is not only related to the litecoin wallet but also on other wallets... I assume there must be a bad version of the QT-wallet that got used for several wallets.
This one does not allow to dump a private key for some addresses... the weird thing is that is allowed to dump a private key for a new address created within that same wallet... I would be happy to see the fix/solution for this dumpprivkey issue
