### ISSUE TITLE
How do I connect with Peer , what DNS Seeds are available for testnet ?

### ISSUE THREAD

**Issue by jasgeeteden** [litecoin-project/litecoin#400]
I am creating Litecoin Java API, 
but now I am struggling with Peer connection so I am unable to connect with bloackchain.

**Comment by untrustbank** [comment]
The test net seeds are found in the code at:
https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L231-#L233

The test net default TCP port is found in the code at:
https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L220

**Comment by thrasher-** [comment]
Feel free to join the #litecoin-dev to ask questions similar to the above. This is for issues relating to Litecoin Core.
