### ISSUE TITLE
Main and test loshan DNS seeds are down

### ISSUE THREAD

**Issue by untrustbank** [litecoin-project/litecoin#405]
The loshan DNS seeds for main net and test net are down or not configured. Reproduce name resolution failure with the following `dig` commands:

main net
```
dig @coco.ns.cloudflare.com seed-a.litecoin.loshan.co.uk a
...
loshan.co.uk.		3600	IN	SOA	coco.ns.cloudflare.com. dns.cloudflare.com. 2026227196 10000 2400 604800 3600
...
```
test net
```
dig @coco.ns.cloudflare.com seed-b.litecoin.loshan.co.uk a
...
loshan.co.uk.		3600	IN	SOA	coco.ns.cloudflare.com. dns.cloudflare.com. 2026227196 10000 2400 604800 3600
...
```

**Comment by losh11** [comment]
I’m working to bring them back online ASAP.

**Comment by rromanchuk** [comment]
@losh11 my crawler is also constantly ranking best nodes, and automatically generates new zone files. Just been busy and haven't finished the last step to actually update my zone files automatically.  This may be helpful for the community though.  


```
$ORIGIN seed.litenodes.net.
$TTL 60


@	28800	IN	SOA	ns1.litenodes.net. hostmaster.litenodes.net. (
				1513011133 ; SERIAL
				3600 ; REFRESH
				1800 ; RETRY
				1209600 ; EXPIRE
				60 ; MINIMUM
				)

@	1800	IN	NS	ns1.litenodes.net.
@	1800	IN	NS	ns2.litenodes.net.
@	1800	IN	NS	ns3.litenodes.net.
@	1800	IN	NS	ns4.litenodes.net.
@	1800	IN	NS	ns5.litenodes.net.

ns1	1800	IN	A	136.243.139.96
ns1	1800	IN	AAAA	2a01:4f8:212:3b1f::2
ns2	1800	IN	A	136.243.139.96
ns2	1800	IN	AAAA	2a01:4f8:212:3b1f::2
ns3	1800	IN	A	136.243.139.96
ns3	1800	IN	AAAA	2a01:4f8:212:3b1f::2
ns4	1800	IN	A	136.243.139.96
ns4	1800	IN	AAAA	2a01:4f8:212:3b1f::2
ns5	1800	IN	A	136.243.139.96
ns5	1800	IN	AAAA	2a01:4f8:212:3b1f::2

*.seed.litenodes.net.zone.	IN	CNAME	seed.litenodes.net.zone.
@	IN	A	84.209.146.99
@	IN	A	185.106.122.60
@	IN	A	66.96.207.87
@	IN	A	114.112.96.38
@	IN	A	81.229.156.238
@	IN	A	89.223.26.145
@	IN	A	185.176.41.60
@	IN	A	188.235.242.100
@	IN	A	46.40.30.216
@	IN	A	173.212.198.242
@	IN	A	80.106.185.170
@	IN	A	54.169.215.51
@	IN	A	45.63.76.239
@	IN	A	80.192.27.189
@	IN	A	158.248.254.46
@	IN	A	45.40.137.114
@	IN	A	180.162.20.163
@	IN	A	122.114.92.71
@	IN	A	77.55.216.156
@	IN	A	2.234.146.93
@	IN	A	72.226.7.21
@	IN	A	212.26.191.22
@	IN	A	89.212.75.6
@	IN	A	80.209.230.119
@	IN	A	138.197.142.104
@	IN	AAAA	2a00:c440:11:1196:107b:ed0f:8eac:2421
@	IN	AAAA	2a03:4000:1c:97::1
@	IN	AAAA	2a02:810c:c4c0:ec8:f023:f6a7:e5b7:ef4a
@	IN	AAAA	2a01:e34:edd2:78a0:c164:69dd:d3ef:1d0d
@	IN	AAAA	2001:0:9d38:6ab8:34d7:1ef2:a244:416f
@	IN	AAAA	2002:7169:8b2a::7169:8b2a
@	IN	AAAA	2405:4800:63c7:7f9:f11e:624d:e53c:a746
@	IN	AAAA	2400:2652:182:2200:4aa:9271:8774:a195
@	IN	AAAA	2002:2d74:af0a::2d74:af0a
@	IN	AAAA	2001:d08:c2:22ae:8a7:f135:76cf:49e8
@	IN	AAAA	2605:6000:f382:2a01:2956:4d27:32b3:3a92
@	IN	AAAA	2607:fea8:e1f:fa8f:d194:c19b:7dbd:cf83
@	IN	TXT	dp4tq3jsbmzp5ltc.onion
@	IN	TXT	czrgw3cgee7su4y7.onion
@	IN	TXT	qekekbdlg5isiuqm.onion
@	IN	TXT	ft5l3hssyd5dzy2g.onion
@	IN	TXT	rwwxs24bswdnjq7p.onion
@	IN	TXT	tgdhkkbrufpzaw3n.onion
```

**Comment by untrustbank** [comment]
@losh11 Do you need help getting updated address data to periodically update to CloudFlare via their API? That could be an easy way to go vs. running your own daemon that replies to DNS requests.

@rromanchuk I was wondering if your ranking algorithm takes into consideration the remote node's NODE_WITNESS service bit? The reason I ask is because of [this code in the upstream repo](https://github.com/bitcoin/bitcoin/blob/master/src/protocol.h#L296-L298). If that gets pulled into Litecoin Core (0.16 maybe?) then new nodes will only connect out to nodes with that bit set and it will be beneficial to seed out segwit nodes more often (or earlier in the result list).

**Comment by rromanchuk** [comment]
@untrustbank service bit is not a factor at the moment, but luckily i can add it easily.

Current logic
https://github.com/rromanchuk/bitnodes/blob/master/seeder.py#L155

I got 83% of the way in these automatically updating my zone files in r53 (don't want to mess with rolling my own bind right now), but haven't rolled it out yet. Doing too many things at once 💥

**Comment by untrustbank** [comment]
After I wrote that last message, I noticed that my concern is covered by most of the DNS seeds already supporting service bit specific lookups (for example via x9.seed-a.litecoin.loshan.co.uk, x9.dnsseed.thrasher.io, etc...).

I also looked at the CloudFlare API and it looks like it would be rather simple to make updates given a list of IPs (you don't even have to format a zone file or anything like that).

**Comment by untrustbank** [comment]
do you need help with this?

**Comment by untrustbank** [comment]
these seeds are still down

**Comment by thrasher-** [comment]
@losh11 is hoping to have it fixed tomorrow. We are currently monitoring all seeders using https://litecoin-monitor.thrasher.io/
