### ISSUE TITLE
Mac OS X Build Make Error

### ISSUE THREAD

**Issue by schwertfische** [litecoin-project/litecoin#406]
### Machine specs:
- OS: 10.12.6
- CPU: 3GHZ Intel Core i7
- RAM: 16 G 
- Disk size: 500G
- Disk Type (HD/SDD): SSD

Hi, 
following the steps to compile the project.
./autogen.sh
./configure
make
...
..... stopped here.
  GEN      qt/test/moc_wallettests.cpp
  CXX      qt/test/qt_test_test_litecoin_qt-moc_wallettests.o
  CXXLD    qt/test/test_litecoin-qt
  CXX      test/test_test_litecoin_fuzzy-test_bitcoin_fuzzy.o
  CXXLD    test/test_litecoin_fuzzy
Making all in doc/man
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.

What can i do?
thanks in advance
Kind regards

**Comment by rromanchuk** [comment]
Did you follow the directions here https://github.com/litecoin-project/litecoin/blob/master/doc/build-osx.md   Do you have all the dependencies?

**Comment by schwertfische** [comment]
@rromanchuk Yes, i followed all the instructions and i upgraded all dependences with brew.

**Comment by rromanchuk** [comment]
I don't see any errors?    Did you try `make deploy` or `./src/litecoind`

**Comment by thrasher-** [comment]
Looks good to me, on a successful compilation without any errors you'll
recieve output similar to above. Try Ryan's suggestion and it should work.

**Comment by schwertfische** [comment]
Those commands had worked good.

Elapsed Time:  5.941s
File size: 25886778 bytes, Checksum: CRC32 $32204AB7
Sectors processed: 160614, 145500 compressed
Speed: 12.0Mbytes/sec
Savings: 68.5%
created: /Users/inc/litecoin/Litecoin-Qt.dmg
+ Done +
So everything is ok?

**Comment by thrasher-** [comment]
You can ignore the deprecated warnings, the output of make deploy looks good.

So next steps are executing the .dmg file, which will then install Litecoin Core.

**Comment by thrasher-** [comment]
Closed as this issue appears fixed but please respond to this thread if you're still having issues.
