### ISSUE TITLE
Unable to compile on Ubuntu quantal 12.10

### ISSUE THREAD

**Issue by abrkn** [litecoin-project/litecoin#41]
```
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y build-essential libssl-dev libdb5.1-dev libdb5.1++-dev libboost-all-dev git libqrencode-dev

cd ~
git clone git://github.com/litecoin-project/litecoin.git
cd litecoin/src
make -f makefile.unix USE_UPNP=-
```

```
ubuntu@********:~/litecoin/src$ make -f makefile.unix USE_UPNP=-
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DUSE_IPV6 -DBOOST_SPIRIT_THREADSAFE -I/home/ubuntu/litecoin/src -I/home/ubuntu/litecoin/src/obj -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/bitcoinrpc.d -o obj/bitcoinrpc.o bitcoinrpc.cpp

æg++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make: *** [obj/bitcoinrpc.o] Error 4
```

**Comment by MorozCoi** [comment]
Hello everybody!
How can i fix it:
make -f makefile.unix USE_UPNP=-/bin/sh ../share/genbuild.sh obj/build.h
fatal: ваша текущая ветка «master» еще не содержит ни одного коммита
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/home/evgeniy/morozcoin/src -I/home/evgeniy/morozcoin/src/obj -DUSE_IPV6=1 -I/home/evgeniy/morozcoin/src/leveldb/include -I/home/evgeniy/morozcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/bitcoinrpc.d -o obj/bitcoinrpc.o bitcoinrpc.cpp
bitcoinrpc.cpp: In function ‘json_spirit::Object CallRPC(const string&, const Array&)’:
bitcoinrpc.cpp:1068:81: error: no matching function for call to ‘SSLIOStreamDevice<boost::asio::ip::tcp>::connect(std::__cxx11::string, int64)’
     if (!d.connect(GetArg("-rpcconnect", "127.0.0.1"), GetArg("-rpcport", 55883)))
                                                                                 ^
bitcoinrpc.cpp:586:10: note: candidate: bool SSLIOStreamDevice<Protocol>::connect(const string&, const string&) [with Protocol = boost::asio::ip::tcp; std::__cxx11::string = std::__cxx11::basic_string<char>]
     bool connect(const std::string& server, const std::string& port)
          ^
bitcoinrpc.cpp:586:10: note:   no known conversion for argument 2 from ‘int64 {aka long long int}’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
makefile.unix:172: failed to perform the recipe for the target «obj/bitcoinrpc.o»
make: *** [obj/bitcoinrpc.o] Error 1

**Comment by aaressinfomedia** [comment]
-- bool connect(const std::string& server, const std::string& port)

do necessory change in above line as given below

++ bool connect(const std::string& server, std::string port)
