### ISSUE TITLE
66: mempool min fee not met transaction gets stuck

### ISSUE THREAD

**Issue by gituser** [litecoin-project/litecoin#410]
I'm using Litecoin `v0.14.2`
### Describe the issue
Sometimes after successfully posting transaction to the network it isn't mined/distributed around.

If I try to re-send it with sendrawtransaction, I get: `66: mempool min fee not met` why am I getting this and how to fix it?

Please note: I'm setting every hour recommended fee via settxfee RPC call per KB from some 3rd party service. 
Could it be that this affects sending and re-distribution of transactions or is it generally mempool issue?
Thank you.

#### If so, please list the steps to reproduce below:
1. Create a new transaction
2. Try to re-send it via: `./litecoin-cli sendrawtransaction $(./litecoin-cli getrawtransaction <txid>)`
3. Get an error: `66: mempool min fee not met`

### Expected behaviour
Should be able to resend the transaction.

### Actual behaviour
Transaction gets stuck.

### What version of litecoin-core are you using?
Litecoin Core Daemon version v0.14.2

### Machine specs:
- OS: Linux

**Comment by losh11** [comment]
This is mainnet right? What fee per kb are you using at the moment? `Mintxfee` is 0.001LTC/kB.

**Comment by gituser** [comment]
@losh11, yes, it is.

currently fee set to: `0.00999000 LTC`

**Comment by thrasher-** [comment]
This came about by:

a) Large congestion on the Litecoin network at the time.
b) 5MB mempool limit. For a long time Litecoin didn't have much transaction per block volume so we lowered the limit to this. During the excitement over the past few months the mempool limit was hit, which lead to issues like the one above in which the mempool gets crowded and drives up the mempoolminfee. We've now set it to 300MB. This gives transactions with lower fees less chance of getting evicted. You can also adjust this value manually by setting `-maxmempool=<n>` where n is the size in MB.
c) 0.15.1 contains fee code improvements, as well as lowering the minrelayfee.
