### ISSUE TITLE
Wallet not loading anymore on Arch linux "libprotobuf.so.14" error

### ISSUE THREAD

**Issue by cercos** [litecoin-project/litecoin#417]
#### If so, please list the steps to reproduce below:
1. open terminal
2. run 'litecoin-qt'
3. receive error 'litecoin-qt: error while loading shared libraries: libprotobuf.so.14: cannot open shared object file: No such file or directory'

### Expected behaviour
Litecoin wallet should open

### Actual behaviour
Wallet doesn't open

### Machine specs:
- OS: Arch linux
- CPU: Intel Core i3
- RAM: 4GB
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

**Comment by hugohn** [comment]
Sounds like you are missing the protobuf libraries. What happens when you type 'protoc' in the command line?

**Comment by cercos** [comment]
Shows the help for the command

**Comment by RyuzakiKK** [comment]
protobuf has been updated on Arch to version 3.5.0.1, and now there is only libprotobuf.so.15 instead of 14.
@cercos have you tried to recompile litecoin-qt?

**Comment by cercos** [comment]
Recompiling fixed.  Thanks.

**Comment by thrasher-** [comment]
Glad to hear it's now working! Closing.
