### ISSUE TITLE
mining of alt coin generated from litecoin source on normal server or local computer 

### ISSUE THREAD

**Issue by adneerav** [litecoin-project/litecoin#425]
I have used litecoin latest source to build own alt coin. I have made required changes related to genesis block , nonce related.I am able to generate(build) Core wallet ,cli ,tx & qt files.

I am able to run core(mycoind) and its showing mycoind server starting. And also able to execute rpc command using mycoin-cli.

### Describe the issue
But somehow its not started mining. ? Or how can I check its already started ?How can I start mining for that coin ? I have copied same source and binary on two different aws server(ubuntu 16.0.4) for testing and added each other Ip in both conf file as addnode. Its showing in peer info(getpeerinfo) too.

### Actual behaviour
I am able to run core(mycoind) and its showing mycoind server starting. And also able to execute rpc command using mycoin-cli.

### What version of litecoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:Ubuntu 16.0.4
- CPU:i7
- RAM:12GB
- Disk size:250GB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally
[debug.log](https://github.com/litecoin-project/litecoin/files/1626233/debug.log)
 the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by thrasher-** [comment]
You'll need to use a mining application (like cpuminer or cgminer) which talks to your coins daemon. This is also out of the Litecoin issues scope so I'm closing this.
