### ISSUE TITLE
How to recover wallet.dat from backup 

### ISSUE THREAD

**Issue by bogdangainusa** [litecoin-project/litecoin#428]
### Describe the issue
Hello. I'm using litecoin core version 0.14.2 and suddenly i got one error and i cannot access my wallet. I found this out in debug.log.

`Warning: Warning: Wallet file corrupt, data salvaged! Original wallet.dat saved as wallet.{timestamp}.bak in "/home/cryptodaemon/.litecoin/"; if your balance or transactions are incorrect you should restore from a backup.`

Now i have 2 backups created, and i cannot access my wallet and also my accounts. Is there any way to recover whole wallet.dat file? I've tried to restart litecoin daemon with --salvagewallet but this don't help. Now i have 3 files:

wallet.151525xxx.bak wallet.151525xxx.bak wallet.dat Last one wallet.dat don't have any accounts or transactions... Please any solutions? I have a lot of money into my wallet.

### Machine specs:
- OS: amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux
- CPU: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
- RAM: 16G
- Disk size: 1000G
- Disk Type (HD/SDD): SSD

**Comment by thrasher-** [comment]
Did you make any backups of the wallet.dat file before the issue occurred? If so, please restore that file to `~/.litecoin/wallet.dat`. With any of the wallet files listed above, are you able to see any transactions when opening Litecoin Core? If so, please try running the Litecoin Core client with parameter `-rescan`

**Comment by thrasher-** [comment]
Closed due to inactivity but please post back here if you'd like to troubleshoot this further.
