### ISSUE TITLE
./configure error on OS Sierra

### ISSUE THREAD

**Issue by david-angga** [litecoin-project/litecoin#431]
Can't passed the ./configure command

Here's what I did:
1. xcode-select --install
2. brew install automake berkeley-db4 libtool boost --c++11 miniupnpc openssl pkg-config protobuf qt libevent
3. brew install librsvg
4. brew install zeromq
5. git clone https://github.com/litecoin-project/litecoin
6. cd litecoin
7. ./autogen.sh
8. ./configure

### Expected behaviour
Should build and make 

### Actual behaviour
Error message:
./configure: line 1: syntax error near unexpected token `('
./configure: line 1: `m4trace:configure.ac:11: -1- AC_INIT([Litecoin Core], [_CLIENT_VERSION_MAJOR._CLIENT_VERSION_MINOR._CLIENT_VERSION_REVISION], [https://github.com/litecoin-project/litecoin/issues], [litecoin], [https://litecoin.org/])'

On OS Sierra: 10.12.6

**Comment by david-angga** [comment]
Update, ./autogen.sh also failed with this error message:

> /usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:45: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1

**Comment by thrasher-** [comment]
Very strange that it's unable to find `sed`. That's a base system utility and should be in /usr/bin/sed. Doing a search on the web seems to show similar results and all to do with brew after this particular commit https://github.com/Homebrew/brew/commit/36efa1a9b9f77b742ae5496e75a6efb08ef3d175. Please try `brew update` or `brew repair`.

**Comment by thrasher-** [comment]
Closed due to inactivity but please post back here if you'd like to troubleshoot this issue further.

**Comment by srgtcauliflour** [comment]
Sorry to re-open a dead post but I'm also experiencing the OP's Initial ./configure issue on OSX High Sierra 10.13.6
Just curious if the OP managed to find a Solution?

./configure: line 1: syntax error near unexpected token `('
./configure: line 1: `m4trace:configure.ac:11: -1- AC_INIT([Litecoin Core], [_CLIENT_VERSION_MAJOR._CLIENT_VERSION_MINOR._CLIENT_VERSION_REVISION], [https://github.com/litecoin-project/litecoin/issues], [litecoin], [https://litecoin.org/])'
