### ISSUE TITLE
litecoin-0.14.2-linux-signatures file improperly encoded

### ISSUE THREAD

**Issue by michaelplews** [litecoin-project/litecoin#432]
### Describe the issue

OS: Ubuntu 16.04 LTS

`litecoin-0.14.2-linux-signatures.asc` ([located here](https://download.litecoin.org/litecoin-0.14.2/linux/litecoin-0.14.2-linux-signatures.asc)) gpg signatures file has a strange file encoding, meaning simply running:

```bash
sha256sum litecoin-0.14.2-linux-signatures.asc -c
```
results in:
```bash
sha256sum: 'litecoin-0.14.2-aarch64-linux-gnu.tar.gz'$'\r': No such file or directory
: FAILED open or read64-linux-gnu.tar.gz
sha256sum: 'litecoin-0.14.2-arm-linux-gnueabihf.tar.gz'$'\r': No such file or directory
: FAILED open or readinux-gnueabihf.tar.gz
sha256sum: 'litecoin-0.14.2-i686-pc-linux-gnu.tar.gz'$'\r': No such file or directory
: FAILED open or readpc-linux-gnu.tar.gz
sha256sum: 'litecoin-0.14.2-x86_64-linux-gnu.tar.gz'$'\r': No such file or directory
: FAILED open or read4-linux-gnu.tar.gz
sha256sum: WARNING: 15 lines are improperly formatted
sha256sum: WARNING: 4 listed files could not be read
```

### Any extra information that might be useful in the debugging process.
Changing the encoding to UTF-8 solves this issue.
```bash
$ sha256sum -c litecoin-0.14.2-linux-signatures.asc | grep OK
sha256sum: litecoin-0.14.2-aarch64-linux-gnu.tar.gz: No such file or directory
sha256sum: litecoin-0.14.2-arm-linux-gnueabihf.tar.gz: No such file or directory
sha256sum: litecoin-0.14.2-i686-pc-linux-gnu.tar.gz: No such file or directory
sha256sum: WARNING: 15 lines are improperly formatted
sha256sum: WARNING: 3 listed files could not be read
litecoin-0.14.2-x86_64-linux-gnu.tar.gz: OK
```

**Comment by t-nelson** [comment]
It just has DOS line endings. Trying installing the package ```tofrodos```, then you can use a command like ```fromdos < litecoin-0.14.2-linux-signatures.asc | sha256sum -c -```

**Comment by thrasher-** [comment]
The binaries for v0.14.2 were signed using a Windows machine hence the DOS encoding. The above commands works however future versions will be UTF-8 encoded. 0.15.1rc1 uses it now:

https://download.litecoin.org/litecoin-0.15.1rc1/linux/

```
$ sha256sum -c litecoin-0.15.1rc1-linux-signatures.asc 
litecoin-0.15.1-aarch64-linux-gnu.tar.gz: OK
litecoin-0.15.1-arm-linux-gnueabihf.tar.gz: OK
litecoin-0.15.1-i686-pc-linux-gnu.tar.gz: OK
litecoin-0.15.1-x86_64-linux-gnu.tar.gz: OK
```
You still also can individually gpg verify each file and for extra security can perform gitian builds to compare your hashes against others.
