### ISSUE TITLE
Bitcoin core P2SH segwit address is valid on Litecoin chain.

### ISSUE THREAD

**Issue by coinsmith** [litecoin-project/litecoin#433]
Please see this issue at the Bitcoin repo.

https://github.com/bitcoin/bitcoin/issues/12301#issuecomment-361557715

Thanks.

**Comment by westonal** [comment]
@coinsmith Please summarise the issue here. Rather than make people follow the link.

**Comment by coinsmith** [comment]
Describe the issue

As a test, I withdrew litecoin to a Bitcoin core generated segwit address. I used a Yobit wallet for this test. The withdrawal went through and now sits in a litecoin address identical to the Bitcoin core generated segwit address

What behavior did you expect?

I would expect the transaction to bounce, since the segwit address is generated from a Bitcoin address

What was the actual behavior?

The transferred litecoin now sits in what originally was a Bitcoin address

**Comment by westonal** [comment]
Yes it appears to deliberately support both: https://github.com/litecoin-project/litecoin/blob/94adaf8468fad3607f0639b55e7b3cbd0758fd53/src/chainparams.cpp#L134
`5` and `50`

You should still be able to use the same private key to send the litecoin.

**Comment by thrasher-** [comment]
When Litecoin was first released, it had the same P2SH value as Bitcoin which caused a lot of confusion. Since then, we've recently changed it to M whilst also supporting 3 for compatibility. In version 0.16, we'll have our own native address format for Litecoin segwit transactions via bech32.

**Comment by thrasher-** [comment]
v0.16.0rc1 is now tagged. Litecoin Core will only produce P2SH-segwit addresses prefixed with M by default and also produces native segwit addresses using bech32 (ltc1..). It will still however support 3 for compatibility.
