### ISSUE TITLE
How we can define premine coin

### ISSUE THREAD

**Issue by tarun1982** [litecoin-project/litecoin#436]
How we can define amount premine coin

**Comment by losh11** [comment]
This issues section is not for any other cryptocurrency that isn't Litecoin. Unfortunately we cannot help you with this.

**Comment by tarun1982** [comment]
Litecoin support premine coin Or not, can you pls confirm this.

**Comment by kcw-grunt** [comment]
@tarun1982 Pre-mining is running a blockchain before the general public gets access.  Litecoin was never pre-mined.  And, it's blockchain is already released.  I'm sorry but your question doesn't make sense for a cryptocurrency that is already being available to the general public.
