### ISSUE TITLE
MinGW Runtime Assertion Failed when changing passphrase on wallet

### ISSUE THREAD

**Issue by elomatt** [litecoin-project/litecoin#441]
### Issue description

Apologies if this is an inappropriate place to raise this, but I was directed here from a comment on [my reddit thread](https://www.reddit.com/r/litecoin/comments/7x3wn6/mingw_runtime_assertion_failed_when_changing/)

I've got a Litecoin wallet on a Windows 7 64-bit machine running Litecoin Core version v0.14.2 (64-bit). I've left it alone for some time, and wanted to change the passphrase (which I have written down so I'm pretty sure it's correct). When I enter the old passphrase the wallet software throws a [MinGW Runtime Assertion error](https://imgur.com/a/DyurS). I've seen two other threads with this same issue but neither of them had solutions. I tried re-installing the client and rescanning the blockchain but no dice.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. Run Litecoin-Core (64-bit)
2. Open "change passphrase" dialog box
3. Enter old and new passphrases

### Expected behaviour
The passphrase should change and I should get a confirmation dialog box

### Actual behaviour
The wallet software throws a [MinGW Runtime Assertion error](https://imgur.com/a/DyurS). If I click ignore, I get told I entered the wrong passphrase. If I choose abort or retry the client crashes.

### What version of litecoin-core are you using?
0.14.2

### Machine specs:
- OS: Windows 7 64-bit
- CPU: 64-bit processor, can't remember exactly what and I'm not at that workstation now
- RAM: 16 GB I think
- Disk size: Loads
- Disk Type (HD/SDD): Mixed

### Any extra information that might be useful in the debugging process.
I noticed that when I put in a passphrase I know to be incorrect I do not get the assertion error- I just get a message about the phrase being wrong. It's only when I put in the passphrase which should be correct that this error kicks. Then, when I "Ignore" the error, I get a message that I put in the wrong phrase. If I "Abort" or "Retry" then the client crashes. This leads me to believe that I have correctly remembered the passphrase, but something's wrong with it being re-set.

I'll try and add log files to this issue later.

**Comment by thrasher-** [comment]
Hey @elomatt,

That particular assert is thrown when some keys are able to be decrypted but not all. It's usually indicative that the wallet file is corrupted. Are you able to load your wallet with a passphrase and see all transactions without using the change passphrase option? If so, please make a backup of your wallet.dat file. Then once you have a backup, try running Litecoin Core with -salvagewallet to create a new wallet file.

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to follow this up if you wish to pursue this issue.

**Comment by elomatt** [comment]
Sorry for being absent for so long and thanks for your reply. I can see the transaction history for the wallet, and I finally got round to trying this. Steps:

1. Stop all litecoin processes
2. Back up wallet.dat
3. From a command prompt, run: "litecoin-qt.exe -salvagewallet" (this opens a Litecoin Core Version 0.14.2 window and then it starts loading)
4. Wait for it to rescan the blockchain (I left it alone for a couple of days)
5. The same interface as always shows up and I have the same situation as before.
