### ISSUE TITLE
Invalid “-onion”-address

### ISSUE THREAD

**Issue by Kewwvo** [litecoin-project/litecoin#447]
Whenever I try to open Lightcoin Core v0.14.2 on my MacBook I get stuck on 
“Verifying Wallet” 
and I get the additional message saying 
“Invalid “-onion”-address: ‘192…: 9050’”
After that LightcoinCore shuts itself down.
I cant get into the preferences menu to change IP or Port.
I’m locked out of the Program.
No coins on it, luckily.
I have tried deleting all the files and restarting and reinstalling: nothing.
Every time I reinstall and open (even running through terminal) I get the same result: nothing.
I also tried changing my IP address and Port settings on my router: nothing.
The “-onion” thing must be saved/stored somewhere. 
But I honestly don’t know what to look for.
Thank you in advance for taking the time!
![e2fa332ac689001a9e207438a587153d289391af](https://user-images.githubusercontent.com/36794267/36632375-5d612f9c-1986-11e8-837c-886a07fe977c.jpg)

**Comment by jmsktm** [comment]
Hey, I'm a novice. So my advice may not be of much help. But I found this:
https://github.com/litecoin-project/litecoin/blob/master/doc/tor.md

Seems like it's trying to run behind a Tor proxy.
qq: How are you starting the wallet? You aren't using the -proxy argument, right?

**Comment by Kewwvo** [comment]
Hi there,
first off, thank you for your time :)
I'm no expert on these thing either.

I've tried setting this up via Tor as mentioned in the link you've shared. But I got the same result.
I run the wallet simply by clicking on the application. 
It worked fine at first but now it's useless. Luckily I don't depend on it.
I also run Bitcoin Core and everything works just perfect.

**Comment by thrasher-** [comment]
Hi there,

By default Litecoin Core will check to see if a config file `litecoin.conf` exists in the ~/Library/Application Support/Litecoin directory. It might have a left over onion configuration in there if you set it up in the past. Please check to see if it exists in that directory and let us know.

**Comment by Kewwvo** [comment]
I've found a config file in "litecoin-master -> .tx -> config." 
upon loading i get
`/Users/../Desktop/litecoin-master/.tx/config ; exit;
/Users/../Desktop/litecoin-master/.tx/config: line 1: [main]: command not found
;; connection timed out; no servers could be reached
/Users/../Desktop/litecoin-master/.tx/config: line 4: [bitcoin.qt-translation-014x]: command not found
/Users/../Desktop/litecoin-master/.tx/config: line 5: lang: No such file or directory
/Users/../Desktop/litecoin-master/.tx/config: line 6: source_file: command not found
/Users/../Desktop/litecoin-master/.tx/config: line 7: source_lang: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
`

**Comment by Kewwvo** [comment]
The new version has solved everything ^^
Thank you all very much for doing what you're doing!
Peace

**Comment by thrasher-** [comment]
Glad to hear that the issue has been resolved!
