### ISSUE TITLE
v0.15.1 - p2pool

### ISSUE THREAD

**Issue by DJMorgan** [litecoin-project/litecoin#449]
v0.15.1 - p2pool will display a message when you start p2pool:
`> Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!`
What is the problem and what has changed daemon?

**Comment by K2Miner** [comment]
fresh first build is doing this same thing with me running:
 python run_p2pool.py --net litecoin --give-author 0 -f 1 -a LX...wallet adress

**Comment by DJMorgan** [comment]
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial 
```

**Comment by thrasher-** [comment]
Please see fix here: https://github.com/p2pool/p2pool/pull/380

**Comment by thrasher-** [comment]
Closed as this had been fixed upstream.
