### ISSUE TITLE
Will you please offer a macOS binary tarball download please?

### ISSUE THREAD

**Issue by J-Liu** [litecoin-project/litecoin#456]
I know it is not development question, but I didn't get a reply from contact@litecoin.org
DMG is very friendly to end users, but, still, lots of users wanna a cli wallet.

**Comment by thrasher-** [comment]
You can find the tarball at https://download.litecoin.org/litecoin-0.16.0rc1/osx/

Or for v0.15.1:

https://download.litecoin.org/litecoin-0.15.1/osx/

**Comment by J-Liu** [comment]
Cool! Thank You! It is really great!
