### ISSUE TITLE
Multiwallet support

### ISSUE THREAD

**Issue by kryvel** [litecoin-project/litecoin#458]
Hello,
Does have Litecoin support of multiwallet feature, that allows running with multiple -wallet options to load more than one wallet?
Same as in Bitcoin. [#8694](https://github.com/bitcoin/bitcoin/pull/8694)
Thanks in advance

**Comment by thrasher-** [comment]
Hey, 

Yes, both v0.15.1 and v0.16.0rc1 support multiple wallets.

**Comment by kryvel** [comment]
Great! Is it documented somewhere ? I did not find any information regarding it.. 
Is it ported from bitcoin and/or works in the same way ?

**Comment by thrasher-** [comment]
Documentation can be found here: https://github.com/litecoin-project/litecoin/blob/v0.15.0.1rc1/doc/release-notes-litecoin.md#multi-wallet-support

And for using the walletdir you can read about it here:
https://github.com/litecoin-project/litecoin/blob/v0.16.0rc1/doc/release-notes-litecoin.md#wallets-directory-configuration--walletdir

It behaves the same way as Bitcoin :)

**Comment by kryvel** [comment]
Thank you! 
Is wiki [litecoin.conf](https://litecoin.info/index.php/Litecoin.conf) page outdated ?

**Comment by thrasher-** [comment]
They were, the options have been updated on the Wiki.

**Comment by M-Shahbaz** [comment]
Hi,
What about dynamic wallet load / create/ separate instance for each wallet request
[https://github.com/bitcoin/bitcoin/issues/13059](S13059)
