### ISSUE TITLE
make[1]: Nothing to be done for 'all'

### ISSUE THREAD

**Issue by leegod** [litecoin-project/litecoin#460]
I git cloned litecoin.git, 

./autogen.sh
./configure --disable-tests --with-gui=qt5
make

and following errors.

![default](https://user-images.githubusercontent.com/6247030/38172175-4a1fa0da-35e2-11e8-86fb-0ae960b94625.PNG)

**Comment by thrasher-** [comment]
It appears you have a warning but no errors, the binaries should be found in the `/home/ubuntu/Desktop/litecoin/src` directory (litecoind, litecoin-cli, litecoin-tx) and Qt binaries located in the `/home/ubuntu/Desktop/litecoin/src/qt` directory.
