### ISSUE TITLE
addwitnessaddress report Segregated witness not enabled on network.

### ISSUE THREAD

**Issue by passionofvc** [litecoin-project/litecoin#464]
I create a segwit address for litecoin testnet but show me [Segregated witness not enabled on network]
Does litecoin support segwit address?
addwitnessaddress rpc not work.

`litecoin-cli.exe -datadir=temp -server -rpcuser=test -rpcpassword=test -rpcport=5555  -testnet -maxconnections=0 addwitnessaddress "muYMAMjf1ZeRQQxmArGJctRURGkHtj6L4d"`

error code: -4
error message:
Segregated witness not enabled on network

```
litecoind --version
Litecoin Core Daemon version v0.15.1
Copyright (C) 2011-2018 The Litecoin Core developers
Copyright (C) 2009-2018 The Bitcoin Core developers

```

**Comment by thrasher-** [comment]
Yes it does, how many blocks have you synced on testnet? You'll need to wait until 6048 blocks have been mined.

**Comment by passionofvc** [comment]
hi @thrasher- 
My local litecoind only run in -maxconnections not connect to peer, and no download or sync testnet ,
I  only want to create a segwit addess from local litecoin daemon.
do you mean must connect to testnet ?

**Comment by thrasher-** [comment]
Download and install v0.16.0rc1 from https://dev.litecoin.org or compile it from source.

You can then use `getnewaddress "" "bech32"` or `getnewaddress "" "p2sh-segwit"` to generate segwit addresses from the local daemon.

**Comment by passionofvc** [comment]
this is p2sh-segwit address output
```
getnewaddress "" "p2sh-segwit”
QaUEkpnMexTgHHuGRJQWrGUCtEgNHb9B3T

```
```
 validateaddress QaUEkpnMexTgHHuGRJQWrGUCtEgNHb9B3T
{
  "isvalid": true,
  "address": "QaUEkpnMexTgHHuGRJQWrGUCtEgNHb9B3T",
  "scriptPubKey": "a914981aa8f41e23ac0df0fc96420fe35ba98c7131c987",
  "ismine": true,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "script": "witness_v0_keyhash",
  "hex": "0014512794acc9e8aced32afe74def65490d9326e00f",
  "pubkey": "03c7933ab9e1b1031abeefe2da1d8a8edfcda2d65e8ae956f8965d2c02b626aa30",
  "embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "512794acc9e8aced32afe74def65490d9326e00f",
    "pubkey": "03c7933ab9e1b1031abeefe2da1d8a8edfcda2d65e8ae956f8965d2c02b626aa30",
    "address": "tltc1q2yneftxfazkw6v40uax77e2fpkfjdcq0fn0f3a",
    "scriptPubKey": "0014512794acc9e8aced32afe74def65490d9326e00f"
  },
  "addresses": [
    "tltc1q2yneftxfazkw6v40uax77e2fpkfjdcq0fn0f3a"
  ],
  "account": "p2sh-segwit",
  "timestamp": 1523762819,
  "hdkeypath": "m/0'/0'/21'",
  "hdmasterkeyid": "5354b09b4a0d665e1c884ba429ac91a34c7aac1c"
}

```
