### ISSUE TITLE
testnet.litecointools.com giving production address and showing 0 balance

### ISSUE THREAD

**Issue by Polve** [litecoin-project/litecoin#468]
I'm using the testnet faucet to do some tests, and the page says:
WALLET ADDRESS: LdvbJU7mp4JZFEvMiDdZfg6Soi36DG7pvc

but isn't LdvbJU7mp4JZFEvMiDdZfg6Soi36DG7pvc a production address?

Also, the balance is 0

**Comment by thrasher-** [comment]
This has been fixed now.

http://testnet.litecointools.com/

You can also use:

http://testnet.thrasher.io
