### ISSUE TITLE
Does the Light Coin have a developer fee?

### ISSUE THREAD

**Issue by munggo** [litecoin-project/litecoin#469]
Hi~!

I have a question.

Does the Light Coin have a developer fee?
Does the other coin also have a developer fee?

If so, how much do you charge?

**Comment by losh11** [comment]
If you're asking about mining reward being split and directed towards development, this does not happen with Litecoin. Most Litecoin Core developers are funded by the Litecoin Foundation, which is a non-profit organisation. The majority of the Litecoin Foundation's income is from community donations.
