### ISSUE TITLE
Why is your release page here in github such a mess?

### ISSUE THREAD

**Issue by cyberluke** [litecoin-project/litecoin#471]
Just why please why...0.13 marked latest, then one prerelease, then some secret newer version together with 0.15.1 that does not show by default. API /tx/send returns error 400 even on your installation.

**Comment by losh11** [comment]
v0.15.1 is the latest release. I've changed the 0.15.1 release to reflect that. GitHub seems to hide tags when you don't mark them as pre-releases or latest. 

I'm not sure what you mean by the API endpoint `/tx/send `.  Are you talking about the JSON-RPC api?

**Comment by thrasher-** [comment]
Unfortunately Litecore requires a specific patchset on top of Litecoin Core and the last version for Litecore is 0.13 so just replacing the binaries won't suffice. After Litecoin Core v0.16 is released, effort can be shifted to the Litecore port. Closing this issue as this repo is Litecoin Core specific and will address this in the litecore-litecoin repo.

**Comment by gituser** [comment]
So the last version is `v0.16.0` ?

On Github `v0.15.1` is still tagged as latest release. Can you fix this?

Thanks.
