### ISSUE TITLE
Help coin

### ISSUE THREAD

**Issue by GabrielLeonte** [litecoin-project/litecoin#473]
Where i can find coin maturity for 0.15 source code ?

**Comment by ZgrK** [comment]
@GabrielLeonte https://github.com/litecoin-project/litecoin/tree/0.15

**Comment by GabrielLeonte** [comment]
Where in what file is value of coin maturity ?

**Comment by thrasher-** [comment]
The value can be found here: 

https://github.com/litecoin-project/litecoin/blob/0.15/src/consensus/consensus.h#L19
