### ISSUE TITLE
Litecoin RPC Calculate the commission (PHP)

### ISSUE THREAD

**Issue by serderovsh** [litecoin-project/litecoin#475]
Hello, I have a small problem.
I can not calculate the commission in any way.

Implementation example:
```
 $litecoin = new jsonRPCClient('http://user:password@127.0.0.1:9332/');
 echo "<pre>\n";
  print_r($litecoin ->sendfrom('account', 'toaddress', '0.005')); echo "\n";
  echo "</pre>";
```

Please help, how to calculate the commission before shipment, the second day I can not solve this problem.

And another question: Is it possible to deduct a commission from the amount using the method "sendfrom"?

**Comment by thrasher-** [comment]
There's no commission API for handling payments. You'll need to create the logic for calculating the commission first and then send the commission to your desired address or account once you have received payment.
