### ISSUE TITLE
Litecoin Explorer API Doesn't Support Https

### ISSUE THREAD

**Issue by MelbourneDeveloper** [litecoin-project/litecoin#486]
**Description**

The Litecoin explorer API does not support GET requests over https. Https is critical for ensuring that traffic between APIs and apps etc. is encrypted for the privacy of the user.

**Expected Behaviour**

All API calls are forcibly encrypted.

**Actual Behaviour**

API GET calls can not be encrypted

**How reliably can you reproduce the issue, what are the steps to do so?**

Easily. This Url works:

http://explorer.litecoin.net/chain/Litecoin/q/addressbalance/LPabWk6qQwjoFPdgM4ahNsUeGJ19v7rdNm

This Url does not:

https://explorer.litecoin.net/chain/Litecoin/q/addressbalance/LPabWk6qQwjoFPdgM4ahNsUeGJ19v7rdNm

**What type of machine are you observing the error on (OS/CPU and disk type)?**

Windows 10 / Firefox

**Comment by thrasher-** [comment]
That block explorer is hosted by a community memeber, someguy123. I will ask him if he can enable SSL but for the mean time please use https://insight.litecore.io/

**Comment by xblau** [comment]
The API endpoints are documented here: https://github.com/bitpay/insight-api#api-http-endpoints

For example, if you want to get the current balance of an address:

    $ curl https://insight.litecore.io/api/addr/Ler4HNAEfwYhBmGXcFP2Po1NpRUEiK8km2/balance
    105000000

**Comment by MelbourneDeveloper** [comment]
@xblau  perfect. Thanks. 
@thrasher 

Are either of you interested in alpha testing a Trezor integrated Android app that supports Litecoin?

https://christianfindlay.wordpress.com/2018/04/22/hardfolio-alpha-testing/

**Comment by losh11** [comment]
People on reddit.com/r/litecoin will likely be very interested.
