### ISSUE TITLE
Litecoind address is valid in Bitcoind and I can send a transaction from BTC to LTC

### ISSUE THREAD

**Issue by PawanTiwariOodles** [litecoin-project/litecoin#495]
I have generated a Llitecoind address **mjSjjywqo5ijnQxEE15hq1e4R7JToL2G7p** and try to send test BTC from bitcoind. Transaction is successful and it is also showing on blocktrail. 
Here is hash : **354d07e45f06c2bcc2101fc0af7644bb8dc7737439a336bfc6c07435f34bdd8a**

My query is : how can I validate these addresses vice-versa. As both is valid on one another.
Like : 
`bitcoin-cli validateaddress "mjSjjywqo5ijnQxEE15hq1e4R7JToL2G7p"
{
  "isvalid": true,
  "address": "mjSjjywqo5ijnQxEE15hq1e4R7JToL2G7p",
  "scriptPubKey": "*******",
  "ismine": false,
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false
}
`
And from Litecoind, I validated bitcoind generated address. Here,
`itecoin-cli validateaddress "2N8oHRgYZLBxah4KF84asp4DFTemoDA3bwE"
{
  "isvalid": true,
  "address": "2N8oHRgYZLBxah4KF84asp4DFTemoDA3bwE",
  "scriptPubKey": "*****",
  "ismine": false,
  "iswatchonly": false,
  "isscript": true
}
`
Is there anything that validates these addresses.?
**There is an update:**
After updating the version f litecoind (v 0.16.0) Litecoind addresses are not valid on bitcoind, but bitcoind (v. 0.16) generated addresses are still valid on litecoind. And when I validate an address its generating an another address in response.

Test:  
` litecoin-cli validateaddress "2NA5RAtvvRVtHYjiqYRHQyL6tDtgGnMiLQ6"
{
  "isvalid": true,
  "address": "QdSBHuoASbwNgvUtAXKS42YKNH86hLGojv",
  "scriptPubKey": "***",
  "ismine": false,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false
}
`

**Comment by top1st** [comment]
the v0.16 generate invalid address on main net mode.

**Comment by thrasher-** [comment]
Litecoin uses the same script prefix on mainnet and testnet, so addresses starting with '3' will be valid on Litecoin and addresses starting with '2' will be valid on the testnet network. A version in the past was released to use 'M' for both P2SH and P2SH-segwit addresses, but moving foward the latest version of Litecoin Core supports bech32 addresses which means that all addresses have a ltc specific prefix. For example, on mainnet bech32 addresses start with 'ltc1' and testnet 'tltc'.
