### ISSUE TITLE
Dust threshold of Litecoin

### ISSUE THREAD

**Issue by pushdpopd** [litecoin-project/litecoin#498]
I'm investigating the specification of litecoin to create easy to use litecoin wallet.
 
In litecoin mainnet, when I try to broadcast 0.0001 LTC transaction, my transaction is rejected by the following error: 
"{"result":null,"error":{"code":-26,"message":"64: dust"},"id":"a92beefa-cc60-4c25-abae-9fb8a49e92cb"}"

Is 0.0001 LTC dust amount?
 I thought the implementation of dust judgement logic is same with bitcoin, but is there any difference? 

Any comments and advices are appreciated.

**Comment by ecurrencyhodler** [comment]
Dust is currently at 0.000546 LTC as the mintxfee is set at 0.001 LTC/kB.  The dust will be lowered when the mintxfee is lowered to 0.00001 LTC/kB in the future.

**Comment by thrasher-** [comment]
This will likely occur with the 0.17 release, depending on the amount of 0.16 nodes around that time.
