### ISSUE TITLE
Invalid address generate

### ISSUE THREAD

**Issue by Alfa911** [litecoin-project/litecoin#502]
Generate invalid address on wallet

{
  "isvalid": true,
  "address": "MCYEbmeTavop3ie7gw8D7jt7oJemFjyRn3",
  "scriptPubKey": "XXXXX",
  "ismine": true,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "script": "witness_v0_keyhash",
  "hex": "001453296e7a4be1f20c7763268b141edf4c30c19b22",
  "pubkey": "020aae01ecac0ec83f5e6778291099c904cf10cb5dd4877806ce1cb2d277ed7fbf",
  "embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "53296e7a4be1f20c7763268b141edf4c30c19b22",
    "pubkey": "020aae01ecac0ec83f5e6778291099c904cf10cb5dd4877806ce1cb2d277ed7fbf",
    "address": "ltc1q2v5ku7jtu8eqcamry693g8klfscvrxez6lvn08",
    "scriptPubKey": "001453296e7a4be1f20c7763268b141edf4c30c19b22"
  },
  "addresses": [
    "ltc1q2v5ku7jtu8eqcamry693g8klfscvrxez6lvn08"
  ],
  "account": "",
  "timestamp": 1528466796,
  "hdkeypath": "m/0'/0'/3'",
  "hdmasterkeyid": "f354a65c0f5c419f8536020abd61a31c082a08cc"
}

**Comment by thrasher-** [comment]
That address validates fine, it's a p2sh-segwit address. Why do you think it's invalid?

**Comment by Alfa911** [comment]
http://explorer.litecoin.net/address/MCYEbmeTavop3ie7gw8D7jt7oJemFjyRn3
https://chainz.cryptoid.info/ltc/search.dws?q=MCYEbmeTavop3ie7gw8D7jt7oJemFjyRn3
https://live.blockcypher.com/ltc/

they said  Invalid Address 
and cannot send coin from LTC wallets to this address

**Comment by thrasher-** [comment]
@Alfa911 both blockcypher and the explorer at litecoin.net do not support the new P2SH prefix `M`. However, both https://insight.litecore.io and https://chainz.cryptoid.info will work. For example, please see this link: https://insight.litecore.io/address/MAm3DE3MdvfcwTeFRg8Ucwzg6M2rUKKucq

Only wallets which support the new P2SH prefix and P2SH-segwit addresses will allow you to send funds to it. So if your exchange doesn't suport it, then you can generate a legacy address instead via `getnewaddress "" "legacy"` and use that instead.

**Comment by Alfa911** [comment]
Thank, with "legacy" work good
