### ISSUE TITLE
Hello! I am getting this error code when I am compiling my code

### ISSUE THREAD

**Issue by Mattistorm** [litecoin-project/litecoin#504]
I am getting this error code after I type in make -f makefile.unix
makefile.unix:186: recipe for target 'obj/main.o' failed
make: * [obj/main.o] Error 1

I know that this is an old version of litecoin, but I need help from someone to slove this problem

Regards Matt

**Comment by thrasher-** [comment]
Ensure that you have installed all the depencies listed in https://github.com/litecoin-project/litecoin/blob/0.8/doc/build-unix.md and are using the specific version mentioned. 

Followed by:

`make -f makefile.unix ` in the src directory for Linux/Unix. There has been countless upgrades in performance, features and security so it is not reccomended to base code off 0.8 anymore.
