### ISSUE TITLE
Bulk address sending

### ISSUE THREAD

**Issue by iocredit** [litecoin-project/litecoin#509]
Hey guys, I'd like to generate ~10,000 Litecoin addresses and send 0.0001 LTC to each one (for a giveaway), what would be the best way to go about automating it so I don't have to do it by hand? I know how to generate them, but what would be the best way to loop through them and make a transaction for each individual address? Is there a library I can use? Any help would be highly appreciated.

**Comment by thrasher-** [comment]
@iocredit This would be a pretty simple project just using Litecoin Core. You would need to write a script which talks to the litecoind JSONRPC API to generate 10,000 addresses, fund the wallet with enough funds and then use the `sendmany` API to send the desired amount to the recipients. You will need to make sure you abide by the dustrelayfee/minrelayfee limits though. However, bulk address sending amounts just at or above the dust limit is discouraged as it causes UTXO bloat and network congestion. Once again, this is for Litecoin Core **issues**, so please use another communication channel like the Litecoin talk forums or litecoin-dev IRC channel.

**Comment by onlyjob** [comment]
@iocredit, you are seeking help in doing something selfish, unjustified and potentially harmful to the Litecoin blockchain. Are you trying to test the limits of the network by flooding it with generated addresses, DDOS style??

Why don't we all generate 10_000 addresses each and see what happens?

Please act responsibly and don't do things like that without coordination and consent, even if you can.
