### ISSUE TITLE
How to run LTC full node on Ubuntu and configuration file format for LTC?

### ISSUE THREAD

**Issue by ishwarchandratiwari** [litecoin-project/litecoin#514]
**How to install and Launch LiteCoin daemon on machine?**
And what should be the correct LiteCoin configuration file format for LTC Mainnet, <br>I want to run LTC node with USERNAME and PASSWORD

**Comment by thrasher-** [comment]
You can either build the binary using the docs supplied in https://github.com/litecoin-project/litecoin/tree/master/doc or you can download the binaries from https://litecoin.org. 

A good guide for compiling and running can be found here:
https://medium.com/@baddour/setting-up-a-litecoin-full-node-a-complete-step-by-step-recipe-that-anyone-can-follow-fb18b82d5cfe

Note that this is related to Litecoin Core project issues, not general support so this request is better directed to the litecoin talk forums: https://litecointalk.io/
