### ISSUE TITLE
Need help! wallet.dat corrupt

### ISSUE THREAD

**Issue by aqwark** [litecoin-project/litecoin#515]
hello!

I need some help!
I accidentally deleted my wallet.dat (Litecoin wallet)
I recovered a wallet.dat and when i try to open the wallet it says
wallet.dat corrupt, salvage failed

the debug report say
"date": CDBEnv::Open: LogDir=D:\guldenblock\database ErrorFile=D:\guldenblock\db.log
"date": Failed to rename wallet.dat to wallet.some numbers.bak

I tried python pywallet.py

when i try walletrecover program from bitcoin

without code i get this error
C:\pywallet>pywallet.py --datadir=C:(folder where my wallet.dat is)\ --dumpwallet
Traceback (most recent call last):
File "C:\pywallet\pywallet.py", line 5004, in 
db_env = create_env(db_dir)
File "C:\pywallet\pywallet.py", line 1269, in create_env
r = db_env.open(db_dir, (DB_CREATE|DB_INIT_LOCK|DB_INIT_LOG|DB_INIT_MPOOL|DB_INIT_TXN|DB_THREAD|DB_RECOVER))
bsddb.db.DBNoSuchFileError: (2, 'No such file or directory -- C:\yourbkpwallet\__db.001: No such file or directory')

and with what i guess is the right code i get this error
C:\pywallet>pywallet.py --passphrase=(MyCode) --datadir=C:(folder where my wallet.dat is)\ --dumpwallet
ERROR:root:Couldn't open wallet.dat/main. Try quitting Bitcoin and running this again.

i think the bitcoin recovery script dont work on a wallet.dat from LTC
I already found https://github.com/magnux/pywaller, but it also does not help

so i dont know what to do anymore

im a windows user

**Comment by thrasher-** [comment]
Hey @aqwark, sorry to hear that you are experiencing issues with your wallet. How was the original wallet file recovered? Was it from a backup or a data recovery tool used to recover a deleted file?

**Comment by aqwark** [comment]
Hey Adrian!

Recovered from a data recovery tool...

среда, 4 июля 2018 г., 4:44 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by thrasher-** [comment]
There is a chance that the original location where the wallet file originally was stored on disk has been overwritten with new data which is why the salvage failed.

The output of pywallet above is showing issues opening the wallet file. Please see this guide here: 
https://bitcointalk.org/index.php?topic=398155.msg6964230#msg6964230

**Comment by thrasher-** [comment]
Closed due to inactivity, but please reopen if you wish to pursue this issue.
