### ISSUE TITLE
rpc api issue  

### ISSUE THREAD

**Issue by guanhui07** [litecoin-project/litecoin#519]
`  [root@master-yzjbz2154544231-1528962361316 ~]#    curl -X POST localhost:9332  -d  '{"id":1,"method":"getbalance","params":["LWVRyoJawzDYtvRmLVzUXqUSkNT7H1MLTt"]}' -H 'Authorization: Basic Z3Vhbmh1aTA3OjEyMzQ1Ng=='  

command not found

`
I try curl rpc from the command ，it return  command not found.

but this getblockhash  command  bellow
`[root@master-yzjbz2154544231-1528962361316 ~]#  curl -X POST localhost:9332  -d  '{"id":1,"method":"getblockhash","params":[1281]}' -H 'Authorization: Basic Z3Vhbmh1aTA3OjEyMzQ1Ng=='  -i

{"result":"baba7f471d08542028874caf03faa4c97c4480f8a01e044a99e68b7193f8e724","error":null,"id":1}
`

return right

**Comment by guanhui07** [comment]
curl -X POST localhost:9332  -d  '{"id":1,"method":"gettransaction","params":["e69caf5e5b6d6b3d513bb5eabd300e7e1844f52e1be5018f594c432977abcbce"]}' -H 'Authorization: Basic Z3Vhbmh1aTA3OjEyMzQ1Ng=='  -i
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Sat, 14 Jul 2018 07:32:50 GMT
Content-Length: 76

{"result":null,"error":{"code":-32601,"message":"Method not found"},"id":1}

**Comment by ashleyconnor** [comment]
Get balance takes an account not an address.

**Comment by joenhon** [comment]
I can't use the 'Wallet' method in cli，Do you know what the reason is?

**Comment by ashleyconnor** [comment]
What command are you running?

**Comment by joenhon** [comment]
• I found the reason, Because of version, The low version of wallet has “== wallet==” command

发送自 Joen

发件人: Ashley Connor
发送时间: 2018年8月31日 20:03
收件人: litecoin-project/litecoin
抄送: joenhon; Comment
主题: Re: [litecoin-project/litecoin] rpc api issue (#519)

What command are you running?

**Comment by ashleyconnor** [comment]
@joenhon can this be closed?

**Comment by thrasher-** [comment]
Closed due to a solution posted above.
