### ISSUE TITLE
Build a cryprocurrency

### ISSUE THREAD

**Issue by hsy0331** [litecoin-project/litecoin#528]
I am looking for a person who is able to create a token using litecoin or etherium.
I am wondering how much it cost to completely build up.

Our company is business advisory firm, and we are working for finance only not tech in "fintech,"
so we need to have a partners for "tech."

The first coin that we would build is based on a blockchain for evaluation system among buyer and seller, but I do not know which blockchain is better for this types of business.

Please advise for me and offer to build a token.

Thank you.

**Comment by AxelBlockchainDevelopment** [comment]
Hi, I can do this for you!

If you're still looking for this you can contact me on telegram, my username is: @AxelBlockchainDevelopment (https://t.me/AxelBlockchainDevelopment). 

Thanks :)

**Comment by hsy0331** [comment]
Thank you for your feedback.
I will install telegram, and I will contact you in this week.
Thank you

2018-08-12 15:42 GMT-04:00 AxelBlockchainDevelopment <
notifications@github.com>:
