### ISSUE TITLE
litecoin-cli giving false information? :/

### ISSUE THREAD

**Issue by quantaf1re** [litecoin-project/litecoin#529]
Hey guys, got a strange one here... I've been parsing Litecoin through the whole blockchain and have run into errors with a couple of transactions. Basically, it gives mostly false data - there are no inputs, value is wrong etc. Strangely, the txid is the same as the hash (which it shouldn't be - calling this tx with the 'true' txid is what pulls this data and shows the incorrect txid in the result). Maybe because there's no witness data in this result? Just guessing there.
The other strange thing is that I have 2 nodes running. Both nodes are returning the same incorrect information for the same tx's. They return the data perfectly fine for other tx's. I highly doubt that's a coincidence, but I thought a node is supposed to gather data from 8 other nodes when syncing the chain? My nodes are physically very close, so my only thought is that the 2nd node got all (or most) of its block from my 1st node?
I'm running litecoin-0.16.0-x86_64-linux-gnu downloaded from the website
To reproduce - just run the same rpc commands
2 Examples.
Example 1:
txid = a4b7fd54fe5f149ca34f248696fe706bcf9c358d47b6cee0d18bcbeee9db3dbd
On 2 explorers:
https://chainz.cryptoid.info/ltc/tx.dws?a4b7fd54fe5f149ca34f248696fe706bcf9c358d47b6cee0d18bcbeee9db3dbd.htm
https://chain.so/api/v2/tx/LTC/a4b7fd54fe5f149ca34f248696fe706bcf9c358d47b6cee0d18bcbeee9db3dbd

My rpc commands and its results:

~/litecoin-0.16.0/bin$ ./litecoin-cli --rpcuser=xxx --rpcpassword=xxx --rpcport=xxx --rpcconnect=xxx getrawtransaction a4b7fd54fe5f149ca34f248696fe706bcf9c358d47b6cee0d18bcbeee9db3dbd
01000000000101e010790e52239fcd4090fb5268994f271eaa1e97fa39f0ed9429def16b3022680000000000ffffffff02d05f98000000000017a914631e191027e407a30eee747dc8f168b826aa4f5f87a49c000000000000160014f0b439274270385364f753e8c379ac6e591bbc1a02483045022100b2d1f363b4f1f721173487d420163b4dfd32cafda732552027ed2e41fdf8522a02205f5a5116728c892d8376bff4b66e1823e3c7e23e139d32421436e7229317494d012103ccb1b5951a6ccd9159deec82545d07f2e380e70e07373548eeaa41d3dacca0a900000000

~/litecoin-0.16.0/bin$ ./litecoin-cli --rpcuser=xxx --rpcpassword=xxx --rpcport=xxx --rpcconnect=xxx decoderawtransaction 01000000000101e010790e52239fcd4090fb5268994f271eaa1e97fa39f0ed9429def16b3022680000000000ffffffff02d05f98000000000017a914631e191027e407a30eee747dc8f168b826aa4f5f87a49c000000000000160014f0b439274270385364f753e8c379ac6e591bbc1a02483045022100b2d1f363b4f1f721173487d420163b4dfd32cafda732552027ed2e41fdf8522a02205f5a5116728c892d8376bff4b66e1823e3c7e23e139d32421436e7229317494d012103ccb1b5951a6ccd9159deec82545d07f2e380e70e07373548eeaa41d3dacca0a900000000
{
  "txid": "006088188fa6d73b4bba43df91e36fba70fa02532732e75d4aa18681167b35b5",
  "hash": "006088188fa6d73b4bba43df91e36fba70fa02532732e75d4aa18681167b35b5",
  "version": 1,
  "size": 224,
  "vsize": 224,
  "locktime": 0,
  "vin": [
  ],Z
  "vout": [
    {
      "value": -69796447753.79967999,
      "n": 0,
      "scriptPubKey": {
        "asm": "90fb5268994f271eaa1e97fa39f0ed9429def16b3022680000000000ffffffff02d05f98000000000017a914631e191027e407a30eee747dc8f168b826aa4f5f OP_EQUAL OP_MAX OP_NUMEQUAL 0 0 0 0 0 0 0014f0b439274270385364f753e8c379ac6e591bbc1a 12360 022100b2d1f363b4f1f721173487d420163b4dfd32cafda732552027ed2e41fdf8522a02205f5a5116728c892d8376bff4b66e1823e3c7e23e139d32421436e7229317494d 33 -3518924 OP_MUL 6ccd9159deec82545d07f2e380e70e07373548eeaa41d3dacca0 OP_HASH160",
        "hex": "4090fb5268994f271eaa1e97fa39f0ed9429def16b3022680000000000ffffffff02d05f98000000000017a914631e191027e407a30eee747dc8f168b826aa4f5f87a49c000000000000160014f0b439274270385364f753e8c379ac6e591bbc1a02483045022100b2d1f363b4f1f721173487d420163b4dfd32cafda732552027ed2e41fdf8522a02205f5a5116728c892d8376bff4b66e1823e3c7e23e139d32421436e7229317494d012103ccb1b5951a6ccd9159deec82545d07f2e380e70e07373548eeaa41d3dacca0a9",
        "type": "nonstandard"
      }
    }
  ]
}

Example 2:
txid = 0a5c62f16623956f529c9b5fd62580e71a1dd8fa2a86d98dd6772589fef2e97c
https://chainz.cryptoid.info/ltc/tx.dws?0a5c62f16623956f529c9b5fd62580e71a1dd8fa2a86d98dd6772589fef2e97c.htm
https://chain.so/api/v2/tx/LTC/0a5c62f16623956f529c9b5fd62580e71a1dd8fa2a86d98dd6772589fef2e97c

My rpc commands and results:
~/litecoin-0.16.0/bin$ ./litecoin-cli --rpcuser=xxx --rpcpassword=xxx --rpcport=xxx --rpcconnect=xxx getrawtransaction 0a5c62f16623956f529c9b5fd62580e71a1dd8fa2a86d98dd6772589fef2e97c
010000000001019be9e1ef2ee29ee5a9556444999eb055d0e954e288f5b1845a7bb4d3567bd2f50100000017160014093c79f1986f9cb3042ca318ce47fd850c0840b2ffffffff02560d340000000000160014629970f72398c97ef31e23e7a6a1eceb39e3d6fe326c3105000000001976a914ed60bdb6ad828cf1b84f2d38ffac319ab1cee16088ac0247304402200b11e6361fc31b526c75c418f70a9d8e5a3d79f6e0b482207d54588057a546150220461863db6fcab7b92c0939ac5ad125a42519c6df08916cffaef7081725b2bcc40121039d6695322b82a32df4968eeae21ad5c9c5c809c6e34efb9c00598aa296d0b70100000000

~/litecoin-0.16.0/bin$ ./litecoin-cli --rpcuser=xxx --rpcpassword=xxx --rpcport=xxx --rpcconnect=xxx decoderawtransaction 010000000001019be9e1ef2ee29ee5a9556444999eb055d0e954e288f5b1845a7bb4d3567bd2f50100000017160014093c79f1986f9cb3042ca318ce47fd850c0840b2ffffffff02560d340000000000160014629970f72398c97ef31e23e7a6a1eceb39e3d6fe326c3105000000001976a914ed60bdb6ad828cf1b84f2d38ffac319ab1cee16088ac0247304402200b11e6361fc31b526c75c418f70a9d8e5a3d79f6e0b482207d54588057a546150220461863db6fcab7b92c0939ac5ad125a42519c6df08916cffaef7081725b2bcc40121039d6695322b82a32df4968eeae21ad5c9c5c809c6e34efb9c00598aa296d0b70100000000
{
  "txid": "cd57b05239dd4c26ab449be6daa4f4128ad742bd6604ef60def4473ec35506be",
  "hash": "cd57b05239dd4c26ab449be6daa4f4128ad742bd6604ef60def4473ec35506be",
  "version": 1,
  "size": 248,
  "vsize": 248,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
    {
      "value": -69979792631.58084863,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 5 OP_NOTIF 999eb055d0e954e288f5b1845a7bb4d3567bd2f50100000017160014093c79f1986f9cb3042ca318ce47fd850c0840b2ffffffff02560d340000000000160014629970f7 98c97ef31e23e7a6a1eceb39e3d6fe326c3105000000001976a914ed60bdb6ad828cf1 OP_NOP9 -1 38ffac319ab1cee16088ac0247304402200b11e6361fc31b526c75c418f70a9d8e5a3d79f6e0b482207d545880 7 OP_WITHIN 150220461863db6fcab7b92c0939ac5ad125a42519c6df08916cffaef7081725b2bcc40121039d6695322b82a32df4968eeae21ad5c9c5c809c6e34efb9c00598aa296d0b701",
        "hex": "a9556444999eb055d0e954e288f5b1845a7bb4d3567bd2f50100000017160014093c79f1986f9cb3042ca318ce47fd850c0840b2ffffffff02560d340000000000160014629970f72398c97ef31e23e7a6a1eceb39e3d6fe326c3105000000001976a914ed60bdb6ad828cf1b84f2d38ffac319ab1cee16088ac0247304402200b11e6361fc31b526c75c418f70a9d8e5a3d79f6e0b482207d54588057a546150220461863db6fcab7b92c0939ac5ad125a42519c6df08916cffaef7081725b2bcc40121039d6695322b82a32df4968eeae21ad5c9c5c809c6e34efb9c00598aa296d0b701",
        "type": "nonstandard"
      }
    }
  ]
}

Thanks in advance for any help working out what the issue is here! :slight_smile:

**Comment by thrasher-** [comment]
Hey @quantaf1re,

`decoderawtransaction` has a 2nd parameter for setting whether or not the transaction is a serialised witness transaction, in this example it is, so setting this to true will give you the correct output. If it is not specified, it will attempt to use heuristics to parse it.

**Comment by thrasher-** [comment]
Closed due to inactivity, but please reopen if you wish to pursue this issue.
