### ISSUE TITLE
qt not started and giving error 

### ISSUE THREAD

**Issue by potadibyo** [litecoin-project/litecoin#533]
whenever i run ./litecoin-qt i found this line of error
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

Please advice me for this problem.

**Comment by thrasher-** [comment]
Please provide details about the operating system and environment you are running. What version of Qt did you use to compile Litecoin Core?

**Comment by thrasher-** [comment]
Closed due to inactivity but please free to pursue this if you wish to.
