### ISSUE TITLE
how to use "walletnotify"

### ISSUE THREAD

**Issue by kazaff** [litecoin-project/litecoin#535]
hi, there~

When I run the wallet node, and set up the config like this:

```
...
walletnotify=/usr/bin/curl -H "Content-Type:application/json" -X POST -d '{"txid":"%s"}' http://xxxx
...
```

But it seemed not work.

What can i do?

**Comment by thrasher-** [comment]
Please check out this as an example: https://bitcoin.stackexchange.com/questions/24457/how-do-i-use-walletnotify

**Comment by kazaff** [comment]
All i need to do is just restart the wallet.....
So dumb i am.
