### ISSUE TITLE
Testnet stalling

### ISSUE THREAD

**Issue by NicolasDorier** [litecoin-project/litecoin#540]
I am synching a new node:

Latest log show I am on block `776519`.
```
2018-09-30 05:37:02 connect() to [2a01:4f9:2a:2518::2]:19335 failed: Cannot assign requested address (99)
2018-09-30 05:38:56 UpdateTip: new best=1d5263661c8678bc4e475af9509f8d45105f730181d14feeba1e4e68cab8ff5e height=776517 version=0x20000000 log2_work=53.010468 tx=1831703 date='2018-09-30 05:37:26' progress=1.000000 cache=0.0MiB(191txo)
2018-09-30 05:43:49 UpdateTip: new best=26c2c4147c422632f64a9058018095893e55d0617a93deaa4add21cc79d85bd6 height=776518 version=0x20000000 log2_work=53.010468 tx=1831708 date='2018-09-30 05:42:37' progress=1.000000 cache=0.0MiB(197txo)
2018-09-30 05:45:11 connect() to [2001:8a0:dda2:aa01:40a1:8579:ad55:8591]:19335 failed: Cannot assign requested address (99)
2018-09-30 05:47:54 UpdateTip: new best=c5bed9e6a7204996d46c5a749e73803811f3a4a4a044720acc5ade20a69171a5 height=776519 version=0x20000000 log2_work=53.010468 tx=1831710 date='2018-09-30 05:47:39' progress=1.000000 cache=0.0MiB(201txo)
```

`getblockchaininfo` show me that I have many header after.
```
root@BTCPayServerVM:~# litecoin-cli.sh getblockchaininfo
{
  "chain": "test",
  "blocks": 776519,
  "headers": 776710,
```

My node is super slow, probably downloading block slower than it can sync. 
Already tried to reboot.

Any solution? Does somebody has a reliable node I can connect to?

**Comment by losh11** [comment]
http://testnet.litecointools.com has a list of testnet v4 nodes you should
be able to connect with.

**Comment by NicolasDorier** [comment]
@losh11 ok so something is weird...

The top node at your address is

```
    "synced_headers": 776521,
    "synced_blocks": 776521,
```

Why does my node have more header? My node is in a constant state of IBD right now.

**Comment by NicolasDorier** [comment]
I guess the problem will solve by itself in 200 blocks, but this is weird.

**Comment by thrasher-** [comment]
It's because this peer is reporting a higher synced headers height:

Valid heights are at https://testnet.thrasher.io or http://testnet.litecointools.com

`
{
    "id": 4745,
    "addr": "5.165.18.58:55062",
    "addrlocal": "173.209.42.7:19335",
    "addrbind": "173.209.42.7:19335",
    "services": "000000000000040c",
    "relaytxes": true,
    "lastsend": 1538306454,
    "lastrecv": 1538306493,
    "bytessent": 49193,
    "bytesrecv": 2355,
    "conntime": 1538305851,
    "timeoffset": 1,
    "pingtime": 0.154072,
    "minping": 0.154072,
    "version": 70015,
    "subver": "/LitecoinCore:0.16.0/",
    "inbound": true,
    "addnode": false,
    "startingheight": 776814,
    "banscore": 0,
    "synced_headers": 776817,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 23932,
      "feefilter": 32,
      "getheaders": 1053,
      "headers": 23486,
      "inv": 61,
      "ping": 192,
      "pong": 192,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    },
    "bytesrecv_per_msg": {
      "addr": 55,
      "feefilter": 32,
      "getaddr": 24,
      "getheaders": 1053,
      "headers": 318,
      "inv": 244,
      "ping": 192,
      "pong": 192,
      "sendcmpct": 66,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    }
  },
`

**Comment by NicolasDorier** [comment]
@thrasher- my own node is reporting higher synced header. Seems that `blocks` match those two explorers. But my `headers` keep growing faster.

```
{
  "chain": "test",
  "blocks": 776582,
  "headers": 776818,
```

My verification progress never get over

```
"verificationprogress": 0.9999977783067506
```

**Comment by thrasher-** [comment]
Yeah, exactly. I banned their node and they seem to have stopped broadcasting a higher synced block height which was confusing nodes. Have you been able to complete IBD now? Seems as though they've stopped.

**Comment by NicolasDorier** [comment]
yes now it came back to normal
