### ISSUE TITLE
Wallet attempts to verify and rejects block 120 before confirming block 1

### ISSUE THREAD

**Issue by number435398** [litecoin-project/litecoin#542]
When playing with the newest version of litecoin for an alt coin I think I discovered an issue.  When I changed the block time to 1 minute and changed the retarget time to 1 hour (or 60 blocks), and tried it on an existing blockchain that it was forced to download fresh, I got the following:

1. Debug.log shows that it confirmed the genesis block.
2.  Debug.log doesn't show confirmation or rejection of blocks 1-119
3.  Debug.log shows it trying to confirm block 120 and rejects block 120.
4. ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: <insert hash for block 120 here>, bad-diffbits, incorrect proof of work (code 16)
5. Wallet Debug window shows "Current Number of Blocks: 0"

Code changed I think may have impacted it:
`//consensus.nPowTargetTimespan = 3.5 * 24 * 60 * 60; // 3.5 days`
`consensus.nPowTargetTimespan = 60 * 60; // 1 hour`
`//consensus.nPowTargetSpacing = 2.5 * 60;`
`consensus.nPowTargetSpacing = 60; // 1 minute`

**Comment by thrasher-** [comment]
This is related to altcoin development and you're adjusting consensus related variables so you're bound to cause issues if you're doing something which it doesn't expect.

**Comment by number435398** [comment]
Its perceived association with alt-coin development is irrelevant.  

It is something that is not supposed to occur within the code and could be exacerbated with a subsequent issue at a later time.  Obviously the debug output is not as verbose as it claims to be and it may be double-verifying the block hashes, once to check ahead on the blockchain and again to write it out to the debug.log; this is an issue regardless of its alt-coin relationship and why I did not close the matter myself after discovering the issues relating to it.  

The issue that the debug lacks the claimed verboseness that it should have remains a bug.  

Your dismissiveness of this due to my presentation thereof relating to an alt-coin is impeding to the continued development of litecoin core unto itself.
