### ISSUE TITLE
How to manage multi wallet on single daemon or qt running on server ?

### ISSUE THREAD

**Issue by adneerav** [litecoin-project/litecoin#545]
Hello,

I am trying understand the multiple wallet.I took the [reference from this link](https://github.com/litecoin-project/litecoin/blob/v0.15.0.1rc1/doc/release-notes-litecoin.md#multi-wallet-support)

What I want to do ?

 ### **I wants to create user wise wallet on same server where my daemon is running. Not like single wallet will have multiple accounts.So I can take the backup of each wallet and import too.**

Right now in single wallet we can create multiple accounts and each accounts can have multiple addresses using `getnewaddress` command from `-cli`

So when we start coin core daemon to load multiple wallet its required to pass wallet file too(correct me if I am wrong here) like below

`./litecoind -wallet=john.dat -wallet=jimmy.dat`

**_Is it proper way to give multiple wallet with `-wallet` & argument ? and what if any new wallet created if the daemon has been started with two wallet._**
**_eg. after starting daemon with john & jimmy 's wallet want to create new wallet (jack's wallet)._**

So in above example do I need to stop(`./litecoin-cli stop`) daemon and start daemon again with 3 wallets(`./litecoind -wallet=john.dat -wallet=jimmy.dat -wallet=jack.dat`) ?

[litecoin source URL.](https://github.com/litecoin-project/litecoin/tree/0.15)

For cli I am using like below(correct me if i am doing anything wrong)

```
./litecoin-cli -rpcwallet=jimmy.dat listaccounts
{
  "": 0.00000000
}
```

```
./litecoin-cli -rpcwallet=john.dat listaccounts
    {
  "": 0.00712000,
  "a": 0.00000000
}
```

**_For Rest api using as below (correct me if i am doing anything wrong)_**

`curl --user litecoinrpc:lite108local1234567890 --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listaccounts", "params": [] }' -H 'content-type: text/plain;' http://192.168.39.108:2301/wallet/john.dat`

**Output :**

`{"result":{"":0.00712000,"a":0.00000000},"error":null,"id":"curltest"}`

This is related to litecoin daemon, cli and  wallet only.

Thanks,

**Comment by furqansiddiqui** [comment]
You can better save wallets you wish to use in litecoin.conf like this:

```
wallet=jimmy.dat
wallet=john.dat
wallet=jack.dat
```

To add new wallets each time, yes you need to stop daemon, append config file and start daemon again. Now that you want to create a separate wallet for each user, its not possible to do dynamically, you will have to write a shell script that does this for you, however there is light at end of tunnel, since Bitcoin core from 0.17 supports dynamic loading and unloading of wallets but I am not sure when litecoin will reach there

**Comment by thrasher-** [comment]
Litecoin Core with dynamic loading and unloading of wallets will be supported once 0.17 is tagged (should be within the next week)

**Comment by adneerav** [comment]
Hello @thrasher- 
Thanks for the response 

Is there any pull request or or something for this update where I can get and test  ?

**Comment by adneerav** [comment]
Hello @thrasher-  

Is this the [0.17 version](https://github.com/thrasher-/litecoin/tree/0.17) which you pointed on this thread ?
Multieple wallet load unlocd https://github.com/thrasher-/litecoin/tree/0.17

**Comment by thrasher-** [comment]
Hey @adneerav, yeah that is the 0.17 version. It is currently undergoing review and will be branched into here once completed.

**Comment by adneerav** [comment]
@thrasher- 

thanks,
Is it possible to increase the maximum number of wallet load at a time ?

**Comment by adneerav** [comment]
Hello,

@thrasher-  with more detail on last comment

I am using litecoin core for the multiple wallet functionality from [0.17 branch](https://github.com/thrasher-/litecoin/tree/0.17) . All the wallet access and things I am doing using RPC.

Issue :
I am not able to load wallet more than 240(may b depends on system or db limit,Please correct me if I am wrong).

How can I increase the size of the DB or limit so I can load multiple wallet more compare to current limit.

Or is there any way where I can load multiple wallet more compare to current ?

Daemon getting stopped after 240 wallets.

What I've tried so far ?
I've added below things by creating DB_CONFIG file in datadirectory
set_lk_max_lockers 400000
set_lg_regionmax 1048576

Reference link of above : https://bitcoin.stackexchange.com/a/70737

**Result  :** same issue

If anyone face this type of issue please share or guide on this.

Thanks,

**Comment by thrasher-** [comment]
Closing as dynamic wallet loading/unloading is now supported, but can follow up the limit issues in https://github.com/litecoin-project/litecoin/issues/584

**Comment by adneerav** [comment]
Hello @thrasher-

I observed one more things for crashing daemon.
By using loadwallet api wallets are loading and I can make api request to that wallet.After loading multiple wallet dynmically using REST api i check memory usage.

After that I've unloaded wallet using unloadwallet REST api and observed the memory usage which should be lesser compare to at the time of wallets are loaded.But it showing same percentage or same mb/kb usage in both case(loadwallet & after unloading wallet)

So by unloading wallet i guess wallets objects are not getting released from the memory.And its increasing the memory usage and daemon getting crashed.

Similar issue(15526) was reported on Bitcoin too.And tried to make changes from bitcoin to litecoin source but faced same issue might be missing something.


Can you please give your input or help me to resolve this issue ?
Thanks,
