### ISSUE TITLE
can't send or receive coins using pubkey

### ISSUE THREAD

**Issue by Misriyadi** [litecoin-project/litecoin#546]
I tried using version 0.16, but when I tried to send coins, coins couldn't be accepted, maybe I could help my problem, thank you

**Comment by thrasher-** [comment]
Hi @Misriyadi, were you trying to send the coins to another user or an exchange? Do you have the transaction ID?

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to reopen this if you wish to pursue the issue.
