### ISSUE TITLE
X11 Connection Fail on OVH Server, XFCE Client

### ISSUE THREAD

**Issue by Mentors4EDU** [litecoin-project/litecoin#549]
The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 22 (Invalid argument) on X server ":50.0"
      after 389 requests (385 known processed) with 0 events remaining.
Similar to #381

To be able to load Litecoin--qt

It won't open and either has fault at segmentation or a fatal IO error. Similar system IO exceptions happened in the past with other crypto programs

One can try using the XFCE Client on X2GO

0.16.3 Pre-Compiled from site, 64 bit system

XUbuntu OS

**Comment by thrasher-** [comment]
Thanks for posting this and have replicated the problem. Will follow this up in #381 as it is related.
