### ISSUE TITLE
P2SH Converter

### ISSUE THREAD

**Issue by guchenglin111** [litecoin-project/litecoin#550]
How does Java implement the function of converting this link from 3Qfs JepRkgAjSwiJpD8VeFGTdz4RtZAFuo to MWt1cYEPho2AFSzCv67qTWrxgeswt7vZN?

**Comment by thrasher-** [comment]
It uses bitcoinjs and you can find the code here: https://github.com/litecoin-project/p2sh-convert/blob/master/index.html
