### ISSUE TITLE
Hang with QT 5.11.2 QSslConfigurationQSsl

### ISSUE THREAD

**Issue by MiWCryptoCurrency** [litecoin-project/litecoin#551]
Hang with QT 5.11.2 QSslConfiguration::defaultConfiguration() 

With QT 5.11.2 and OpenSSL 1.1.1, a deadlock occurs when calling  QSslConfiguration::defaultConfiguration() resulting in the qt application not loading. 

This code block was added in 2015 https://github.com/litecoin-project/litecoin/commit/15e26a6a9afe299b9ca6fced73b876644365879b to add this setting This setting is the default in QT > 5.4 and this setting no longer needs to be done in the client code.

This was discovered upstream in bitcoin in https://github.com/bitcoin/bitcoin/issues/14359
The fix was to remove the code
https://github.com/bitcoin/bitcoin/commit/2468471e13987b1be377e1b33fe9c5cdb7a7a3e3

After applying this commit, the client started as expected

**Comment by MiWCryptoCurrency** [comment]
https://github.com/litecoin-project/litecoin/pull/552

**Comment by thrasher-** [comment]
Thanks, the PR has been merged.
