### ISSUE TITLE
How to allow my litecoin daemon should connect to specific node/IP address of my other litecoin daemon

### ISSUE THREAD

**Issue by adneerav** [litecoin-project/litecoin#553]
Hello,

I want to make multiple litecoin daemons which I've setup on different server I want like one or two daemon should allow to connect any daemon based on dns seeds.

But other thn that two daemon rest of all **daemon should be connected to daemon as per given ip address.It should note connect other thn those nodes.**

I've tried to set things in `litecoin.conf` file with `connect` option
Apart from rpc username ,rpc password , port and daemon 1 below are configuration i tried.
```
connect=IP_ADDRES_OF_ONE_OF_MY_DAEMON_NO1
connect=IP_ADDRES_OF_ONE_OF_MY_DAEMON_NO2
connect=IP_ADDRES_OF_ONE_OF_MY_DAEMON_NO3
```
This all IP addresses have open required port and publicly open

So how to allow my daemons to connect & communicate with specific nodes/ip ?

I understand if litecoin team not allow & dont get time to provide answer of these type of questions but please respond anyone else who have the solution.

Thanks

**Comment by thrasher-** [comment]
You can start the litecoind daemon with command line param `-connect=ip`. This will attempt to make a connection to the node and sets the dnsseed functionality to 0. You'll need to ensure that the server=1 option in the config file is set and you can review the connection attempt in the `debug.log` file or if you specify `-printtoconsole` it will show up in the console. You can also see if you can telnet to each of the daemons to make sure that they're reachable.

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to reopen this if you wish to pursue the issue.
