### ISSUE TITLE
What is the maximum size of the block 

### ISSUE THREAD

**Issue by adneerav** [litecoin-project/litecoin#556]
Hello

I am creating wallet and setup on server for the litecoin wallet.But before that I want to check the size of the single block.
I am bit confused with 1 MB or 4 MB. And I've also checked [this issue](https://github.com/litecoin-project/litecoin/issues/194) and the files which is changed in bitcoin source but same files, variables are not in litecoin source

Is it changed in build/version/branch wise ?
I am using Branch 0.15 & 0.16.

And is there any documentation or where in source code block size related things are defined so in can if its changing or changed I can check branch wise to understand.As total block size I can get but individual block size I need to check.

I understand if litecoin/repository member can not reply on this type of question(If they can thn it would be great help) so if anyone else know please provide details.

Thanks

**Comment by thrasher-** [comment]
Hi @adneerav,

With segwit, blocks have a size and weight associated with them. Theoretically, blocks can fill up to a block weight around 4MB as per BIP141: https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#other-consensus-critical-limits Adjusting the block size/weight/total values is out of scope as this is only related to Litecoin Core issues.
