### ISSUE TITLE
how to get the utxos of my address?

### ISSUE THREAD

**Issue by waliguder** [litecoin-project/litecoin#557]
https://insight.litecore.io/ can not work?
Is there any other way to get an address for utxo? Or code implementation

**Comment by thrasher-** [comment]
https://insight.litecore.io/api/addr/LXA3i9eEAVDbgDqkThCa4D6BUJ3SEULkEr/utxo works and should be what you're after.

Litecoin Core supports a `listunspent` API call but that is only for addresses which you own.

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to reopen it if you wish to pursue this issue.

**Comment by losh11** [comment]
@CoinInn-Aries Insight Lite was formerly a block explorer with a publicly available API, this service is no longer being maintained, and thus it was shutdown. You can likely find many other Litecoin block explorers who may offer an API endpoint with similar functionally.

**Comment by CoinInn-Aries** [comment]
> @CoinInn-Aries Insight Lite was formerly a block explorer with a publicly available API, this service is no longer being maintained, and thus it was shutdown. You can likely find many other Litecoin block explorers who may offer an API endpoint with similar functionally.

Do you have a recommendation? thanks

**Comment by waliguder** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by arlong87** [comment]
> @CoinInn-Aries Insight Lite was formerly a block explorer with a publicly available API, this service is no longer being maintained, and thus it was shutdown. You can likely find many other Litecoin block explorers who may offer an API endpoint with similar functionally.

any example?

**Comment by waliguder** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by losh11** [comment]
> any example?

Litecoinspace.org is great.
