### ISSUE TITLE
Synchronized testnet data jam

### ISSUE THREAD

**Issue by ye21st** [litecoin-project/litecoin#561]
When I synced the network data, the wallet data will remain stuck for synchronization, 8 weeks ago.

Litecoin version: v0.15.1
QT version: 4.8.3
OS: Windows 7
litecoin.conf: 

> testnet=1
txindex=1
server=1
rpcuser=ffk
rpcpassword=ffk
rpcallowip=127.0.0.1
rpcallowip=192.168.1.120
rpcport=8336
port=8106
zmqpubrawtx=tcp://192.168.1.120:28336
zmqpubrawblock=tcp://192.168.1.120:28336
zmqpubhashtx=tcp://192.168.1.120:28336
zmqpubhashblock=tcp://192.168.1.120:28336

**Comment by thrasher-** [comment]
Your config looks good, have you confirmed that you're connected to any peers? Using this file, try adding `addnode=ip:port`. You can also find a bunch of other nodes using https://testnet.thrasher.io/. I'd also reccomend updating to the latest version (0.16.3) as that contains the most updated seed list and DNS seeders. It also contains very important security fixes.

**Comment by thrasher-** [comment]
Closed due to inactivity but please reopen if you wish to pursue this again

**Comment by qq29oo** [comment]
https://testnet.thrasher.io can not open,is there any website to find the p2p peers?
