### ISSUE TITLE
Transaction cannot be broadcast immediately, no-witness-yet

### ISSUE THREAD

**Issue by AlmscoinDEV** [litecoin-project/litecoin#562]
Hi!
I'm forked last version LTC. In testnet i try mine some blocks. It's successfully. But when i try send some coins from win QT to another node i see in TX that "not in memory pool" and i see in debug.log this - Transaction cannot be broadcast immediately, no-witness-yet
And in win QT, in Send tab i see this "warning fee estimation is currently not possible"

i mine 52 blocks and all coins are confirmed

Where is the error ?

P.S. Sorry for my bad eng :-(

**Comment by AlmscoinDEV** [comment]
@thrasher- pls help me!

**Comment by losh11** [comment]
Sorry we do not support Litecoin forked coins here.  Closing this issue since this is only for posting issues relating directly to Litecoin Core.
