### ISSUE TITLE
Litecoind is displaying BUS error

### ISSUE THREAD

**Issue by aaroncatalano** [litecoin-project/litecoin#564]
Ubuntu 18 

Executed litecoind

Bug: Never starts. Returns the following error:  Bus error (core dumped)

Make completes successfully without any errors.  Do not get this message if run bitcoind command against bitcon classic.  Google did not return solution.

**Comment by thrasher-** [comment]
What operating system are you running and which version of Litecoin Core are you using?

**Comment by thrasher-** [comment]
Can you please paste the contents of your debug.log file?

**Comment by aaroncatalano** [comment]
Appears to be hardware issue related to Ubuntu 18. Was able to compile successfully on Ubuntu 16.04, MAC, and Windows/Linux Bash.
