### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [litecoin-project/litecoin#566]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support LTC on our service for a long time and we have been exchanging LTC for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by losh11** [comment]
This is the Litecoin Core issues page. I’d recommend that you’d cantact the Litecoin Foundation at contact@litecoinfoundation.org.

**Comment by BestChangeOfficial** [comment]
We started a partnership with this exchanger and it is already listed on our monitor. Also, you may leave your feedback or review on this page: https://www.bestchange.com/simpleswap-exchanger.html
