### ISSUE TITLE
Makefile:9544: recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by VtpVlan-oo7** [litecoin-project/litecoin#569]
collect2: error: ld returned 1 exit status
Makefile:3708: recipe for target 'litecoind' failed
make[2]: *** [litecoind] Error 1
make[2]: Leaving directory '/home/surya/litecoin/src'
Makefile:9544: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1

please help me to fix this issue !!

![image](https://user-images.githubusercontent.com/31241756/50400642-3e27a400-07ae-11e9-827c-6016fac49c0e.png)

**Comment by thrasher-** [comment]
Please ensure that you have the right version of boost installed and all other dependencies: https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian

**Comment by BhumikaB** [comment]
Thanks a lot, it helps
