### ISSUE TITLE
IBD starting year during startup directory entry at bitcoin value

### ISSUE THREAD

**Issue by Trombonista** [litecoin-project/litecoin#575]
Hello!
Just a small typo / copy-paste-error:  IBD "last block time" is "Fri Oct 7 09:31:05 2011" (seems correct w/o headers), but when asking for data directory (initial startup), it says "load history since 2009, when litecoin first started" (=bitcoin starting date). Expected DL size seems o.k.
Seen at litecoin core 0.16.3 linux 64bit
best regards

**Comment by thrasher-** [comment]
Thanks! A PR has been submitted.
