### ISSUE TITLE
Wrong RU localization (bitcoin instead of litecoin)

### ISSUE THREAD

**Issue by OlegKozhemiakin** [litecoin-project/litecoin#577]
"ПОТЕРЯЕТЕ ВСЕ ВАШИ БИТКОЙНЫ" should be "ПОТЕРЯЕТЕ ВСЕ ВАШИ ЛАЙТКОИНЫ"
https://github.com/litecoin-project/litecoin/blob/82cacfef8100809ad950b48a01db98e52a6f6877/src/qt/locale/bitcoin_ru_RU.ts#L172

"Введите биткоин-адрес" should be "Введите лайткоин-адрес"
https://github.com/litecoin-project/litecoin/blob/82cacfef8100809ad950b48a01db98e52a6f6877/src/qt/locale/bitcoin_ru_RU.ts#L914

**Comment by thrasher-** [comment]
Thanks for reporting this!

**Comment by thrasher-** [comment]
Fixed in https://github.com/litecoin-project/litecoin/commit/b230514b362f0edd4714def56fb5ff3e9774900e
