### ISSUE TITLE
litecoin-qt startup hang

### ISSUE THREAD

**Issue by rpodgorny** [litecoin-project/litecoin#578]
litecoin-qt seems to be hit by the same qt/ssl bug as the original bitcoin-qt.

see https://github.com/bitcoin/bitcoin/issues/14359 for all the information needed to analyze and fix it.

cheers, R.

**Comment by thrasher-** [comment]
Thanks, a fix has been merged into master via: https://github.com/litecoin-project/litecoin/commit/10753d669ddd2c2d2c22a2b99de4159b0992ff8d
