### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Thanoos** [litecoin-project/litecoin#587]
rm: cannot remove '.libs/libunivalue.a': Permission denied
rm: cannot remove '.libs/libunivalue.la': Permission denied
rm: cannot remove '.libs/libunivalue.lai': Permission denied
ar: `u' modifier ignored since `D' is the default (see `U')
ar: could not create temporary file whilst writing archive: No more archived files
Makefile:744: recipe for target 'libunivalue.la' failed
make[3]: *** [libunivalue.la] Error 1
make[3]: Leaving directory '/home/thanoose/awpcoin/src/univalue'
Makefile:9848: recipe for target 'univalue/libunivalue.la' failed
make[2]: *** [univalue/libunivalue.la] Error 2
make[2]: Leaving directory '/home/thanoose/awpcoin/src'
Makefile:9344: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/thanoose/awpcoin/src'
Makefile:741: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by JohnnyLoathe** [comment]
Simple permission error.
Change permissions for the cloned folder and contents.

**Comment by thrasher-** [comment]
Please follow @JohnnyLoathe's advice as it is related to file permissions.

**Comment by Thanoos** [comment]
Many Thanks
can you help me out with this error
litecoincoin-qt: chainparams.cpp:231: CTestNetParams::CTestNetParams(): Assertion `consensus.hashGenesisBlock == uint256S("0xd686c51a8ba8b81e4173096785e458253105e1a4d637fd7824893cd2691ee71f")' failed.
Aborted (core dumped)

**Comment by JohnnyLoathe** [comment]
Your making your own coin and don't know what your doing.
This is for Litecoin related issues only.

**Comment by losh11** [comment]
As someone else said then deleted, you are trying to build your own coin... 

No offence but if you're not able to work out how to create a genesis block... you probably shouldn't be creating a cryptocurrency. We don't offer support for forked coins here.
