### ISSUE TITLE
Litecoind cli rpcport option is ignored

### ISSUE THREAD

**Issue by ksemaev** [litecoin-project/litecoin#596]
Litecoind version is `0.16.3` and none of the rpc options combinations help me to make it use custom port.
Even trying simple `litecoind -rpcport=8232 -printtoconsole` still gives me this in log:
```  2019-06-02 08:31:27 Bound to [::]:9333
2019-06-02 08:31:27 Bound to 0.0.0.0:9333
```

Is there anyt reason for that? I tried adding `rpcallowip`, `server` , `rpcbind` and many others - nothing seems to work

**Comment by ksemaev** [comment]
tried `0.17.2` the same result

**Comment by ksemaev** [comment]
the same issue that this one, closed for some reason: https://github.com/litecoin-project/litecoin/issues/351

**Comment by ksemaev** [comment]
another weird thing is: wheb you specify 9333 as rpcport, you receive 
```Error: Unable to bind to 0.0.0.0:9333 on this computer. Litecoin Core is probably already running.```

So the only way I could make it work is specify any non-9333 port, which it ignores and starts using 9333 as rpc port. This is very wrong

**Comment by ksemaev** [comment]
@losh11 maybe you can advice?

**Comment by ksemaev** [comment]
also I see that when I specify custom port only it uses 2 ports as rpc: custom and 9333

**Comment by thrasher-** [comment]
9333 is the server port, if you wish to adjust that use `litecoind -port=12345`. If you wish to adjust the rpcport, then `-rpcport=9332` is the correct command.

2019-09-03T06:54:22Z Bound to [::]:12345
2019-09-03T06:54:22Z torcontrol thread start
2019-09-03T06:54:22Z Bound to 0.0.0.0:12345
