### ISSUE TITLE
cpuminer  not working properlly on Litecoin regtest

### ISSUE THREAD

**Issue by salmanfarisk** [litecoin-project/litecoin#597]
Hi...

I just run litecoin-qt 0.17.1 in retest  network on ubuntu. I setup a cpuminer on the same system. cpuminer is mine perfectly. 
My cpuminer stating command is
`./cpuminer -a scrypt -o http://localhost:5005/ --userpass=someuser:somepass --debug --coinbase-addr=Lc7xuQRxWaCzJRbeZdrf9BAiU6yNgYZTRX -t 4 --no-getwork  --no-longpoll --no-redirect -s 2 `

But it is not confirming or mining the transaction on the regtest network. The transaction status is shown as `Status: 0/unconfirmed, in memory pool` . I thing this problem is related to segwit activation. I don't know more about the segwit. 

The litecoin.conf file is

`rpcuser=someuser

 rpcpassword=somepass

 rpcallowip=127.0.0.1

 listen=1

 server=1

 daemon=1

  rpcport=5005

 addnode=192.168.11.22

 txindex=1

 keypool=10000`

Have any configuration is need to mine the all the transaction on my regtest network. ...????

Thankyou...

**Comment by farsider350** [comment]
Why don't you just use 'generate 1' in console if cup mining?

**Comment by salmanfarisk** [comment]
The 'generate 1' is working. But I need to setup the mining in automation way.

**Comment by farsider350** [comment]
Batch file for CPU mining

@echo off
echo. Litecoin mining Now ... Please Wait ...
@echo off
for /l  %%x in (1, 1, 999) do (
echo %%x
litecoin-cli.exe generatetoaddress 1 AddressHere 
echo Litecoin %%x
)

**Comment by farsider350** [comment]
If you insist on using the cpuminer. Change localhost to the actual ip. ie.127.0.0.1

**Comment by salmanfarisk** [comment]
@farsider350 Actually there is no problem is to using cpuminer. It is do mining continuously. But the problem is on transaction. If I transfer some coin from one node to another, then that transaction is not adding to the block (That is not confirming). I add proper fee for every transaction. But it is not adding any single block that mine by cpuminer. I don't understand why the transaction is not adding to block. I do mining many time. But transactions is still unconfirmed.

**Comment by salmanfarisk** [comment]
Need any configuration changes???
