### ISSUE TITLE
Alert tests fail, needs new alert data

### ISSUE THREAD

**Issue by keo** [litecoin-project/litecoin#60]
Hi!

I cloned master-0.8 and ran the build. The homebrew version of the osx makefile had an error, will send a pull request for that separately.

Running the tests fails, see below:

OpenSSL 1.0.1e, Homebrew patch, OS X 10.8.latest

```
$ make -f makefile.osx test
/bin/sh ../share/genbuild.sh obj/build.h
./test_litecoin
Running 95 test cases...
test/alert_tests.cpp:173: error in "AlertNotify": check r.size() == 4u failed [1 != 4]
test/alert_tests.cpp:174: error in "AlertNotify": check r[0] == "Alert 1" failed [Evil Alert; /bin/ls; echo  != Alert 1]
unknown location:0: fatal error in "AlertNotify": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000000)
test/alert_tests.cpp:175: last checkpoint

*** 3 failures detected in test suite "Litecoin Test Suite"
make: *** [test] Error 201
```

Unfortunately I don't know enough of this code to help here, just submitting it.

**Comment by Alkaris** [comment]
no solution or just complete dead silence on how to fix this issue?

**Comment by coblee** [comment]
We fixed it by creating correct alert data. But since alert system is no longer active, this is moot.
