### ISSUE TITLE
Futurebit 2 bfgminer write error

### ISSUE THREAD

**Issue by ranjo2721762** [litecoin-project/litecoin#605]
Hi my bfgminer suddenly says FutureBit Write Error: No space left on device. I have two futurebit2 moonlanders in my pc win10 they were mining then this problem came up. I looked up sources from the internet but no answer. Can anyone help me?
![bfgminer](https://user-images.githubusercontent.com/53713467/62430547-a847e600-b6b9-11e9-821c-9813e2253fc6.jpg)

**Comment by FaysalM** [comment]
You probably want to contact the device manufacturer for this.

**Comment by vova557** [comment]
здравствуйте , я разработчик лайткоина как я могу получить деньги за работу

**Comment by Gr0sT0ny0** [comment]
Hi ! I have the same problem
