### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by Xyd94TeUEbg7qi3prH3ttULmwc7mfUwrxCMphPX** [litecoin-project/litecoin#615]
Is there a **faucet** that works for **Litecoin Core testnet** ?

**Comment by losh11** [comment]
This is the one that works for me: https://tltc.bitaps.com
We'll be refilling the one at http://testnet.litecointools.com soon.

**Comment by Xyd94TeUEbg7qi3prH3ttULmwc7mfUwrxCMphPX** [comment]
Thank you ! @losh11
