### ISSUE TITLE
Consensus issue disclosure

### ISSUE THREAD

**Issue by ChillingSilence** [litecoin-project/litecoin#619]
Hi Team,

Just wanting to discuss the desired responsible way to disclose a potential consensus issue I've noticed which could affect a small portion of the Litecoin network (~10-20%). Is there an email for somebody from the Litecoin Foundation or other developer I should lodge this with in private? What's your preferred method for disclosure?

Kind regards

Josiah

**Comment by FaysalM** [comment]
Were you able to contact anyone for this? Best bets are to contact @wangxinxi via telegram or #litecoin on irc (freenode). 
Some other methods: contact@litecoin.org

**Comment by ChillingSilence** [comment]
Been trying to get a bit more information together, hadn't been able to find anybody. I'll give that a whirl, thank you for the response @FaysalM
