### ISSUE TITLE
Virus/Trojan Aleart? 

### ISSUE THREAD

**Issue by Diamondog** [litecoin-project/litecoin#623]
I wanted to download Litecoin core and got this message when trying to go to the site to download it:

![image](https://user-images.githubusercontent.com/14934423/69009900-18584000-0928-11ea-991d-fc16484c72f3.png)

Whats going on?

**Comment by losh11** [comment]
Some anti virus software often gives out false positives, as some malware
install mining software in the background. As you may know, Litecoin Core
does include software which will let you mine (albeit only on CPU).

You should report to McAfee that this is not malicious. Then you should
probably uninstall McAfee, as I don’t understand why anyone would pay to
use anything other than Windows Defender on Windows 10.

**Comment by ltfschoen** [comment]
I got a similar alert on an old macOS when checking the latest version 1.18.1 <img width="621" alt="Screenshot 2020-06-30 at 1 36 09 pm" src="https://user-images.githubusercontent.com/6226175/86122338-f89d1300-bad7-11ea-9507-d9ce1821c763.png">

**Comment by losh11** [comment]
So this is likely a false positive.
As mentioned previously Litecoin Core contains code which lets you
'generate [blocks] to an address'.
And Avast doesn't realise Litecoin Core isn't mining for malicious reasons.
So you'd have to mark this as a false positive and report it to Avast.

**Comment by ltfschoen** [comment]
Yes, Avast was so annoying I ended up just uninstalling it.
It gave me all the same alerts when I tried to install Dash Core too.
Is it possible to collaborate with antivirus software providers so they don't scare off new users?

**Comment by losh11** [comment]
Looks like you contact them through here:
https://www.avast.com/en-gb/false-positive-file-form.php

**Comment by ltfschoen** [comment]
Thanks I created a report

<img width="927" alt="Screenshot 2020-06-30 at 3 04 01 pm" src="https://user-images.githubusercontent.com/6226175/86129585-394e5980-bae3-11ea-8bbb-7f894b6806c1.png">

<img width="1165" alt="Screenshot 2020-06-30 at 3 04 39 pm" src="https://user-images.githubusercontent.com/6226175/86129599-3ce1e080-bae3-11ea-957e-f32d24d5068c.png">

**Comment by ltfschoen** [comment]
They asked me to upload the file to the security community here https://www.virustotal.com/gui/home/upload, but it's a binary file and I can't tell if it contains any sensitive personal information (e.g. litecoin-project/litecoin/src/litecoin_cli-bitcoin-cli.o)
