### ISSUE TITLE
./litecoin-qt: error while loading shared libraries

### ISSUE THREAD

**Issue by Jiankun-Huang** [litecoin-project/litecoin#631]
Hi, I am getting this error every time I run ./litecoin-qt. I am using Unbuntu 18.4 litecoin 0.13 source.
### ./litecoin-qt: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory Thanks

**Comment by thrasher-** [comment]
You'll need to make sure that you have all the depends installed: https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md#dependencies

The particular one you're missing is libboost_system and the current version supported is 0.17x
