### ISSUE TITLE
compilation failure (std::deque?)

### ISSUE THREAD

**Issue by rpodgorny** [litecoin-project/litecoin#632]
compilation on latest arch linux now fails for me:

Making all in src
make[1]: Entering directory '/home/radek/tmp/build/litecoin-qt/src/litecoin-0.17.1/src'
make[2]: Entering directory '/home/radek/tmp/build/litecoin-qt/src/litecoin-0.17.1/src'
  CXX      litecoind-bitcoind.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-merkleblock.o
httpserver.cpp:74:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   74 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:33:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
   32 | #include <support/events.h>
  +++ |+#include <deque>
   33 | 
httpserver.cpp: In member function ‘bool WorkQueue<WorkItem>::Enqueue(WorkItem*)’:
httpserver.cpp:92:13: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   92 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:95:9: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
   95 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function ‘void WorkQueue<WorkItem>::Run()’:
httpserver.cpp:106:35: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  106 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:110:31: error: ‘queue’ was not declared in this scope; did you mean ‘Enqueue’?
  110 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
make[2]: *** [Makefile:6346: libbitcoin_server_a-httpserver.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/radek/tmp/build/litecoin-qt/src/litecoin-0.17.1/src'
make[1]: *** [Makefile:10510: all-recursive] Error 1
make[1]: Leaving directory '/home/radek/tmp/build/litecoin-qt/src/litecoin-0.17.1/src'
make: *** [Makefile:774: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by rpodgorny** [comment]
https://aur.archlinux.org/packages/litecoin-qt/

Quick fix:
add
#include <deque>
at line 33 in httpserver.cpp

**Comment by losh11** [comment]
Does building bitcoin-qt 0.17.1 also fail for you?

**Comment by rpodgorny** [comment]
yes. with the very same error.
if you need some versions info, just let me know...

**Comment by rpodgorny** [comment]
just fyi - bitcoin master compiles fine for me (is it 0.19.something?) -> maybe you should merge upstream changes as well...

**Comment by losh11** [comment]
Can you try building from`litecoin/0.18` branch? `0.18.x` will be the next release of Litecoin Core. Currently it's in internal testing before we tag it as a release candidate.

**Comment by rpodgorny** [comment]
0.18 branch fails just as 0.17 does (same error)

**Comment by rpodgorny** [comment]
in bitcoin repo:

git show a592913022

commit a5929130223973636f3fd25fbfaf2953f2ec96a9
Author: Jan Beich <jbeich@FreeBSD.org>
Date:   Fri Oct 25 13:05:17 2019 +0000

    http: add missing header bootlegged by boost < 1.72
    
    httpserver.cpp:74:10: error: no template named 'deque' in namespace 'std'
        std::deque<std::unique_ptr<WorkItem>> queue;
        ~~~~~^

diff --git a/src/httpserver.cpp b/src/httpserver.cpp
index 811377718..d9c711332 100644
--- a/src/httpserver.cpp
+++ b/src/httpserver.cpp
@@ -15,6 +15,7 @@
 #include <sync.h>
 #include <ui_interface.h>
 
+#include <deque>
 #include <memory>
 #include <stdio.h>
 #include <stdlib.h>

**Comment by rpodgorny** [comment]
...any progress on this? the fix is pretty simple... ;-)

**Comment by thrasher-** [comment]
Included in 0.18 https://github.com/litecoin-project/litecoin/commit/ba8a8c46b3e929d118b57e30fe38cc48bd309557

**Comment by c4pt000** [comment]
> +#include

why didn't you just write that shit?

#include <deque>

**Comment by yoyofreeman** [comment]
+ #include <deque>
