### ISSUE TITLE
Rebuld Error Nothing to be done for 'all-am'. Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by imskaaz** [litecoin-project/litecoin#635]
I trying build for making my own cryptocurrency using litecoin  0.15

Ubuntu Linux LTS 18.04
Ram 8
Disk 300

```
GEN      qt/test/moc_addressbooktests.cpp
  CXX      qt/test/qt_test_test_pigycoin_qt-moc_addressbooktests.o
  GEN      qt/test/moc_paymentservertests.cpp
  CXX      qt/test/qt_test_test_pigycoin_qt-moc_paymentservertests.o
  GEN      qt/test/moc_wallettests.cpp
  CXX      qt/test/qt_test_test_pigycoin_qt-moc_wallettests.o
  CXXLD    qt/test/test_pigycoin-qt
  CXX      test/test_test_pigycoin_fuzzy-test_pigycoin_fuzzy.o
  CXXLD    test/test_pigycoin_fuzzy
make[2]: Leaving directory '/root/Desktop/pigycoin/src'
make[1]: Leaving directory '/root/Desktop/pigycoin/src'
Making all in doc/man
make[1]: Entering directory '/root/Desktop/pigycoin/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/Desktop/pigycoin/doc/man'
make[1]: Entering directory '/root/Desktop/pigycoin'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/Desktop/pigycoin'
```
Ayone can help me with this ?

What i do / What i modif ?

I just do renaming the file
and do

```
./autogen.sh
```
```
./configure
```
```
make
```

**Comment by vova557** [comment]
Hello something I do not see that we are talking about cryptocurrency it's about the Director's rights to the desktop 21.02.2020, 07:45, "imskaaz" <notifications@github.com>:I trying build for making my own cryptocurrency using litecoin 0.15Ubuntu Linux LTS 18.04Ram 8Disk 300GEN qt/test/moc_addressbooktests.cpp
  CXX qt/test/qt_test_test_pigycoin_qt-moc_addressbooktests.o
  GEN qt/test/moc_paymentservertests.cpp
  CXX qt/test/qt_test_test_pigycoin_qt-moc_paymentservertests.o
  GEN qt/test/moc_wallettests.cpp
  CXX qt/test/qt_test_test_pigycoin_qt-moc_wallettests.o
  CXXLD qt/test/test_pigycoin-qt
  CXX test/test_test_pigycoin_fuzzy-test_pigycoin_fuzzy.o
  CXXLD test/test_pigycoin_fuzzy
make[2]: Leaving directory '/root/Desktop/pigycoin/src'
make[1]: Leaving directory '/root/Desktop/pigycoin/src'
Making all in doc/man
make[1]: Entering directory '/root/Desktop/pigycoin/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/Desktop/pigycoin/doc/man'
make[1]: Entering directory '/root/Desktop/pigycoin'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/Desktop/pigycoin'
Ayone can help me with this ?What i do / What i modif ?I just do renaming the fileand do./autogen.sh
./configure
make

**Comment by losh11** [comment]
Hi, we do not offer support for building your own cryptocurrency in the Litecoin Issue tracker.

**Comment by vova557** [comment]
losh11 подскажите я разработчик лайткоин но почему мне не платят прошу разобраться21.02.2020, 08:45, "Loshan T" <notifications@github.com>:Closed #635.

**Comment by imskaaz** [comment]
when i dont make any change, i got same problem

**Comment by adamantcoders** [comment]
That's not an error. Source code is compiled successfully. Check src/ folder, you'll find daemon files
