### ISSUE TITLE
rpcRunLater race in walletpassphrase

### ISSUE THREAD

**Issue by kryvel** [litecoin-project/litecoin#644]
Hi,
I encountered with deadlock on concurrent walletpassphrase rpc call in bitcoin wallet. The same behavior in litecoin too.
Here is a description of the issue https://github.com/bitcoin/bitcoin/issues/18482

Could you please backport the fix to litecoin ?

**Comment by kryvel** [comment]
Hello,
This is high severity issue, because it totally lock daemon and all interaction with them.

**Comment by kryvel** [comment]
Is litecoin still alive ? :)

**Comment by losh11** [comment]
This issue is fixed in 0.18 which is being released soon.

**Comment by kryvel** [comment]
Great, nice to hear that!
Where could I find commit or PR? 
I saw last commit was in late December 2019...

**Comment by losh11** [comment]
@kryvel in the 0.18 branch. fixed in commit #703dcfe
