### ISSUE TITLE
Need help: sent litecoin to p2sh bitcoin address

### ISSUE THREAD

**Issue by cloudever** [litecoin-project/litecoin#651]
Hi everyone!

I accidentaly sent litecoin to my bitcoin address starts with `3`. Fortunately, I have a private key of that bitcoin address and able to retrieve a private key for litecoin network.

Where can I find an util that will help me retrieve coins from litecoin network by conversion of private key between networks?

**Comment by losh11** [comment]
Hi Pavel,

I’ve actually created a script for people with this issue. Download the
script:
https://gist.github.com/losh11/c8eb4a33a20218d4426c030c6a033625

Use python to run it, and it should be able to convert a bitcoin WIF to a
Litecoin WIF.

**Comment by cloudever** [comment]
@losh11 Thank you very much! I've got a litecoin successfully!
