### ISSUE TITLE
Couldn't get free coin on testnet faucet 

### ISSUE THREAD

**Issue by khaninejad** [litecoin-project/litecoin#653]
Hi,

I wanted to get free coin to test LITECOIN TESTNET and tried many faucet but no luck.
http://testnet.litecointools.com/
https://tltc.bitaps.com/
http://testnet.thrasher.io/
received:
RESPONSE:
{
    "code": -4
}
and 
RESPONSE:
{
    "code": -6
}

**Comment by losh11** [comment]
Hi @khaninejad  in the future we'd appreciate if you'd asking this question on something like the Litecoin Reddit or IRC. Faucet related questions aren't strictly related to the Litecoin Core source.

Anyways, here's a testnet faucet that should be working: https://testnet-faucet.com/ltc-testnet/
