### ISSUE TITLE
configure: error: libdb_cxx headers missing, Litecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

### ISSUE THREAD

**Issue by throwawat99** [litecoin-project/litecoin#656]
After running ./configure I am getting the above error
"configure: error: libdb_cxx headers missing, Litecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)"

For it to build

Branch 0.15, cloned from github

Ubuntu 20.04

I have tried using --with-incomatible-bdb to no effect

**Comment by throwawat99** [comment]
Anyone got any ideas?

**Comment by farsider350** [comment]
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

**Comment by throwawat99** [comment]
Found a solution since the above packages arent available:
https://cryptoandcoffee.com/mining-gems/install-berkeley-4-8-db-libs-on-ubuntu-16-04/
followed by
https://www.fsanmartin.co/compiling-berkeley-db-4-8-30-in-ubuntu-19/
