### ISSUE TITLE
error: unable to rename temporary 'libbitcoin_common_a-coins-592de513.o.tmp' to output file 'libbitcoin_common_a-coins.o': 'No such file or directory'

### ISSUE THREAD

**Issue by ltfschoen** [litecoin-project/litecoin#657]
Running the `make` command when following the instructions to build from source using the latest 'master' branch https://github.com/litecoin-project/litecoin/blob/v0.18.1/doc/build-osx.md fails with error.

I expected `make` not to crash

I tried to build from source following these instructions: https://github.com/litecoin-project/litecoin/blob/v0.18.1/doc/build-osx.md. I ran the following commands:

```
xcode-select --install
brew install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode
brew install librsvg
git clone https://github.com/litecoin-project/litecoin
cd litecoin
./contrib/install_db4.sh .
./autogen.sh
./configure
make
```

But running `make` crashed with error:
```
...
  AR       libbitcoin_wallet.a
  CXX      libbitcoin_common_a-base58.o
  CXX      libbitcoin_common_a-bech32.o
  CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
error: unable to rename temporary 'libbitcoin_common_a-coins-592de513.o.tmp' to output file
      'libbitcoin_common_a-coins.o': 'No such file or directory'
1 error generated.
make[2]: *** [libbitcoin_common_a-coins.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Run terminal on macOS Mojave 10.14.6 and following the build instructions

I cloned the latest 'master' branch, as suggested in the instructions to build from source

macOS Mojave 10.14.6, 2.2 GHz Intel Core i7, 16 GB RAM, SSD, 24Gb free space

**Comment by ltfschoen** [comment]
I tried updating dependencies with `brew upgrade ...` and building from tag v0.18.1 (instead of 'master' branch) by following these steps
```
xcode-select --install
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
brew install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode
brew upgrade automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode
brew install librsvg
brew upgrade librsvg
git clone https://github.com/litecoin-project/litecoin
cd litecoin
git checkout v0.18.1
./contrib/install_db4.sh .
./autogen.sh
./configure
make
```

But running `make` still fails:
```
~/code/litecoin-project/litecoin - [(HEAD detached at v0.18.1)] $ make
Making all in src
  CXX      libbitcoin_common_a-coins.o
error: unable to rename temporary 'libbitcoin_common_a-coins-9300c5d0.o.tmp' to output file
      'libbitcoin_common_a-coins.o': 'No such file or directory'
1 error generated.
make[2]: *** [libbitcoin_common_a-coins.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

```

**Comment by ltfschoen** [comment]
the error was caused because Avast antivirus had moved the temp file to its virus chest

<img width="620" alt="Screenshot 2020-06-30 at 2 12 38 pm" src="https://user-images.githubusercontent.com/6226175/86124689-d1e0db80-badb-11ea-9ee5-7fb54c05f3a6.png">

**Comment by losh11** [comment]
Thank you @ltfschoen. This will make it easier for people building Litecoin Core on macOS with Avast.
I'm gonna assume it's safe to close this issue?

**Comment by ltfschoen** [comment]
So I restored all the files using Avast so they weren't locked.

<img width="996" alt="Screenshot 2020-06-30 at 2 24 03 pm" src="https://user-images.githubusercontent.com/6226175/86126746-1fab1300-badf-11ea-9f77-d5d5143ced2a.png">

**Comment by ltfschoen** [comment]
But when I ran `make` again, it gave the following error

```
  CXX      qt/libbitcoinqt_a-trafficgraphwidget.o
qt/trafficgraphwidget.cpp:55:13: error: member access into incomplete type 'QPainterPath'
        path.moveTo(x, YMARGIN + h);
            ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:59:17: error: member access into incomplete type 'QPainterPath'
            path.lineTo(x, y);
                ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:61:13: error: member access into incomplete type 'QPainterPath'
        path.lineTo(x, YMARGIN + h);
            ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:108:22: error: variable has incomplete type 'QPainterPath'
        QPainterPath p;
                     ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
qt/trafficgraphwidget.cpp:115:22: error: variable has incomplete type 'QPainterPath'
        QPainterPath p;
                     ^
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: forward declaration of 'QPainterPath'
class QPainterPath;
      ^
5 errors generated.
make[2]: *** [qt/libbitcoinqt_a-trafficgraphwidget.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

```

**Comment by ltfschoen** [comment]
so I tried just running the litecoin-0.18.1-osx.dmg that i'd downloaded, I dragged the executable into the Applications/ folder and ran it, but it displayed the following error (it might be due to a conflict as a result of me having also tried installing that version 0.18.1 from source?)

<img width="418" alt="Screenshot 2020-06-30 at 3 16 13 pm" src="https://user-images.githubusercontent.com/6226175/86131379-e1fdb880-bae5-11ea-9f97-3d237dc09f68.png">


so then i tried using an older version v0.17.1 from https://download.litecoin.org/litecoin-0.17.1/, i verified checksums matched as follows, and that version  v0.17.1 installed successfully

```
cat SHA256SUMS.asc
shasum -a 256 https://download.litecoin.org/litecoin-0.17.1/osx/litecoin-0.17.1-osx.dmg
```
