### ISSUE TITLE
hard fork question

### ISSUE THREAD

**Issue by bsbinternaltesting** [litecoin-project/litecoin#669]
hello sir i have one question regarding litecoin fork from past 4 day im trying to search about one of my question but still im not able to fine can anyone help me to solve that ?
Question im trying to hark fork litecoin in which my coin name will be new and address prefix also but i want to use same network like if i fork litecoin and give name ABC and user who have coin in litecoin ledger will have coin in ABC new coin fork is that possible ?

**Comment by cheezcharmer** [comment]
bump

**Comment by losh11** [comment]
Hi, we do not offer support for software unrelated to Litecoin.
