### ISSUE TITLE
[Bug] QR Code in Request Payment includes prefix: "litecoin:"

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-project/litecoin#675]
## Description
When scanning an address via QR code, the decoded string includes the address and prefix which makes the scanner throw an error.  

## Expectation
When scanning an address via QR code, only the address should be encoded to the scanning device.

expected address:  `ltc1hfehae23....` actual  `litecoin:ltc1hfehae23....`

## Actual Behavior
The decoded string includes the address and prefix which makes the scanner throw an error.  
- [ ] Reliabilty: This happens every time
- [ ] Litecoin Core version: v0.18.1
- [ ] Source: macOS pkg from litecoin.org website
- [ ] HW Env: MBP 16in, macOS Catalina 
 
## Screenshot

|Error View|
|----------|
|![Screen Shot 2020-10-23 at 1 34 16 PM](https://user-images.githubusercontent.com/2899463/97005073-d3745a80-1535-11eb-8e0c-f654867c1fd6.png)|

**Comment by losh11** [comment]
Core generates a Litecoin URI which may in certain situations include an amount & description. Wallets are recommended to be compatible with this URI scheme.

**Comment by losh11** [comment]
Closing: expected behaviour (litecoin uri scheme).
