### ISSUE TITLE
Make Deploy fails on Catalina

### ISSUE THREAD

**Issue by blockinator** [litecoin-project/litecoin#678]
Make Deploy fails when compiling on MacOS Catalina (v10.15.7).
Error:
```
Error: Could not parse fancy disk image plist at "./contrib/macdeploy/fancy.plist"
make: *** [Litecoin-Core.dmg] Error 1
```

I installed the following dependencies:
```
brew install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf python qt libevent qrencode librsvg
```

**Comment by volbil** [comment]
Fix https://github.com/bitcoin/bitcoin/commit/04a69c200e0d18ae63c7e47898f85d1b4cb5c23d#diff-678e6cc67aa7fc8e7c7d0964993502b14062606794af10874a7feee4aaec3f32

**Comment by losh11** [comment]
Are you able to backport this to litecoin 0.18?
