### ISSUE TITLE
License violation spotted - another project stole your code

### ISSUE THREAD

**Issue by littleskunk** [litecoin-project/litecoin#680]
The project, https://github.com/platincoin-project/platincoin , copied your code and removed your copyright notice. Please report this to GitHub to takedown the violating repository.

Let me know if you need any proof. I can point you to some code lines that will show the origin. The code was copied somewhere in 2017 - early 2018.

The reason why I believe this takedown is important is that this project is harming the open-source community. In some countries, they are as famous as BitConnect and they might take the same ending including some media reports that might contain the origin of this project. It would be awesome if you could make a statement from your side just to make it clear what the open-source community stands for. I would bet the media will love to quote you.

If my understanding of a license violation is incorrect I would also love to learn more about it. So you can help me one way or the other :D

**Comment by RedCuckoo** [comment]
But they kept the original license, didn't they?

https://github.com/platincoin-project/platincoin/blob/master/COPYING
