### ISSUE TITLE
Qt 5.15 warnings

### ISSUE THREAD

**Issue by broros** [litecoin-project/litecoin#691]
getting lots of warnings related to qt 5.15 on osx

'''
warning: 'width' is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
warning: 'mapped' is deprecated: Use QSignalMapper::mappedInt(int) instead [-Wdeprecated-declarations]
'''

**Comment by DumbGameMaker** [comment]
duplicate of #689
