### ISSUE TITLE
make -f makefile.unix not working

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [litecoin-project/litecoin#705]
An .exe file should be created.

![image](https://user-images.githubusercontent.com/77284265/113411843-b8442b80-93ae-11eb-82a7-1f0f25ccd31e.png)

Download the litecoin source code, cd into the folder, cd into src and type into terminal:
make -f makefile.unix

Earliest version, forked through github.

Ubuntu Virtual Machine

**Comment by TheAwesomeGuy47** [comment]
Also I believe I do not have the "db_css.h" file.

**Comment by thrasher-** [comment]
You're missing the Berkeley DB header files. Furthermore, we haven't used the makefile.unix file for several releases. Can follow the instructions here: https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md#berkeley-db
