### ISSUE TITLE
Taproot-Schnorr softfork

### ISSUE THREAD

**Issue by jonathancross** [litecoin-project/litecoin#713]
Now that Bitcoin Core v0.21.1 has been released and miners can begin signaling support for Taproot, it would be great to consider if / when Litecoin will consider supporting such a softfork.

**Comment by losh11** [comment]
Litecoin will support Taproot. The next release of Litecoin Core is likely 0.21.1 (including taproot activation code).

**Comment by DaCryptoRaccoon** [comment]
This won't end well.
