### ISSUE TITLE
Litecoin with Lightning network 

### ISSUE THREAD

**Issue by BioDownload** [litecoin-project/litecoin#724]
Would be cool to have a fast lightning network for instant transactions for mobile and desktop wallet so that sending and recieving payments could be faster for coffee or payment tickets.

Thanks

**Comment by vae520283995** [comment]
same

**Comment by losh11** [comment]
Closing due to unrelated to Litecoin Core development. Lightning Network for Litecoin does exist. Please check out the @ltcsuite organisation on GitHub.
