### ISSUE TITLE
Update download link for QT 5.9.7 in qt.mk inside depends/packages

### ISSUE THREAD

**Issue by biocarecoin** [litecoin-project/litecoin#727]
The link in the qt.mk file inside packages/depends folder gives 404

please update the link to  : https://download.qt.io/archive/qt/5.9/5.9.7/submodules/ 

instead of 

https://download.qt.io/official_releases/qt/5.9/5.9.7/submodules/

**Comment by Jolly-Pirate** [comment]
Already reported the issue with a pull request of the solution https://github.com/litecoin-project/litecoin/issues/721
