### ISSUE TITLE
download.litecoin.org has ssl protocol error. Downloads not possible with Chrome + Firefox

### ISSUE THREAD

**Issue by marcelser** [litecoin-project/litecoin#730]
Hi,

Just tried to download the wallet from litecoin.org with chrome but when I try to download the download button redirects me to download.litecoin.org and there I just receive a "SSL protocol error". Also tried Firefox and there I get also an SSL error telling me "SSL_ERROR_RX_RECORD_TOO_LONG".

Please fix your ssl issues on download.litecoin.org. No one can trust a wallet where the download server has SSL issues.

Thank you

Marc

**Comment by losh11** [comment]
I am using Google Chrome v90.0.4430.212 (x86) for macOS & Firefox v88.0.1 (x86) for macOS. I am unable to reproduce this issue. For example visiting the url `https://download.litecoin.org/litecoin-0.18.1/osx/` does not display any SSL errors. Attempting to download a v18 binary does not show this either. Can you share a screenshot of what you see when you visit the above link?

**Comment by thrasher-** [comment]
Any update @marcelser ?

**Comment by marcelser** [comment]
Seems to be resolved now. When I click on the download button on "litecoin.org" I get a proper download window in chrome.
