### ISSUE TITLE
litecoin 0.18 as an altcoin, in ubuntu 20.4 TLS. VM in Boxes.

### ISSUE THREAD

**Issue by ronaldopadula** [litecoin-project/litecoin#732]
I used litecoin to create an altcoin named rpocoin. To be used as teaching material in class. But, I have the following error:

root@rpocoin-base:/home/rpocoin/Desktop/rpocoin# make
Making install in src
make[1]: Entering directory '/home/rpocoin/Desktop/rpocoin/src'
make[2]: Entering directory '/home/rpocoin/Desktop/rpocoin/src'
make[3]: Entering directory '/home/rpocoin/Desktop/rpocoin'
make[3]: Leaving directory '/home/rpocoin/Desktop/rpocoin'
make[2]: *** No rule to make target 'qt/res/icons/rpocoin_splash.png', needed by 'qt/qrc_bitcoin.cpp'.  Stop.
make[2]: Leaving directory '/home/rpocoin/Desktop/rpocoin/src'
make[1]: *** [Makefile:13079: install-recursive] Error 1
make[1]: Leaving directory '/home/rpocoin/Desktop/rpocoin/src'
make: *** [Makefile:776: install-recursive] Error 1

I need a help.

**Comment by losh11** [comment]
Unrelated to Litecoin Core.
