### ISSUE TITLE
Testnet DNS seeds are down

### ISSUE THREAD

**Issue by lwebbz** [litecoin-project/litecoin#741]
I've been trying to connect to the hard coded DNS seeds  testnet-seed.litecointools.com, seed-b.litecoin.loshan.co.uk  dnsseed-testnet.thrasher.io and I'm not receiving the addresses of any peers. I think they might be offline at the moment, please could you reactivate them?

**Comment by SomethingUseful** [comment]
my testnet4 node stopped syncing yesterday. 

Loading addresses from DNS seeds (could take a while)
0 addresses found from DNS seeds
Adding fixed seed nodes as DNS doesn't seem to be available.

is testnet4 dead?

**Comment by SomethingUseful** [comment]
I deleted peers.dat and ran -reindex seems like its resyncing ...

**Comment by lwebbz** [comment]
Yeah I can confirm that yesterday the testnet Blockchain stopped producing blocks,  the current block height is 2018015 with the last block being mined 18 hours ago. Kinda annoying been working great for me before then. Maybe the hashpower has fallen significantly?

**Comment by losh11** [comment]
Litecoin testnet is once again mining correctly.
