### ISSUE TITLE
Where can I check the mint program?

### ISSUE THREAD

**Issue by adust09** [litecoin-project/litecoin#746]
I’m going to see if Litecoin really controls the amount of reward per block issued by the block height as per the specification.

It should have a half-life every 840,000 blocks, but the program I’ve spotted appears to have a half-life every 210,000 blocks, just like the Bitcoin from which it forked.

The Github code referenced is https://github.com/litecoin-project/litecoin/blob/v0.18.1/src/validation.cpp#L1154
![image](https://user-images.githubusercontent.com/47593288/132623901-d168a04b-f8ad-4b71-a69e-f91403c1ae4e.png)

Please let me know if I’m wrong or if there are other programs out there.

**Comment by losh11** [comment]
The number of block halvings is determined by:

>int halvings = nHeight / consensusParams.nSubsidyHalvingInterval

Which is current height, divided by a fixed variable `nSubsidyHalvingInterval`. If you got to `chainparams.cpp`, you can see the value of `nSubsidyHalvingInterval` as [840000](https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L66).

I believe you might've just been confused by that comment right? That comment just hadn't been updated correctly, but comments have no effect on code. Will close issue.
