### ISSUE TITLE
What is the theoretical TPS (transaction per second) for Litecoin?

### ISSUE THREAD

**Issue by adust09** [litecoin-project/litecoin#747]
As far as this site is concerned, the current TPS is about 1.56.

https://blockchair.com/litecoin/charts/transactions-per-second

but, The literature here says theoretically 56 TPS, is that true?

If that's true, it's a terrible disconnect from reality.

https://coinmarketcap.com/alexandria/article/litecoin-vs-bitcoin#toc-transactions-per-second

I've read the white paper, etc., but I couldn't find the theoretical TPS clearly, so can someone tell me what it is?

**Comment by losh11** [comment]
This isn't the place to discuss tps, please use LitecoinTalk, Reddit or some other Litecoin discussion lounge.
