### ISSUE TITLE
Transactions are stuck in mempool

### ISSUE THREAD

**Issue by webdev866** [litecoin-project/litecoin#758]
I believe this could be a bug since transactions are stuck within the mempool forever, this is tested by changing the pchMessageStart configuration to prevent collision with the actual litecoin network. Why is it happening even though mining is on.

**Comment by wrapperband** [comment]
What do you mean "prevent collisions with actual   Litecoin network" - are you talking about a fork, or a testnet?

**Comment by webdev866** [comment]
First I used testnet, the issue is that transactions get stuck in there.
Then to make sure I used a fast fork I mined few blocks then tried to test transactions, same result, which means the issue is within the litecoin code. nothing was modified only pchMessageStart that were changed. how can you explain this? Is it a known issue?

**Comment by webdev866** [comment]
Never mind, I figured out the whole issue.

thanks
