### ISSUE TITLE
Security Enhancements for Preventing Two Kinds of Attacks

### ISSUE THREAD

**Issue by CharesFang** [litecoin-project/litecoin#762]
According to [PR#14897](https://github.com/bitcoin/bitcoin/pull/14897) of Bitcoin, the author committed patches to avoid potential attacks that can prevent Bitcoin nodes from getting transactions with others.

> This behavior was described well [here](https://www.cs.umd.edu/projects/coinscope/coinscope.pdf) (page 11).
>
> Per current implementation, if node A receives *INV* (tx) from node B, node A sends *GETDATA* to B and waits for *TX* message back.
>
> Node A is likely to receive more *INVs* (regarding the same tx) from other peers. But node A would not send another *GETDATA* unless it does not hear *TX* back from node B for next 2 minutes (to save bandwidth)
>
> Thus, if B is a malicious node, it can prevent node A from getting the transaction (even if all A’s peers have it) for 2 minutes.
>
> This behavior seems to be an inherent limitation of the current P2P relay protocol, and I don’t see how it can be fundamentally changed (I can see workarounds which involve rewriting a lot of P2P code though).

We checked the `litecoin` code and found the same likely vulnerable code segments in `litecoin/src/net.cpp`,  `litecoin/src/net.h,` and other files. 
Therefore, we strongly suggest that Bitcoin [PR#14897](https://github.com/bitcoin/bitcoin/pull/14897) should be backported promptly for security enhancements. For more details, please refer to the patch commit [1cff3d6c](https://github.com/bitcoin/bitcoin/pull/14897/commits/1cff3d6cb017aea87d16cbda0768bbab256d16da).

Reported by `de957ad9679f28a38f02f00cc7928bce8fb424882ff060a3c09c32895b1474cc`.

**Comment by wrapperband** [comment]
I'd have thought LTC should refactor on the new BTC version each year and bring these fixes in automatically (tested obviously), by now.

**Comment by im95888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CharesFang** [comment]
> I'd have thought LTC should refactor on the new BTC version each year and bring these fixes in automatically (tested obviously), by now.

I'd like to suggest that all the Bitcoin-forked cryptocurrency projects should pay more attention to the security-related issues of Bitcoin, too. We have found many problems inherited from Bitcoin.

**Comment by losh11** [comment]
There is currently a release of Litecoin Core 0.21.1 that will include this
fix, which will go into rc soon.
