### ISSUE TITLE
QT errors when compiling

### ISSUE THREAD

**Issue by mhallager** [litecoin-project/litecoin#765]
Litecoin Core 0.18.1 on Slackware64

**Error messages:**
In file included from /usr/include/qt5/QtGui/qbrush.h:49,
                 from /usr/include/qt5/QtGui/qpalette.h:46,
                 from /usr/include/qt5/QtWidgets/qwidget.h:48,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from ./qt/trafficgraphwidget.h:8,
                 from qt/trafficgraphwidget.cpp:6:
/usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
qt/trafficgraphwidget.cpp: In member function ‘virtual void TrafficGraphWidget::paintEvent(QPaintEvent*)’:
qt/trafficgraphwidget.cpp:108:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  108 |         QPainterPath p;
      |                      ^
qt/trafficgraphwidget.cpp:115:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  115 |         QPainterPath p;
      |                      ^
make[2]: *** [Makefile:8892: qt/qt_libbitcoinqt_a-trafficgraphwidget.o] Error 1
make[2]: Leaving directory '/root/litecoin-slackbuild/litecoin-0.18.1/src'
make[1]: *** [Makefile:12603: all-recursive] Error 1
make[1]: Leaving directory '/root/litecoin-slackbuild/litecoin-0.18.1/src'
make: *** [Makefile:776: all-recursive] Error 1

**Solution:**
The following needs to be added into src/qt/trafficgraphwidget.cpp
`#include <QPainterPath>`

**Comment by losh11** [comment]
This is a known issue whilst building on WSL for Windows, however this change is breaking for non-windows builds. For future reference, Windows users are recommended to build via Gitian through WSL to avoid this error, or include patch themselves.
