### ISSUE TITLE
Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee

### ISSUE THREAD

**Issue by newworld121** [litecoin-project/litecoin#766]

**Comment by newworld121** [comment]
i folked litecoin,and when i try to send some coins.always get this error message

**Comment by farsider350** [comment]
Read what it says mate. Enable fallback fee until you've created enough tx's and blocks for it to estimate itself.

**Comment by newworld121** [comment]
i have enabled fallback fee,but the transaction never be confirmed,and i have created about 20000 blocks,but i can not send any coins

**Comment by farsider350** [comment]
Your probably using segwit addresses before segwit is actually activated. Look into that then get back to me.

**Comment by losh11** [comment]
Closing due to unrelated to Litecoin Core. Please continue discussion on an external forum.

**Comment by newworld121** [comment]
> Your probably using segwit addresses before segwit is actually activated. Look into that then get back to me.
can you contact me on telegram,my id is anticcpcoin
