### ISSUE TITLE
Cant sendcoins: decoded address is of unknown format

### ISSUE THREAD

**Issue by philipp1992** [litecoin-project/litecoin#784]
![image](https://user-images.githubusercontent.com/11994884/158774504-04573ed6-e570-4a24-b1bc-4e08ea647ac7.png)

![image](https://user-images.githubusercontent.com/11994884/158774558-b1b6cbf5-e42e-4230-808f-2fa67335678c.png)

![image](https://user-images.githubusercontent.com/11994884/158774451-668f22bd-26df-484c-a5b7-ca970c41931e.png)

![image](https://user-images.githubusercontent.com/11994884/158774725-5fb2468d-91ad-4643-aa82-981aea980010.png)
![image](https://user-images.githubusercontent.com/11994884/158774919-34599f2d-6dc2-4456-9625-214abeefdba9.png)

**Comment by losh11** [comment]
The Litecoin Foundation maintains our own fork of lnd, called [lndltc](https://github.com/ltcsuite/lnd). The official lnd fork has many issues with litecoin which haven't been fixed yet. We're currently working on rc2, and ironing out any issues before a final release. I would strongly recommend using this over the official lnd.
