### ISSUE TITLE
failure with getblocktemplate (mweb)

### ISSUE THREAD

**Issue by chappjc** [litecoin-project/litecoin#789]
`getblocktemplate '{"rules": ["segwit", "mweb"]}'`

```
CreateNewBlock(): block weight: 19086 txs: 23 fees: 383780 sigops: 930 MWEB weight: 0
ERROR: TestBlockValidity: Consensus::CheckBlock: bad-txns-vin-empty, Transaction check failed (tx hash ea574278edb0aabf11774c56862491f0c9165e802847625cfff56a57df3d2caa) 
```

50d39a320963222b70b5b1f114810bd3e604efd5

Also, please cherry pick https://github.com/bitcoin/bitcoin/commit/3a62b8b77e7b1b08c251551e3cf528f94c3392f8 to fix build issues.

**Comment by losh11** [comment]
I would advise clearing your mempool.

I can’t see tx ea574278edb0aabf11774c56862491f0c9165e802847625cfff56a57df3d2caa
in my mempool. Are you running rc5? Earlier release candidates may have
issues.

**Comment by chappjc** [comment]
I've toasted mempool.dat a couple times.  Also did a `-reindex`.

I don't see `ea57427` with `getrawtransaction` or `getrawmempool` either, so I'm equally uncertain about where this tx is coming from.

testnet, to clarify.

I also tried a fresh resync from genesis, but it gets all headers, and stops processing blocks back in February.  Possibly related to the current stuck testnet at the diff interval disallowing min diff blocks. :/  Would like to try again once it gets moving.

**Comment by chappjc** [comment]
Oh, I'm running a bit ahead of rc3, at 50d39a32, which seems to include a "partial rewind" change to wallet, but nothing consensus related.

**Comment by chappjc** [comment]
I meant to say I'm past rc5.  https://github.com/litecoin-project/litecoin/commit/50d39a320963222b70b5b1f114810bd3e604efd5

**Comment by DavidBurkett** [comment]
Can you run `getrawmempool true` and share the response?

**Comment by chappjc** [comment]
https://gist.github.com/chappjc/6ec9a0f6bced59b2636e140577d86e23

A longer running 0.18 node has over 300, and it also lacks tx ea57427

**Comment by chappjc** [comment]
In case it's relevant, have both txindex and blockfilterindex enabled and synced:

```json
{
  "txindex": {
    "synced": true,
    "best_block_height": 2263967
  },
  "basic block filter index": {
    "synced": true,
    "best_block_height": 2263967
  }
}
```

**Comment by chappjc** [comment]
`LogPrintf("%s", tx.ToString());` in `CheckTransaction` says this:

```cpp
CTransaction(hash=ea574278ed, ver=2, vin.size=0, vout.size=1, nLockTime=0)
    CTxOut(nValue=0.00000000, scriptPubKey=582020f136d07c93adb00cacc417c2)
```

**Comment by chappjc** [comment]
One more update. Wiped the datadir that was stuck, copied from a 0.18 datadir (that is at tip), started up with mweb rc5.  Still get the `getblocktemplate` error, but with reference to a different tx hash:

```
2022-03-31T14:02:20Z CreateNewBlock(): block weight: 1024 txs: 0 fees: 0 sigops: 400 MWEB weight: 0
2022-03-31T14:02:20Z CTransaction(hash=970882a76b, ver=2, vin.size=0, vout.size=1, nLockTime=0)
    CTxOut(nValue=0.00000000, scriptPubKey=58205528fbd50f9e0e1385a47ee56b0b688cfa64f1bb0300f60fb09ca23749677d6e)
2022-03-31T14:02:20Z ERROR: TestBlockValidity: Consensus::CheckBlock: bad-txns-vin-empty, Transaction check failed (tx hash 970882a76b289b41540e73a46afb333f0767b2e7b541e17a2223ab1dd8c6bf55)
```

I've changed the txout printer to show the entire pkscript, so you can see the block it's referencing.

**Comment by chappjc** [comment]
I'm still unable to sync testnet with the release of 0.21.2

Fresh sync,  nuked datadir, ends like this:

```
$ litecoin-cli -testnet -getinfo
{
  "version": 210200,
  "blocks": 2215583,
  "headers": 2323358,
```

All block headers received, but litecoind stuck:

`2022-05-09T17:17:35Z UpdateTip: new best=40c33f9c29a9ba682cc625274cccead5266fe35d023571ec9a4748ad7189c9b9 height=2215583 version=0x20000010 log2_work=55.215562 tx=5617737 date='2022-02-25T08:04:07Z' progress=0.931388 cache=747.5MiB(5700480txo)`

**Comment by chappjc** [comment]
This had to do with the chain split.  I managed to get it to sync by manually adding a node on the mweb fork and manually invalidating c863de49fba3a52e26758fbd232864110e540ae95c97c6cd55c968d5ccd98a79.

**Comment by losh11** [comment]
Is there any reason why it's stuck?
Do you have no peers, etc?

Can you run getnetworkinfo, and getpeerinfo please?

**Comment by chappjc** [comment]
Long since resolved, but it took some manual intervention to get on the right chain: https://github.com/litecoin-project/litecoin/issues/789#issuecomment-1121712719
Recall the issues with testnet having a long non-mweb chain
