### ISSUE TITLE
Why was DUST_RELAY_TX_FEE changed? And the changed commits seem odd to me.

### ISSUE THREAD

**Issue by mone-d** [litecoin-project/litecoin#791]
I thought the dust threshold for Litecoin was 546satoshi. 
However, when I broadcast a 600satoshi transfer transaction, it failed with a dust error.
I found that DUST_RELAY_TX_FEE, which is the factor that determines the dust threshold, was changed to 10x in the following commit. Therefore, the transfer of 600satoshi below 5460satoshi failed.

https://github.com/litecoin-project/litecoin/commit/a02856e36a261173bd14d56c34caa7066f2a9e32

For that fact I have the following questions.
- What was the reason for the change to 10x?
- Why is there no mention in the release notes when the specification was changed?
- Is it not a problem that it seems to have been committed directly to the master branch and has not been reviewed by anyone?
- Why is it that in the next 0.21.1 version, the whole commit seems to have been deleted (reverted)?

Can someone please tell me what is going on?

**Comment by losh11** [comment]
In Litecoin Core 0.21.2+ `DUST_RELAY_TX_FEE` was readjusted to the original 5460 sat value.
