### ISSUE TITLE
Upgrade db from 4.8 to 5.+

### ISSUE THREAD

**Issue by keefer223** [litecoin-project/litecoin#797]
I'm trying to compile from source and numerous warnings and faults are present. It appears that some of the code needs to be updated to the current versions of required programs.

#if !((DB_VERSION_MAJOR == 4 && DB_VERSION_MINOR >= 8) || DB_VERSION_MAJOR > 4)
|           #error "failed to find bdb 4.8+"
|         #endif

The current version of bdb for Debian 11 is 5.3.

Then we have:

configure:5108: $? = 0
configure:5097: g++ -std=c++11 -V >&5
g++: error: unrecognized command-line option '-V'
g++: fatal error: no input files
compilation terminated.

configure:5108: $? = 1
configure:5097: g++ -std=c++11 -qversion >&5
g++: error: unrecognized command-line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.

configure:5112: checking whether we are using the GNU Objective C++ compiler
configure:5131: g++ -std=c++11 -c   conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
compilation terminated.

configure:5112: checking whether we are using the GNU Objective C++ compiler
configure:5131: g++ -std=c++11 -c   conftest.mm >&5
g++: fatal error: cannot execute 'cc1objplus': execvp: No such file or directory
compilation terminated.

the list is so long I've attached a [config.log]
file:///home/keefer/litecoin/config.log

**Comment by losh11** [comment]
Please see this reply for futher information: https://github.com/litecoin-project/litecoin/issues/896#issuecomment-1531192093

Please read the build instructions carefully, you will see a section on bdb4.8 and how you can build it.
