### ISSUE TITLE
Testnet is not syncing (v0.21.2rc6)

### ISSUE THREAD

**Issue by MinwooJ** [litecoin-project/litecoin#798]
I updated my litecoin testnet node to v0.21.2rc6 by docker image, but it is not syncing after the update version. Can anyone help with this? The log is like below.
```
2022-05-03T05:35:13Z New outbound peer connected: version: 70016, blocks=2314018, peer=83 (full-relay)
2022-05-03T05:35:14Z New outbound peer connected: version: 70016, blocks=2263967, peer=84 (full-relay)
2022-05-03T05:36:50Z Potential stale tip detected, will try using extra outbound peer (last tip update: 5960 seconds ago)
2022-05-03T05:37:32Z New outbound peer connected: version: 70016, blocks=2314022, peer=85 (full-relay)
2022-05-03T05:38:53Z New outbound peer connected: version: 70016, blocks=2314022, peer=88 (full-relay)
2022-05-03T05:38:57Z New outbound peer connected: version: 70016, blocks=2314022, peer=89 (full-relay)
2022-05-03T05:39:50Z Potential stale tip detected, will try using extra outbound peer (last tip update: 6140 seconds ago)
2022-05-03T05:42:50Z Potential stale tip detected, will try using extra outbound peer (last tip update: 6320 seconds ago)
2022-05-03T05:43:11Z New outbound peer connected: version: 70016, blocks=2314024, peer=91 (full-relay)
2022-05-03T05:45:33Z New outbound peer connected: version: 70016, blocks=2314026, peer=94 (full-relay)
2022-05-03T05:45:50Z Potential stale tip detected, will try using extra outbound peer (last tip update: 6500 seconds ago)
2022-05-03T05:46:17Z New outbound peer connected: version: 70016, blocks=2314026, peer=96 (full-relay)
```

I have rolled back the version, and it works again but after update to v0.21.2rc6 it's not syncing again. 
Mainnet node was fine after the update, but the testnet nodes are like this.

**Comment by losh11** [comment]
On testnet, a full reindex/resync is required. Please start your 0.21.2
client with a reindex.

**Comment by MinwooJ** [comment]
@losh11 Can you estimate how long does it take when start the client with reindexing?

**Comment by losh11** [comment]
Depends on your disk and CPU speed. On my MacBook Pro it can take around 2
hours.

**Comment by MinwooJ** [comment]
Thank you for the replying. One more question, which option of reindex do you mean `-reindex-chainstate` or `-reindex` ?

**Comment by losh11** [comment]
I haven’t tried -reindex-chainstate myself, but it might work. Not 100%
sure.

**Comment by MinwooJ** [comment]
@losh11 I just finished reindexing. But there's a problem, it looks like a different chain from the previous version. The latest block number and block hash are different from the previous version and there is a difference from the explorer.

The node running on the new server with v0.21.2rc6 is also different from the existing version and the block is different from the explorer.

The node that I just reindexed and the node that ran on the new server have the same block.

Here is the block I compared.
```
Block Number: 2314205

v0.21.2rc6's hash: 952c2b22fe74260891035e8b37b1f2c14c77e9f9680bf10945d55df2077bf44d
v0.17.1's hash: df1d7f13e68fc8e130f70aa04745b61d02cccf4f209c31384050c3dd9456ef4b
explorer's hash: df1d7f13e68fc8e130f70aa04745b61d02cccf4f209c31384050c3dd9456ef4b
explorer link: https://blockexplorer.one/litecoin/testnet/blockHash/2314205
```

I think there is a chain split between the previous versions, v0.17.1 and v0.21.2. Can you check it out?

**Comment by losh11** [comment]
Yes this is expected. After MWEB activated on testnet, someone started
mining with the 0.18.1 client, with a ton of hashrate.
The longest chain is currently the non-mweb one, and all clients <0.21 will
chose the invalid fork.
This will continue to occur until the MWEB chain become longer.

**Comment by MinwooJ** [comment]
@losh11 I didn't even think that the majority of nodes were invalid in the testnet.

Then I have a few more questions.

1. Will clients < 0.21 follow the invalid chain after the activation block on Mainnet? If so, shouldn't there be more 0.21 clients than < 0.21?

2. Currently, v0.21 is the rc version, when is the stable version coming out? Does it come out after activation block? I am asking this question because I am a little reluctant to use rc version of client in the Real environment service.

3. All the testnet explorers I looked up follow the invalid chain. Is there a testnet explorer that is serviced by a valid chain?

4. I'd like to test the taproot address and withdrawal through Testnet, and I'm curious about how to generate the taproot address in the 0.21 client. I couldn't find any guide docs or wiki.

**Comment by losh11** [comment]
> Will clients < 0.21 follow the invalid chain after the activation block
on Mainnet? If so, shouldn't there be more 0.21 clients than < 0.21?

As most of the hashrate on mainnet has supported MWEB (>90%), and will be
mining with 0.21, the longest chain will always be 0.21.
So 0.18.1 (and older) clients will recognise the MWEB chain as the longest
valid chain.

> Currently, v0.21 is the rc version, when is the stable version coming
out? Does it come out after activation block? I am asking this question
because I am a little reluctant to use rc version of client in the Real
environment service.

Currently we consider Litecoin Core 0.21.2rc7 safe for production use. We
expect to release the final build of Litecoin 0.21.2 in the next few days.

> All the testnet explorers I looked up follow the invalid chain. Is there
a testnet explorer that is serviced by a valid chain?

We have contacted many of the testnet explorers to update to 0.21.2, and I
believe Chain.So has updated.

> I'd like to test the taproot address and withdrawal through Testnet, and
I'm curious about how to generate the taproot address in the 0.21 client.
�I couldn't find any guide docs or wiki.

Documentation regarding the taproot update can be found in the mweb branch
of the litecoin repo. Although there is still some missing docs which we
are still working on.

**Comment by MinwooJ** [comment]
@losh11 And one more question. 🙇 

When I request rpc call 'estimatesmartfee' in 0.21.2rc6 as I did in v0.17.1, but the response is null. Is there any changes in `estimatesmartfee` rpc method between v0.17.1 and v.0.21.2rc6?

**Comment by losh11** [comment]
Smart fees is being adjusted at the moment, before a final release. You
also need to keep Litecoin Core running for a while before smart fee gives
a reasonable fee rate.

**Comment by MinwooJ** [comment]
@losh11 Can you answer this question too? 🙇‍♂️ 

> Should I create a DUMMY wallet for 0.21.5rc? My service generates the keys and address, and signed it. It's just using the litecoin-core when it broadcasts the signedTranasction. but It got failed in broadcasting. The error is like "No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet." in 0.17, It doesn't need to create a dummy wallet.

**Comment by MinwooJ** [comment]
@losh11 Though I'm running 0.21 core for while, It returns error when that tried to call rpc ('estimatesmartfee') in testnet. is it okay? It's just issues on only testnet?

**Comment by losh11** [comment]
Yes. In 0.21.2, you must create and load a wallet before you can generate
an address.
