### ISSUE TITLE
TestNet dnsSeed addresses are not working.  What are the TestNet dnsSeed addresses

### ISSUE THREAD

**Issue by doc-ef** [litecoin-project/litecoin#800]
The only documentation I can find shows the LiteCoin TestNet dnsSeed addresses are:  testnet-seed.litecointools.com, seed-b.litecoin.loshan.co.uk, dnsseed-testnet.thrasher.io.
NONE of these 3 dns names even resolve anymore (just do a nslookup on them),  If there are updated/working dnsSeeds for LiteCoin TestNet, could someone publish them somewhere

**Comment by doc-ef** [comment]
Looking at the sources in chainparams.cpp in master branch, I see the below code, which is also using these 3 dns seeds for TestNet.  THEY DO NOT WORK/are not dns names that resolve or exist anymore.      
 vSeeds.emplace_back("testnet-seed.litecointools.com");
 vSeeds.emplace_back("seed-b.litecoin.loshan.co.uk");
 vSeeds.emplace_back("dnsseed-testnet.thrasher.io");

**Comment by losh11** [comment]
working to get my dns seeder back online!

**Comment by doc-ef** [comment]
would be greatly appreciated if u can get one of those 3 working, or give me a dns seed for testnet that works (can always rebuild lib with updated seed address).  trying to do some dev work and relatively certain no one wants me to be doing that on mainnet ;)

**Comment by losh11** [comment]
In the meanwhile if you are struggling to find peers on 0.21.2, please also
feel free to connect to the LF hosted node: 178.62.46.195:19333.

**Comment by doc-ef** [comment]
Not sure why this is closed.  The 3 dns seeds are still not online.  I tried using 178.62.46.195:19333 by hand jamming this Peer into lib, but guessing there is a version conflict (see debug traces below) as the litecoinj lib is working against current mainnet version (the lib works fine against mainnet, but don't want to use mainnet to test code).  Is there any way to get the LiteCoin TestNet working again?

[NioClientManager] INFO  org.litecoinj.net.NioClientManager - Connected to /178.62.46.195:19333
[NioClientManager] INFO  org.litecoinj.core.Peer - Announcing to /178.62.46.195:19333 as: /litecoinj:0.2/
[NioClientManager] DEBUG org.litecoinj.core.BitcoinSerializer - Sending version message: fdd2c8f176657273696f6e000000000065000000760aa2f57d11010000000000000000004253796200000000000000000000000000000000000000000000ffffb23e2ec34b85000000000000000000000000000000000000ffff7f0000014b8700000000000000000f2f6c697465636f696e6a3a302e322f004d1c0000
[NioClientManager] DEBUG org.litecoinj.core.BitcoinSerializer - Received 107 byte 'version' message: 8011010049040001000000004253796200000000000000000000000000000000000000000000ffff4464b8a0c24e490400010000000000000000000000000000000000000000000046cd174f5170c150152f4c697465636f696e436f72653a302e32312e322fde63230001
[NioClientManager] INFO  org.litecoinj.core.Peer - Peer{[178.62.46.195]:19333, version=70016, subVer=/LitecoinCore:0.21.2/, services=16778313 (NETWORK, WITNESS, NETWORK_LIMITED, remaining: 1000000000000000001000000), time=2022-05-09 17:45:38, height=2319326}
[NioClientManager] INFO  org.litecoinj.core.PeerGroup - [178.62.46.195]:19333: Peer died      (0 connected, 0 pending, 1 max)

**Comment by valiopld** [comment]
Same problem. Any suggestions?

**Comment by david-oyeku** [comment]
I think the issue with the testnet DNS seeds might be back. they all dont work again
