### ISSUE TITLE
Add Docker image building from source

### ISSUE THREAD

**Issue by pataquets** [litecoin-project/litecoin#803]
Add a `Dockerfile` to enable building Docker images from the source code.
This can serve to many purposes:
* Development/hacking workflow. No development packages nor toolchain required to hit the road, just Docker.
* Running/deploying the software easily from source. Just build the image, and run a container. No need for OS packages.
* Publishing an official docker image on [Docker Hub](https://hub.docker.com).
* CI/CD pipelines.

Each use case has its own specific requirements, but they're not excluding. They may even be overlapping or have an acceptable compromise (eg. the development image will not be size-optimized for distribution, but size can be worked around later).

What's required initially:
* Select a base OS/distro. Debian/Ubuntu LTS are the most stable. Alpine for size, but links against musl instead of libc. Also, there is an [official GCC image](https://hub.docker.com/_/gcc), which has many flavours (eg. Debian).
* Create a suitable Dockerfile which contains/installs build tools, installs dev deps and runs build process.

With just that file, a quick one-liner build will be possible:
```sh
docker build -t litecoin github.com/litecoin-project/litecoin#master
```
This will produce a runnable image locally. Not even cloning the repo will be needed.

**Comment by losh11** [comment]
We're looking into providing official dockerfiles. Waiting on hearing back from Docker on if we can get an open source docker hub account.

**Comment by pataquets** [comment]
Great to hear that, @losh11.
In case you don't get one, image build and publishing can be automated using Github Actions and the Docker Hub free plan.

**Comment by losh11** [comment]
A docker image is now available, but not yet uploaded to Docker Hub: https://github.com/litecoin-project/docker-litecoin-core

**Comment by losh11** [comment]
The docker image has now been uploaded to Docker Hub.
