### ISSUE TITLE
RE-Opening Issue #800

### ISSUE THREAD

**Issue by doc-ef** [litecoin-project/litecoin#804]
Not sure why this is closed. The 3 dns seeds are still not online. I tried using 178.62.46.195:19333 by hand jamming this Peer into lib, but guessing there is a version conflict (see debug traces below) as the litecoinj lib is working against current mainnet version (the lib works fine against mainnet, but don't want to use mainnet to test code). Is there any way to get the LiteCoin TestNet working again?  I understand there is a new 0.21.2 version, but that should not be a reason for there to be no working TestNet on current version.

[NioClientManager] INFO org.litecoinj.net.NioClientManager - Connected to /178.62.46.195:19333
[NioClientManager] INFO org.litecoinj.core.Peer - Announcing to /178.62.46.195:19333 as: /litecoinj:0.2/
[NioClientManager] DEBUG org.litecoinj.core.BitcoinSerializer - Sending version message: fdd2c8f176657273696f6e000000000065000000760aa2f57d11010000000000000000004253796200000000000000000000000000000000000000000000ffffb23e2ec34b85000000000000000000000000000000000000ffff7f0000014b8700000000000000000f2f6c697465636f696e6a3a302e322f004d1c0000
[NioClientManager] DEBUG org.litecoinj.core.BitcoinSerializer - Received 107 byte 'version' message: 8011010049040001000000004253796200000000000000000000000000000000000000000000ffff4464b8a0c24e490400010000000000000000000000000000000000000000000046cd174f5170c150152f4c697465636f696e436f72653a302e32312e322fde63230001
[NioClientManager] INFO org.litecoinj.core.Peer - Peer{[178.62.46.195]:19333, version=70016, subVer=/LitecoinCore:0.21.2/, services=16778313 (NETWORK, WITNESS, NETWORK_LIMITED, remaining: 1000000000000000001000000), time=2022-05-09 17:45:38, height=2319326}
[NioClientManager] INFO org.litecoinj.core.PeerGroup - [178.62.46.195]:19333: Peer died (0 connected, 0 pending, 1 max)

**Comment by losh11** [comment]
Testnet DNS seeders are now back online! Last year, around the time of this post, there seemed to be a targeted attack on Litecoin Testnet, to prevent MWEB activation. The attacker used a lot of hashrate to make their non-MWEB chain longer. This is no longer the case. For a reliable Litecoin testnet explorer, chain.so works great.
