### ISSUE TITLE
Update unix build docs to include libfmt

### ISSUE THREAD

**Issue by cen1** [litecoin-project/litecoin#806]
Unix build documentation no longer works since 0.21.2 because libfmt is now a required dependency.

https://github.com/litecoin-project/litecoin/blob/0.21/doc/build-unix.md

For ubuntu 20.04 this seems to work for me, I did not try other systems:
```
apt-get -y update
apt-get -y install software-properties-common
add-apt-repository universe
apt-get -y update
apt-get -y install libfmt-dev
```

**Comment by losh11** [comment]
addressed with cad62d89790963fea1c24457aa96fbb235e19b5a
