### ISSUE TITLE
Can't create block 432 on regtest

### ISSUE THREAD

**Issue by Gzernov** [litecoin-project/litecoin#807]
As per title, after upgrading to 0.21.2 I can no longer create blocks in regtest past 432.
Steps to reproduce:
1. Start regtest node
2. `litecoin-cli createwallet ""`
3. ```litecoin-cli generatetoaddress 431 `litecoin-cli getnewaddress` ```
4.  `litecoin-cli getblockcount` -> 431
5. ```litecoin-cli generatetoaddress 1 `litecoin-cli getnewaddress` ```

Results in
```
error code: -1
error message:
CreateNewBlock: TestBlockValidity failed: bad-txns-vin-empty, Transaction check failed (tx hash 58338ec7c9c4e6086f9eef6093d79a69d930d7ca695d1759b07180fef29d8f8e) 
```

This transaction doesn't exist. No transactions were sent and no transactions should be in mempool
```
litecoin-cli getrawtransaction 58338ec7c9c4e6086f9eef6093d79a69d930d7ca695d1759b07180fef29d8f8e
error code: -5
error message:
No such mempool or blockchain transaction. Use gettransaction for wallet transactions.

litecoin-cli gettransaction 58338ec7c9c4e6086f9eef6093d79a69d930d7ca695d1759b07180fef29d8f8e
error code: -5
error message:
Invalid or non-wallet transaction id

```

**Comment by jjambazov-bc** [comment]
I get a similar issue in custom integration tests: `BitcoindException(super=com.neemre.btcdcli4j.core.BitcoindException: Error #-1: CreateNewBlock: TestBlockValidity failed: bad-txns-vin-empty, Transaction check failed (tx hash 58338ec7c9c4e6086f9eef6093d79a69d930d7ca695d1759b07180fef29d8f8e) , code=-1)`. The test communicates with the LTC node through RPC and does the following:

1. `rpcClient.createWallet("testwallet")`
2. Generate blocks:

```kotlin
    override fun generate(blocks: Int) {
        val account = rpcClient.getNewAddress()
        rpcClient.generateToAddress(blocks, account)
    }
```

With release `0.21.1rc1` block generation works properly, so it should be a problem in release `0.21.2`.

**Comment by majority-energy** [comment]
We are having these same errors in our custom integration tests on v0.21.2.

**Comment by DavidBurkett** [comment]
Block 432 is when MWEB activates. It requires a peg-in. You'll need to generate an mweb address and send some coins to it. Then it will allow you to mine the next block.

**Comment by Gzernov** [comment]
> Block 432 is when MWEB activates. It requires a peg-in. You'll need to generate an mweb address and send some coins to it. Then it will allow you to mine the next block.

Thanks, do you mind writing the cli commands to do so? 
I could find any documentation on generating mweb address/sending mweb transaction

**Comment by majority-energy** [comment]
This works for us. We are not getting the `bad-txns-vin-empty` from block 1.
```
# height should be zero but just in case
CURRENT_HEIGHT=$(litecoin-cli getblockchaininfo | jq '.blocks')
ADDR=$(litecoin-cli getnewaddress)
BLOCKS_TO_GENERATE=$((432 - $CURRENT_HEIGHT - 1))
litecoin-cli generatetoaddress $BLOCKS_TO_GENERATE $ADDR
ADDR_MWEB=$(litecoin-cli getnewaddress mweb mweb)
litecoin-cli sendtoaddress $ADDR_MWEB 1
litecoin-cli generatetoaddress 10 $ADDR
```

**Comment by Gzernov** [comment]
@majority-energy thanks for detailed reply, I will close the issue now.
