### ISSUE TITLE
How to get address with script type WITNESS_MWEB_HOGADDR and WITNESS_MWEB_PEGIN?

### ISSUE THREAD

**Issue by Shuixingchen** [litecoin-project/litecoin#808]
I found the function ExtractDestination() didn't deal TxoutType::WITNESS_MWEB_HOGADDR and TxoutType::WITNESS_MWEB_PEGIN condition. but how i can get stealsh address from script type?

**Comment by DavidBurkett** [comment]
WITNESS_MWEB_HOGADDR is not a stealth address. It's a commitment to the extension block.
WITNESS_MWEB_PEGIN is also not a stealth address. It's a commitment to a MW transaction kernel.
Note that, unless you are the owner of an output, or know the view key, it's not possible to retrieve a stealth address from the onchain data. That's what makes them so _stealth_y :)
