### ISSUE TITLE
Testnet stuck on block #2336670

### ISSUE THREAD

**Issue by dlerario** [litecoin-project/litecoin#809]
To be synced with latest block, now on #2349072 (19/05/2022 - 22:26:29 UTC) ( font https://blockexplorer.one/litecoin/testnet/ ) 

Stuck on block #2336670 (shows as 100% sync), can't get highest block.

I've cleaned the /testnet4 folder, except /wallet internal folder, and restarted the litecoind and waited to sync from zero again, but stuck on #2336670 everytime.

Litecoin Core 0.21.2.

Ubuntu 20.04.4 LTS / HDD disk 4tb Seagate Barracuda .

**Comment by losh11** [comment]
You are actually running the correct fork. Blockexplorer.one is reporting
incorrect/invalid litecoin chains.
Please compare with chain.so: https://chain.so/testnet/ltc
