### ISSUE TITLE
Hard fork on litecoind testnet Mar30, consensus mismatch with diffeent explorers

### ISSUE THREAD

**Issue by jun0tpyrc** [litecoin-project/litecoin#812]
https://chain.so/testnet/ltc <= same as the result re-sync by litecoind 0.21.2

higher block heights, but don't know to sync to get to this tip
https://tltc.bitaps.com/blocks 
https://blockexplorer.one/litecoin/testnet/

**Comment by jun0tpyrc** [comment]
- how to get to correct result if the bottom 2 explorers are right?

**Comment by losh11** [comment]
The correct tip is reported by chain.so. The other block explorers are
showing the chain which has hard forked away by not supporting MWEB. We
have already contacted Litecoin testnet explorers to update their node to
0.21.2 to fix this misreporting.

**Comment by losh11** [comment]
Closing. Please let me know if you experience any other issues.

**Comment by AresDad319** [comment]
> The correct tip is reported by chain.so. The other block explorers are showing the chain which has hard forked away by not supporting MWEB. We have already contacted Litecoin testnet explorers to update their node to 0.21.2 to fix this misreporting.

can you tell me this hard fork happened from which block for testnet
?
