### ISSUE TITLE
rpc request submitblock return {"result":"mweb-missing","error":null,"id":"1"}

### ISSUE THREAD

**Issue by ihaevn** [litecoin-project/litecoin#817]
I update litecore to 0.21，rpc submitblock return {“result”:“mweb-missing”,“error”:null,“id”:“1”}，How to solve it？

**Comment by losh11** [comment]
In the latest update there are mandatory changes to mining: https://github.com/litecoin-project/litecoin/blob/0.21/doc/mweb/mining-changes.md

Please read the document linked and implement it into your pool/mining software.

**Comment by losh11** [comment]
The separator is 01. I think you're adding just a single 1.

**Comment by ihaevn** [comment]
thank you @losh11
