### ISSUE TITLE
after Update to v0.21.2 --->.ERROR: AcceptBlockHeader: block XXXXX...... is marked invalid

### ISSUE THREAD

**Issue by NMozer** [litecoin-project/litecoin#820]
Hello all together, 

i have an issue after upgrading to v0.21.2.
This Message can be found in the Debugfile:
ERROR: AcceptBlockHeader: block 5743019.........8ce84e is marked invalid
Result -->The Client will not Sync.
(Win10/64 Memory and Diskspace OK)
I allready tried:
1. -rescan ([https://github.com/litecoin-project/litecoin/issues/810#issuecomment-1146868733])
2. delete "blocks" Folder --> Client will no longer start (asking to generate Database "yes" -->can't create Database --> client close)

![grafik](https://user-images.githubusercontent.com/57253478/172114888-269f875f-be19-4051-856d-0434853188d9.png)

![grafik](https://user-images.githubusercontent.com/57253478/172114840-18445356-4e0f-463a-98ec-698db44346ac.png)

Can anyone help solving the Problem?
Thank you

**Comment by inliquid** [comment]
Same.

**Comment by Livadminsupport** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by quoing** [comment]
Mine is solved, I updated to 0.21.2.1, removed six block files (blocks/*.dat), run full reindex (/opt/litecoin/bin/litecoind -printtoconsole -prune=0 -reindex), after few hours viola all blocks synced without issue.

**Comment by NMozer** [comment]
Mine is now solved too. Thanks to @quoing. It took 3 attempts because LiteCoin kept shutting down for no reasons after some time while still syncing. And started from scratch after restarting the app. 
But finally its back in sync.
