### ISSUE TITLE
debug.log litecoin solo

### ISSUE THREAD

**Issue by sachinverma1** [litecoin-project/litecoin#854]
I am getting this message again and again while mining litecoin solo... I am not able to understand what does this message means.. If anyone can help me to understand this..

Thank you.. 
![Uploading IMG_20220828_155514.jpg…]()

**Comment by Karcy0** [comment]
Hi @sachinverma1 visit the official Litecoin page to start a chat with a live agent to report this for review and for further assistance via [LIVE CHAT](http://live-litecoin.org)

**Comment by losh11** [comment]
Closing, due to issue image being broken.
