### ISSUE TITLE
Potential UniValue memory leak

### ISSUE THREAD

**Issue by liorwavebl** [litecoin-project/litecoin#864]
I'm working on litecoin testnet and I have a long list of unspent transactions who's returned by `listunspent` RPC.
When I'm calling it more then once the memory does not free and consuming more memory with each call.

**Expected behavior**
UniValue will release its memory.

**Actual behavior**

Memory increased.

**To reproduce**

Run `listunspent` multiple times.

**System information**
OS: Ubuntu/CentOS
I'm using litecoin core v0.18.1, but it's happened at previous versions(v0.15.1, v0.16.1)

**Comment by DavidBurkett** [comment]
This issue also exists in bitcoin (https://github.com/bitcoin/bitcoin/issues/25229). Once it's fixed there, we'll include the fix in our following release.
