### ISSUE TITLE
TestNet dnsSeed addresses are not working. 

### ISSUE THREAD

**Issue by david-oyeku** [litecoin-project/litecoin#876]
TestNet dnsSeed addresses are not working.

Have they changed? Can they be fixed?

This is causing a low peer count on lite coin testnet nodes.

[https://github.com/litecoin-project/litecoin/blob/4ae03b3f04ae273c64d8613182fb7c5e83e87705/src/chainparams.cpp#L238](url)

**Comment by losh11** [comment]
Testnet seed `seed-b.litecoin.loshan.co.uk` has now been fixed, should return any stable node.
