### ISSUE TITLE
Addresses Creation In LTC

### ISSUE THREAD

**Issue by ahmed-naeem1012** [litecoin-project/litecoin#878]
when downloaded the complete blockchain of Lite-Coin Core, i want to create bulk of LTC address for my use. Can anyone out there guide me how can I proceed to create addresses with private keys

**Comment by im95888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by losh11** [comment]
Sorry this is not what Issues are meant for. Please ask on litecointalk, or elsewhere.

**Comment by ahmed-naeem1012** [comment]
The, issue had been resolved externally by connection with localhost, Thanks!!
