### ISSUE TITLE
 Descriptor wallets not supported, I am getting this error while creating descriptor wallet. I tried to enable in config file also. but solved my issue. Please help I am using   Litecoin Core version v0.21.2.1.

### ISSUE THREAD

**Issue by SamirBitzees** [litecoin-project/litecoin#884]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by FeragamoDd** [comment]
@SamirBitzees Talk to Litecoin  Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

**Comment by losh11** [comment]
Descriptor wallets were not added in Litecoin 0.21.x. We are looking into doing so for the next release.
