### ISSUE TITLE
Sincronization

### ISSUE THREAD

**Issue by pokecosimo** [litecoin-project/litecoin#893]
![image](https://user-images.githubusercontent.com/96430819/230791756-443de841-e2c2-4151-9578-dfc912feed03.png)
Litteraly 5 days for sync

**Comment by NamecoinGithub** [comment]
https://chainz.cryptoid.info/ltc/#!network

I wonder is LTC a Shitcoin now?  

No one even runs the new MWEB Wallets?  

I thought the new MWEB was a Hard-Fork?  How are all those old wallets operating?  IDK

I think it has to do with the connection issues 


![LitecoinNetwork2023April](https://user-images.githubusercontent.com/130555019/234139098-73111abc-61e8-498d-996d-df9be0418ea6.png)


Synchronization is the correct spelling please change Title

**Comment by losh11** [comment]
@NamecoinGithub For your information: this github issues section is not the place to make this comment.

We believe this explorer to be incorrect. https://blockchair.com/litecoin/nodes shows a more accurate graph, with the majority of nodes labeling themselves as 0.21.x. 
![img](https://i.imgur.com/Ty1xTG7.png)

Also MWEB was not hard-forked in. Older wallets are still able to send/receive non-MWEB transactions.

**Comment by losh11** [comment]
@pokecosimo please check that you are able to find peers. If not, your ISP may have blocked ports required for litecoin to works (9333/tcp).

**Comment by NamecoinGithub** [comment]
I have the same issue NO Connections after Compiling the Wallet as this @pokecosimo 

Your Link does not have a NODE LIST like the site I showed

I was going to add the list to my litecoin.conf file and I changed the Port also but changing the port does not work either

But there are NO MWEB Nodes List to use for my litecoin.conf

????

Do you understand?

**Comment by NamecoinGithub** [comment]
It looks like my Wallet finally found 1 Peer that it says is running 21 Version Wallet to sync with, but that will take weeks at the rate it's going to finish and maybe they don't have the Full Blockchain either

**Comment by losh11** [comment]
Once you have 1 peer, you client should automatically find other peers that this peer is also connected to. Syncing the litecoin blockchain can take a few hours at the very best (80GB download + verification). You will have to keep your computer turned on, and let it sync.

**Comment by NamecoinGithub** [comment]
![LitecoinPeerConnectsOnly2New21Wallets](https://user-images.githubusercontent.com/130555019/234143265-d29c2674-b72d-4b8c-8db1-a1f1bc5db4a9.png)


I think it probably only connected to that same computers IPV6 Connection after 10 MIns still just 1 Peer but at least it's only connecting to 21.x Peers

So maybe my picture is correct and yours is the "Illusion" IDK

Last time I compiled Litecoin last year it found lots of connections in not more than 1 MIN

**Comment by losh11** [comment]
Closing.
