### ISSUE TITLE
Testnet DNS Seeds not working 

### ISSUE THREAD

**Issue by ejaznoob** [litecoin-project/litecoin#897]
None of the three DNS Seeds seems to work. 

**Expected behavior**
I expect to get the testnet dns seeds be resolved and connect.
**Actual behavior**
2023-05-17T20:52:11Z Waiting 11 seconds before querying DNS seeds.
2023-05-17T20:52:22Z Loading addresses from DNS seed testnet-seed.litecointools.com
2023-05-17T20:52:22Z Loading addresses from DNS seed dnsseed-testnet.thrasher.io
2023-05-17T20:52:32Z Loading addresses from DNS seed seed-b.litecoin.loshan.co.uk
2023-05-17T20:52:32Z 0 addresses found from DNS seeds
**To reproduce**

litecoind --testnet
**System information**

Litecoin Core version v0.21.2.2-bf355d283
Ubuntu 22

**Comment by losh11** [comment]
My testnet DNS seed is really struggling to find peers, I'm not totally sure why... but there is at least 1 peer. I've asked thrasher to fix his testnet seeder also.

```bash
$ nslookup seed-b.litecoin.loshan.co.uk 
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	seed-b.litecoin.loshan.co.uk
Address: 89.39.104.167
```

**Comment by losh11** [comment]
For reference it seems that there are multiple testnet nodes, but not all of them live atm or reliable:
```bash
[23-05-18 18:14:26] 1/24 available (8 tried in 1s, 0 new, 16 active), 1 banned; 1 DNS requests, 1 db queries
```

**Comment by losh11** [comment]
The issue has been identified and fixed:

```
nslookup seed-b.litecoin.loshan.co.uk
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	seed-b.litecoin.loshan.co.uk
Address: 51.79.82.75
Name:	seed-b.litecoin.loshan.co.uk
Address: 89.39.104.167
Name:	seed-b.litecoin.loshan.co.uk
Address: 100.25.120.154
Name:	seed-b.litecoin.loshan.co.uk
Address: 52.194.184.141
Name:	seed-b.litecoin.loshan.co.uk
Address: 195.201.246.33
Name:	seed-b.litecoin.loshan.co.uk
Address: 167.71.53.224
```

It seems that the `litecoin-seeder`'s tor proxy might be causing things to go wrong. TBH the tor proxy is no longer needed as DNS records cannot have responses as long as a torv3 address. To improve reliability with torv3 nodes, we should increase the number of fixed peers for the next release.

Closing as fixed.
