### ISSUE TITLE
ltc core cannot customize lower handling fees

### ISSUE THREAD

**Issue by xiao93** [litecoin-project/litecoin#899]
<img width="335" alt="image" src="https://github.com/litecoin-project/litecoin/assets/42384581/e4876ecb-b818-45ca-b396-35ba70e20eb3">

As a user, I hope that ltc can customize a lower handling fee, such as 0.00001 instead of 0.0001

**Comment by DavidBurkett** [comment]
Allowing users to reduce the fee below the minimum would lead to their transactions not being accepted by nodes, and therefore never broadcast to miners nor included in blocks.
