### ISSUE TITLE
Testnet DNS seeds are down AGAIN!

### ISSUE THREAD

**Issue by jsyqrt** [litecoin-project/litecoin#901]
>>> I've been trying to connect to the hard coded DNS seeds testnet-seed.litecointools.com, seed-b.litecoin.loshan.co.uk dnsseed-testnet.thrasher.io and I'm not receiving the addresses of any peers. I think they might be offline at the moment, please could you reactivate them?

![image](https://github.com/litecoin-project/litecoin/assets/25230253/71a9c0d4-46d3-4c70-85de-549066f0e470)

**Comment by jsyqrt** [comment]
#741

**Comment by losh11** [comment]
Looking into it.

**Comment by losh11** [comment]
@jsyqrt I have talked with thrasher, who will be fixing his seeder soon. I was having issue with my seeder, and have found a go implementation which seems to be rather successful in finding peers. It's what's running on `seed-b.litecoin.loshan.co.uk`, however please note that this dns seeder does not allow for service bit filtering. I am currently working on this - requires further work to the ltcsuite.
