### ISSUE TITLE
FTBFS with GCC-13

### ISSUE THREAD

**Issue by onlyjob** [litecoin-project/litecoin#912]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037756 litecoin/0.21.2.1 FTBFS with GCC-13

The full build log can be found at:
http://qa-logs.debian.net/2023/05/22/logs/litecoin_0.21.2.1-1_unstable_gccexp.log

Common build failures are new warnings resulting in build failures with -Werror turned on, or new/dropped symbols in Debian symbols files. For other C/C++ related build failures see the porting guide at
http://gcc.gnu.org/gcc-13/porting_to.html

```
g++ -std=c++14 -DHAVE_CONFIG_H -I. -I../src/config    -I. -I./secp256k1-zkp/include  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include   -I./libmw/include -I./libmw/deps/caches/include -I./libmw/deps/ghc/include -I./libmw/deps/mio/include -I./univalue/include -Wdate-time -D_FORTIFY_SOURCE=2 -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS  -fstack-reuse=none       -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -fno-extended-identifiers -c -o support/libbitcoin_util_a-lockedpool.o `test -f 'support/lockedpool.cpp' || echo './'`support/lockedpool.cpp
support/lockedpool.cpp: In member function ‘void Arena::free(void*)’:
support/lockedpool.cpp:102:20: error: ‘runtime_error’ is not a member of ‘std’
  102 |         throw std::runtime_error("Arena: invalid or double free");
      |                    ^~~~~~~~~~~~~
support/lockedpool.cpp:25:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   24 | #include <algorithm>
  +++ |+#include <stdexcept>
   25 | #ifdef ARENA_DEBUG
support/lockedpool.cpp: In member function ‘void LockedPool::free(void*)’:
support/lockedpool.cpp:327:16: error: ‘runtime_error’ is not a member of ‘std’
  327 |     throw std::runtime_error("LockedPool: invalid address not pointing to any arena");
      |                ^~~~~~~~~~~~~
support/lockedpool.cpp:327:16: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
```

**Comment by DaCryptoRaccoon** [comment]
The error message is indicating that the compiler cannot find the definition of std::runtime_error, which should be included from the <stdexcept> header. To resolve this issue, you need to include the <stdexcept> header in your support/lockedpool.cpp file.

Add the following line at the top of your lockedpool.cpp file:
`
#include <stdexcept>`

Including the <stdexcept> header will make sure that the std::runtime_error class is available in your code, and the compilation error should be resolved. Make sure to save the file after adding the include directive and then try to recompile the code.

**Comment by onlyjob** [comment]
Thanks, @DaCryptoRaccoon. That did help but then compilation failed as follows:

```
./util/bip32.h:13:75: error: 'uint32_t' was not declared in this scope
   13 | NODISCARD bool ParseHDKeypath(const std::string& keypath_str, std::vector<uint32_t>& keypath);
      |                                                                           ^~~~~~~~
./util/bip32.h:11:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```

and

```
./util/string.h:84:50: error: 'uint8_t' was not declared in this scope
   84 |                                 const std::array<uint8_t, PREFIX_LEN>& prefix)
      |                                                  ^~~~~~~
./util/string.h:17:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
```

In the end the following patch fixed FTBFS:

```
--- a/src/support/lockedpool.cpp
+++ b/src/support/lockedpool.cpp
@@ -1,8 +1,9 @@
 // Copyright (c) 2016-2020 The Bitcoin Core developers
 // Distributed under the MIT software license, see the accompanying
 // file COPYING or http://www.opensource.org/licenses/mit-license.php.
 
+#include <stdexcept>
 #include <support/lockedpool.h>
 #include <support/cleanse.h>
 
 #if defined(HAVE_CONFIG_H)
--- a/src/util/bip32.h
+++ b/src/util/bip32.h
@@ -4,8 +4,9 @@
 
 #ifndef BITCOIN_UTIL_BIP32_H
 #define BITCOIN_UTIL_BIP32_H
 
+#include <cstdint>
 #include <attributes.h>
 #include <string>
 #include <vector>
 
--- a/src/util/string.h
+++ b/src/util/string.h
@@ -6,8 +6,9 @@
 #define BITCOIN_UTIL_STRING_H
 
 #include <attributes.h>
 
+#include <cstdint>
 #include <algorithm>
 #include <array>
 #include <cstring>
 #include <locale>
```

Now it would be great to incorporate it here and/or upstream.

**Comment by DaCryptoRaccoon** [comment]
The error messages you're seeing are related to missing declarations of data types like uint32_t and uint8_t. These types are defined in the <cstdint> header file in C++.

To fix these errors, you should include the appropriate header files in your code files. Add the following lines at the top of the .h files where you're encountering these errors:

#include <cstdint>
Here's how you can include it in the specific lines mentioned in your error messages:


In ./util/bip32.h:

```
#include <cstdint> // Add this line at the top of the file

NODISCARD bool ParseHDKeypath(const std::string& keypath_str, std::vector<uint32_t>& keypath);
```

In ./util/string.h:

```
#include <cstdint> // Add this line at the top of the file

const std::array<uint8_t, PREFIX_LEN>& prefix)
```


By including <cstdint>, you'll be able to access the standard integer types like uint32_t and uint8_t without encountering the "not declared in this scope" errors.

Hope this helps.

**Comment by losh11** [comment]
Closing due to patch found.

**Comment by onlyjob** [comment]
Please close once fix is ___committed___, and not before that. This is an outstanding issue affecting latest release.
