### ISSUE TITLE
Any report, issue or feature request related to the GUI should be reported at https://github.com/bitcoin-core/gui/issues/

### ISSUE THREAD

**Issue by komsunkerdsalung** [litecoin-project/litecoin#933]
Any report, issue or feature request related to the GUI should be reported at
https://github.com/bitcoin-core/gui/issues/

**Comment by losh11** [comment]
A new GUI issue should be reported to both us and bitcoin-core/gui (if they aren't already aware, and the issue exists in the same version of Bitcoin Core).
