### ISSUE TITLE
Windows Wallet

### ISSUE THREAD

**Issue by goodthebest** [litecoin-project/litecoin#943]
I'm compiling Windows wallet for litecoin however facing this error while compiling on Ubuntu 20.04. Any clue how to fix it?

`configure: error: Could not link against boost_filesystem-mt-s-x64 !
`

![image](https://github.com/litecoin-project/litecoin/assets/1715740/c442dae4-fd5c-4eb0-9119-61018a3be675)

**Comment by losh11** [comment]
Are you building against the V0.21.2.2 tag? Also are you following the
docs/build-windows.md? Are you cross compiling from a Ubuntu 20.04 machine
or is this WSL2?

On Wed, 6 Mar 2024 at 03:31, Linux server management, OS softwares and
applications, blockchain Mining Pools, Daemons ***@***.***>
wrote:

**Comment by goodthebest** [comment]
I figured it out, my oversight. Thanks for your attention.
