### ISSUE TITLE
I need the PGP key uploaded to keys.openpgp.org

### ISSUE THREAD

**Issue by elvis-hrvat** [litecoin-project/litecoin#947]
Could you please upload your PGP key `D35621D53A1CC6A3456758D03620E9D387E55666` to [keys.openpgp.org](https://keys.openpgp.org/)?
keys.openpgp.org is a security-conscious keyserver and is used by Thunderbird as its default keyserver.

**Comment by losh11** [comment]
Done: https://keys.openpgp.org/search?q=D35621D53A1CC6A3456758D03620E9D387E55666
