### ISSUE TITLE
prune mode is incompatible with -blockfilterindex

### ISSUE THREAD

**Issue by Leningrad00** [litecoin-project/litecoin#952]
**Actual behavior**
Got "prune mode is incompatible with -blockfilterindex" error.

**Expected behavior**
Successfull start.

**To reproduce**

**System information**

0.21.3

Windows 8.1 x64, LiteCoin client v0.21.3 for Winx64, HDD, pruned database.

**Comment by Leningrad00** [comment]
![0213](https://github.com/litecoin-project/litecoin/assets/34949240/dfe3ba17-0671-42fb-85c1-73cab34ac178)

**Comment by losh11** [comment]
We're currently aware of this issue. As a temp fix you can disable blockfilterindex by adding `blockfilterindex=0` to you `litecoin.conf` file.

We hope to release a new patch which will automatically detect if prune mode is enabled, and will not attempt to enable blockfilterindex.
