### ISSUE TITLE
not received payment

### ISSUE THREAD

**Issue by tiktoshi2** [litecoin-project/litecoin#953]
Welcome I have not received payment
 
0.00351095
Address ltc1qurxa65r0v33qheq8pulpwf45x3v9che9km8clr

**Comment by losh11** [comment]
This is not the place to ask help questions, but your address does have 0.00351095 LTC in it. Please see this transaction: https://litecoinspace.org/tx/aeea2641d539b87bcf969035a9665c16015951b99d4b2f5244f8a07f6677b93c

If you don't see it in your Litecoin Core balance, please make sure you are full synced. If it is, then please try resyncing your wallet.
