### ISSUE TITLE
The error I got in the last version

### ISSUE THREAD

**Issue by MTCHANNELL** [litecoin-project/litecoin#959]
As you can see in the picture below, I get such an error.
I was doing my synchronization with this command. : "litecoind.exe -prune=550 -datadir=D:\wallet"
 "litecoind.exe v0.21.2.2" I do not get the error shown in the picture in this version. However, if I upgrade to the new version, I get the error in the picture. I get the same error when synchronizing from scratch. Even if I run "litecoin-qt.exe" and synchronize from scratch, I get the same error directly without opening.

![image](https://github.com/litecoin-project/litecoin/assets/94814602/28615e2d-66ae-4118-9106-34a84181287d)

**Comment by losh11** [comment]
Hi, please see this:
https://gist.github.com/losh11/2d4ee89cdb4965bec4c2128cbc579e31

**Comment by MTCHANNELL** [comment]
I understand sir. So is there any harm in using the old version until the new patch arrives? (v0.21.2.2)

**Comment by losh11** [comment]
You can continue using the old release :)
