### ISSUE TITLE
Prune mode doesn't work on v0.21.3

### ISSUE THREAD

**Issue by gades** [litecoin-project/litecoin#977]
After adding prune=550 to  ~/.litecoin/litecoin.conf the daemon stop running 

Error: Prune mode is incompatible with -blockfilterindex.

Here is config:
daemon=1
server=1
rpcbind=0.0.0.0
rpcuser=user
rpcpassword=password
rpcallowip=127.0.0.1
listen=0
prune=550

litecoin-cli -version
Litecoin Core RPC client version v0.21.3

**Comment by losh11** [comment]
Fixed in 0.21.4 release.
